// AUTO-GENERATED by scripts/generate-motion-endpoint-map.ts — do not edit
// Endpoint ID → generated Zod schema and codec mapping for motion models

import { z } from 'zod';

import { motionTransform } from './motion-transform';

import {
  zBytedanceSeedanceV1ProImageToVideoInput,
  zGrokImagineVideoImageToVideoInput,
  zKlingVideoO1ImageToVideoInput,
  zKlingVideoV25TurboProImageToVideoInput,
  zKlingVideoV3ProImageToVideoInput,
  zSora2ImageToVideoInput,
  zV26ImageToVideoFlashInput,
  zVeo31ImageToVideoInput,
  zVeo3Input,
} from './generated/zod.gen';

import {
  BytedanceSeedanceV1ProImageToVideoInputSchema,
  GrokImagineVideoImageToVideoInputSchema,
  KlingVideoO1ImageToVideoInputSchema,
  KlingVideoV25TurboProImageToVideoInputSchema,
  KlingVideoV3ProImageToVideoInputSchema,
  Sora2ImageToVideoInputSchema,
  V26ImageToVideoFlashInputSchema,
  Veo31ImageToVideoInputSchema,
  Veo3InputSchema,
} from './generated/schemas.gen';

export type MotionJSONSchema =
  | typeof BytedanceSeedanceV1ProImageToVideoInputSchema
  | typeof GrokImagineVideoImageToVideoInputSchema
  | typeof KlingVideoO1ImageToVideoInputSchema
  | typeof KlingVideoV25TurboProImageToVideoInputSchema
  | typeof KlingVideoV3ProImageToVideoInputSchema
  | typeof Sora2ImageToVideoInputSchema
  | typeof V26ImageToVideoFlashInputSchema
  | typeof Veo31ImageToVideoInputSchema
  | typeof Veo3InputSchema;

export const MOTION_INPUT_SCHEMAS = {
  'fal-ai/bytedance/seedance/v1/pro/image-to-video':
    zBytedanceSeedanceV1ProImageToVideoInput,
  'fal-ai/veo3': zVeo3Input,
  'fal-ai/veo3.1/image-to-video': zVeo31ImageToVideoInput,
  'fal-ai/kling-video/v2.5-turbo/pro/image-to-video':
    zKlingVideoV25TurboProImageToVideoInput,
  'fal-ai/sora-2/image-to-video': zSora2ImageToVideoInput,
  'fal-ai/kling-video/o1/image-to-video': zKlingVideoO1ImageToVideoInput,
  'fal-ai/kling-video/v3/pro/image-to-video': zKlingVideoV3ProImageToVideoInput,
  'xai/grok-imagine-video/image-to-video': zGrokImagineVideoImageToVideoInput,
  'wan/v2.6/image-to-video/flash': zV26ImageToVideoFlashInput,
};

export type MotionEndpointId = keyof typeof MOTION_INPUT_SCHEMAS;

export type MotionInputFor<T extends MotionEndpointId> = z.infer<
  (typeof MOTION_INPUT_SCHEMAS)[T]
>;

export const MOTION_TRANSFORMS = {
  'fal-ai/bytedance/seedance/v1/pro/image-to-video': motionTransform(
    zBytedanceSeedanceV1ProImageToVideoInput,
    BytedanceSeedanceV1ProImageToVideoInputSchema
  ),
  'fal-ai/veo3': motionTransform(zVeo3Input, Veo3InputSchema),
  'fal-ai/veo3.1/image-to-video': motionTransform(
    zVeo31ImageToVideoInput,
    Veo31ImageToVideoInputSchema
  ),
  'fal-ai/kling-video/v2.5-turbo/pro/image-to-video': motionTransform(
    zKlingVideoV25TurboProImageToVideoInput,
    KlingVideoV25TurboProImageToVideoInputSchema
  ),
  'fal-ai/sora-2/image-to-video': motionTransform(
    zSora2ImageToVideoInput,
    Sora2ImageToVideoInputSchema
  ),
  'fal-ai/kling-video/o1/image-to-video': motionTransform(
    zKlingVideoO1ImageToVideoInput,
    KlingVideoO1ImageToVideoInputSchema
  ),
  'fal-ai/kling-video/v3/pro/image-to-video': motionTransform(
    zKlingVideoV3ProImageToVideoInput,
    KlingVideoV3ProImageToVideoInputSchema
  ),
  'xai/grok-imagine-video/image-to-video': motionTransform(
    zGrokImagineVideoImageToVideoInput,
    GrokImagineVideoImageToVideoInputSchema
  ),
  'wan/v2.6/image-to-video/flash': motionTransform(
    zV26ImageToVideoFlashInput,
    V26ImageToVideoFlashInputSchema
  ),
};
