/**
 * Video Model Input/Output Schemas
 *
 * Auto-generated by: bun scripts/pull-motion-schemas.ts
 * Source: https://fal.ai/api/openapi/queue/openapi.json?endpoint_id=<id>
 *
 * DO NOT EDIT MANUALLY — re-run the script to refresh.
 */

type JSONSchema = {
  type?: string | string[];
  title?: string;
  description?: string;
  properties?: Record<string, JSONSchema>;
  required?: string[];
  items?: JSONSchema;
  anyOf?: JSONSchema[];
  oneOf?: JSONSchema[];
  allOf?: JSONSchema[];
  $ref?: string;
  $defs?: Record<string, JSONSchema>;
  enum?: unknown[];
  const?: unknown;
  default?: unknown;
  format?: string;
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  maxItems?: number;
  pattern?: string;
  additionalProperties?: boolean | JSONSchema;
};

type ModelSchema = {
  input: JSONSchema;
  output: JSONSchema;
};

export const MOTION_MODEL_SCHEMAS: Record<string, ModelSchema> = {
  'fal-ai/bytedance/seedance/v1/pro/image-to-video': {
    input: {
      type: 'object',
      title: 'SeedanceProImageToVideoInput',
      required: ['prompt', 'image_url'],
      properties: {
        prompt: {
          description: 'The text prompt used to generate the video',
          type: 'string',
          title: 'Prompt',
        },
        aspect_ratio: {
          enum: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16', 'auto'],
          description: 'The aspect ratio of the generated video',
          type: 'string',
          title: 'Aspect Ratio',
          default: 'auto',
        },
        resolution: {
          enum: ['480p', '720p', '1080p'],
          description:
            'Video resolution - 480p for faster generation, 720p for balance, 1080p for higher quality',
          type: 'string',
          title: 'Resolution',
          default: '1080p',
        },
        duration: {
          enum: ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
          description: 'Duration of the video in seconds',
          type: 'string',
          title: 'Duration',
          default: '5',
        },
        image_url: {
          description: 'The URL of the image used to generate video',
          type: 'string',
          title: 'Image Url',
        },
        enable_safety_checker: {
          description: 'If set to true, the safety checker will be enabled.',
          type: 'boolean',
          title: 'Enable Safety Checker',
          default: true,
        },
        camera_fixed: {
          description: 'Whether to fix the camera position',
          type: 'boolean',
          title: 'Camera Fixed',
          default: false,
        },
        end_image_url: {
          description:
            'The URL of the image the video ends with. Defaults to None.',
          title: 'End Image Url',
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
        num_frames: {
          description:
            'The number of frames to generate. If provided, will override duration.',
          title: 'Num Frames',
          anyOf: [
            {
              minimum: 29,
              maximum: 289,
              type: 'integer',
            },
            {
              type: 'null',
            },
          ],
        },
        seed: {
          description:
            'Random seed to control video generation. Use -1 for random.',
          title: 'Seed',
          anyOf: [
            {
              type: 'integer',
            },
            {
              type: 'null',
            },
          ],
        },
      },
    },
    output: {
      type: 'object',
      title: 'SeedanceProI2VVideoOutput',
      required: ['video', 'seed'],
      properties: {
        seed: {
          description: 'Seed used for generation',
          type: 'integer',
          title: 'Seed',
        },
        video: {
          type: 'object',
          title: 'File',
          required: ['url'],
          properties: {
            file_size: {
              description: 'The size of the file in bytes.',
              title: 'File Size',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            file_name: {
              description:
                'The name of the file. It will be auto-generated if not provided.',
              title: 'File Name',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            content_type: {
              description: 'The mime type of the file.',
              title: 'Content Type',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            url: {
              description: 'The URL where the file can be downloaded from.',
              type: 'string',
              title: 'Url',
            },
          },
        },
      },
    },
  },
  'fal-ai/veo3': {
    input: {
      title: 'Veo3TextToVideoInput',
      type: 'object',
      required: ['prompt'],
      properties: {
        prompt: {
          title: 'Prompt',
          type: 'string',
          maxLength: 20000,
          description:
            'The text prompt describing the video you want to generate',
        },
        aspect_ratio: {
          enum: ['16:9', '9:16'],
          title: 'Aspect Ratio',
          type: 'string',
          description: 'The aspect ratio of the generated video.',
          default: '16:9',
        },
        resolution: {
          enum: ['720p', '1080p'],
          title: 'Resolution',
          type: 'string',
          description: 'The resolution of the generated video.',
          default: '720p',
        },
        generate_audio: {
          title: 'Generate Audio',
          type: 'boolean',
          description: 'Whether to generate audio for the video.',
          default: true,
        },
        auto_fix: {
          title: 'Auto Fix',
          type: 'boolean',
          description:
            'Whether to automatically attempt to fix prompts that fail content policy or other validation checks by rewriting them.',
          default: true,
        },
        duration: {
          enum: ['4s', '6s', '8s'],
          title: 'Duration',
          type: 'string',
          description: 'The duration of the generated video.',
          default: '8s',
        },
        safety_tolerance: {
          enum: ['1', '2', '3', '4', '5', '6'],
          title: 'Safety Tolerance',
          type: 'string',
          description:
            'The safety tolerance level for content moderation. 1 is the most strict (blocks most content), 6 is the least strict.',
          default: '4',
        },
        seed: {
          title: 'Seed',
          description: 'The seed for the random number generator.',
          anyOf: [
            {
              type: 'integer',
            },
            {
              type: 'null',
            },
          ],
        },
        negative_prompt: {
          title: 'Negative Prompt',
          description: 'A negative prompt to guide the video generation.',
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
      },
    },
    output: {
      title: 'Veo3TextToVideoOutput',
      type: 'object',
      required: ['video'],
      properties: {
        video: {
          title: 'File',
          type: 'object',
          required: ['url'],
          properties: {
            file_size: {
              title: 'File Size',
              description: 'The size of the file in bytes.',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            file_name: {
              title: 'File Name',
              description:
                'The name of the file. It will be auto-generated if not provided.',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            content_type: {
              title: 'Content Type',
              description: 'The mime type of the file.',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            url: {
              title: 'Url',
              type: 'string',
              description: 'The URL where the file can be downloaded from.',
            },
          },
        },
      },
    },
  },
  'fal-ai/veo3.1/image-to-video': {
    input: {
      type: 'object',
      title: 'Veo31ImageToVideoInput',
      required: ['prompt', 'image_url'],
      properties: {
        prompt: {
          title: 'Prompt',
          type: 'string',
          description:
            'The text prompt describing the video you want to generate',
          maxLength: 20000,
        },
        auto_fix: {
          title: 'Auto Fix',
          type: 'boolean',
          description:
            'Whether to automatically attempt to fix prompts that fail content policy or other validation checks by rewriting them.',
          default: false,
        },
        duration: {
          enum: ['4s', '6s', '8s'],
          title: 'Duration',
          type: 'string',
          description: 'The duration of the generated video.',
          default: '8s',
        },
        generate_audio: {
          title: 'Generate Audio',
          type: 'boolean',
          description: 'Whether to generate audio for the video.',
          default: true,
        },
        resolution: {
          enum: ['720p', '1080p', '4k'],
          title: 'Resolution',
          type: 'string',
          description: 'The resolution of the generated video.',
          default: '720p',
        },
        aspect_ratio: {
          enum: ['auto', '16:9', '9:16'],
          title: 'Aspect Ratio',
          type: 'string',
          description:
            'The aspect ratio of the generated video. Only 16:9 and 9:16 are supported.',
          default: 'auto',
        },
        image_url: {
          title: 'Image URL',
          type: 'string',
          description:
            'URL of the input image to animate. Should be 720p or higher resolution in 16:9 or 9:16 aspect ratio. If the image is not in 16:9 or 9:16 aspect ratio, it will be cropped to fit.',
        },
        safety_tolerance: {
          enum: ['1', '2', '3', '4', '5', '6'],
          title: 'Safety Tolerance',
          type: 'string',
          description:
            'The safety tolerance level for content moderation. 1 is the most strict (blocks most content), 6 is the least strict.',
          default: '4',
        },
        seed: {
          title: 'Seed',
          description: 'The seed for the random number generator.',
          anyOf: [
            {
              type: 'integer',
            },
            {
              type: 'null',
            },
          ],
        },
        negative_prompt: {
          title: 'Negative Prompt',
          description: 'A negative prompt to guide the video generation.',
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
      },
    },
    output: {
      type: 'object',
      title: 'Veo31ImageToVideoOutput',
      required: ['video'],
      properties: {
        video: {
          type: 'object',
          title: 'File',
          required: ['url'],
          properties: {
            file_size: {
              title: 'File Size',
              description: 'The size of the file in bytes.',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            file_name: {
              title: 'File Name',
              description:
                'The name of the file. It will be auto-generated if not provided.',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            content_type: {
              title: 'Content Type',
              description: 'The mime type of the file.',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            url: {
              title: 'Url',
              type: 'string',
              description: 'The URL where the file can be downloaded from.',
            },
          },
        },
      },
    },
  },
  'fal-ai/kling-video/v2.5-turbo/pro/image-to-video': {
    input: {
      type: 'object',
      title: 'ImageToVideoV25ProRequest',
      required: ['prompt', 'image_url'],
      properties: {
        prompt: {
          maxLength: 2500,
          type: 'string',
          title: 'Prompt',
        },
        duration: {
          enum: ['5', '10'],
          description: 'The duration of the generated video in seconds',
          type: 'string',
          title: 'Duration',
          default: '5',
        },
        cfg_scale: {
          minimum: 0,
          maximum: 1,
          type: 'number',
          description:
            '\n            The CFG (Classifier Free Guidance) scale is a measure of how close you want\n            the model to stick to your prompt.\n        ',
          title: 'Cfg Scale',
          default: 0.5,
        },
        tail_image_url: {
          description: 'URL of the image to be used for the end of the video',
          title: 'Tail Image Url',
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
        negative_prompt: {
          maxLength: 2500,
          type: 'string',
          title: 'Negative Prompt',
          default: 'blur, distort, and low quality',
        },
        image_url: {
          description: 'URL of the image to be used for the video',
          type: 'string',
          title: 'Image Url',
        },
      },
    },
    output: {
      type: 'object',
      title: 'ImageToVideoV25ProOutput',
      required: ['video'],
      properties: {
        video: {
          type: 'object',
          title: 'File',
          required: ['url'],
          properties: {
            file_size: {
              description: 'The size of the file in bytes.',
              title: 'File Size',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            file_name: {
              description:
                'The name of the file. It will be auto-generated if not provided.',
              title: 'File Name',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            content_type: {
              description: 'The mime type of the file.',
              title: 'Content Type',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            url: {
              description: 'The URL where the file can be downloaded from.',
              type: 'string',
              title: 'Url',
            },
          },
        },
      },
    },
  },
  'fal-ai/sora-2/image-to-video': {
    input: {
      title: 'ImageToVideoInput',
      type: 'object',
      required: ['prompt', 'image_url'],
      properties: {
        prompt: {
          maxLength: 5000,
          minLength: 1,
          title: 'Prompt',
          description:
            'The text prompt describing the video you want to generate',
          type: 'string',
        },
        aspect_ratio: {
          enum: ['auto', '9:16', '16:9'],
          title: 'Aspect Ratio',
          type: 'string',
          description: 'The aspect ratio of the generated video',
          default: 'auto',
        },
        duration: {
          enum: [4, 8, 12, 16, 20],
          title: 'Duration',
          type: 'integer',
          description: 'Duration of the generated video in seconds',
          default: 4,
        },
        resolution: {
          enum: ['auto', '720p'],
          title: 'Resolution',
          type: 'string',
          description: 'The resolution of the generated video',
          default: 'auto',
        },
        character_ids: {
          title: 'Character IDs',
          description:
            'Up to two character IDs (from create-character) to use in the video. Refer to characters by name in the prompt. When set, only the OpenAI provider is used.',
          anyOf: [
            {
              maxItems: 2,
              type: 'array',
              items: {
                type: 'string',
              },
            },
            {
              type: 'null',
            },
          ],
        },
        image_url: {
          title: 'Image URL',
          type: 'string',
          description: 'The URL of the image to use as the first frame',
        },
        model: {
          enum: ['sora-2', 'sora-2-2025-12-08', 'sora-2-2025-10-06'],
          title: 'Model',
          type: 'string',
          description:
            'The model to use for the generation. When the default model is selected, the latest snapshot of the model will be used - otherwise, select a specific snapshot of the model.',
          default: 'sora-2',
        },
        delete_video: {
          title: 'Delete Video',
          type: 'boolean',
          description:
            'Whether to delete the video after generation for privacy reasons. If True, the video cannot be used for remixing and will be permanently deleted.',
          default: true,
        },
        detect_and_block_ip: {
          title: 'Detect And Block Ip',
          type: 'boolean',
          description:
            'If enabled, the prompt (and image for image-to-video) will be checked for known intellectual property references and the request will be blocked if any are detected.',
          default: false,
        },
      },
    },
    output: {
      title: 'ImageToVideoOutput',
      type: 'object',
      required: ['video', 'video_id'],
      properties: {
        thumbnail: {
          description: 'Thumbnail image for the video',
          anyOf: [
            {
              title: 'ImageFile',
              type: 'object',
              required: ['url'],
              properties: {
                file_size: {
                  title: 'File Size',
                  description: 'The size of the file in bytes.',
                  anyOf: [
                    {
                      type: 'integer',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
                height: {
                  title: 'Height',
                  description: 'The height of the image',
                  anyOf: [
                    {
                      type: 'integer',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
                file_name: {
                  title: 'File Name',
                  description:
                    'The name of the file. It will be auto-generated if not provided.',
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
                content_type: {
                  title: 'Content Type',
                  description: 'The mime type of the file.',
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
                url: {
                  title: 'Url',
                  type: 'string',
                  description: 'The URL where the file can be downloaded from.',
                },
                width: {
                  title: 'Width',
                  description: 'The width of the image',
                  anyOf: [
                    {
                      type: 'integer',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
              },
            },
            {
              type: 'null',
            },
          ],
        },
        video_id: {
          title: 'Video ID',
          type: 'string',
          description: 'The ID of the generated video',
        },
        spritesheet: {
          description: 'Spritesheet image for the video',
          anyOf: [
            {
              title: 'ImageFile',
              type: 'object',
              required: ['url'],
              properties: {
                file_size: {
                  title: 'File Size',
                  description: 'The size of the file in bytes.',
                  anyOf: [
                    {
                      type: 'integer',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
                height: {
                  title: 'Height',
                  description: 'The height of the image',
                  anyOf: [
                    {
                      type: 'integer',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
                file_name: {
                  title: 'File Name',
                  description:
                    'The name of the file. It will be auto-generated if not provided.',
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
                content_type: {
                  title: 'Content Type',
                  description: 'The mime type of the file.',
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
                url: {
                  title: 'Url',
                  type: 'string',
                  description: 'The URL where the file can be downloaded from.',
                },
                width: {
                  title: 'Width',
                  description: 'The width of the image',
                  anyOf: [
                    {
                      type: 'integer',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
              },
            },
            {
              type: 'null',
            },
          ],
        },
        video: {
          title: 'VideoFile',
          type: 'object',
          required: ['url'],
          properties: {
            file_size: {
              title: 'File Size',
              description: 'The size of the file in bytes.',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            duration: {
              title: 'Duration',
              description: 'The duration of the video',
              anyOf: [
                {
                  type: 'number',
                },
                {
                  type: 'null',
                },
              ],
            },
            height: {
              title: 'Height',
              description: 'The height of the video',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            url: {
              title: 'Url',
              type: 'string',
              description: 'The URL where the file can be downloaded from.',
            },
            fps: {
              title: 'Fps',
              description: 'The FPS of the video',
              anyOf: [
                {
                  type: 'number',
                },
                {
                  type: 'null',
                },
              ],
            },
            width: {
              title: 'Width',
              description: 'The width of the video',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            file_name: {
              title: 'File Name',
              description:
                'The name of the file. It will be auto-generated if not provided.',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            content_type: {
              title: 'Content Type',
              description: 'The mime type of the file.',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            num_frames: {
              title: 'Num Frames',
              description: 'The number of frames in the video',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
          },
        },
      },
    },
  },
  'fal-ai/kling-video/o1/image-to-video': {
    input: {
      type: 'object',
      title: 'OmniVideoImageToVideoInput',
      required: ['prompt', 'start_image_url'],
      properties: {
        prompt: {
          maxLength: 2500,
          type: 'string',
          description:
            'Use @Image1 to reference the start frame, @Image2 to reference the end frame.',
          title: 'Prompt',
        },
        duration: {
          enum: ['3', '4', '5', '6', '7', '8', '9', '10'],
          description: 'Video duration in seconds.',
          type: 'string',
          title: 'Duration',
          default: '5',
        },
        start_image_url: {
          description:
            'Image to use as the first frame of the video.\n\nMax file size: 10.0MB, Min width: 300px, Min height: 300px, Min aspect ratio: 0.40, Max aspect ratio: 2.50, Timeout: 20.0s',
          type: 'string',
          title: 'Start Image Url',
        },
        end_image_url: {
          description: 'Image to use as the last frame of the video.',
          title: 'End Image Url',
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
      },
    },
    output: {
      type: 'object',
      title: 'OmniVideoImageToVideoOutput',
      description: 'Output for Kling Omni Video generation.',
      required: ['video'],
      properties: {
        video: {
          type: 'object',
          title: 'File',
          required: ['url'],
          properties: {
            file_size: {
              description: 'The size of the file in bytes.',
              title: 'File Size',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            file_name: {
              description:
                'The name of the file. It will be auto-generated if not provided.',
              title: 'File Name',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            content_type: {
              description: 'The mime type of the file.',
              title: 'Content Type',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            url: {
              description: 'The URL where the file can be downloaded from.',
              type: 'string',
              title: 'Url',
            },
          },
        },
      },
    },
  },
  'fal-ai/kling-video/v3/pro/image-to-video': {
    input: {
      type: 'object',
      title: 'ImageToVideoV3ProRequest',
      required: ['start_image_url'],
      properties: {
        prompt: {
          description:
            'Text prompt for video generation. Either prompt or multi_prompt must be provided, but not both.',
          title: 'Prompt',
          anyOf: [
            {
              maxLength: 2500,
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
        duration: {
          enum: [
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '10',
            '11',
            '12',
            '13',
            '14',
            '15',
          ],
          description: 'The duration of the generated video in seconds',
          type: 'string',
          title: 'Duration',
          default: '5',
        },
        start_image_url: {
          description: 'URL of the image to be used for the video',
          type: 'string',
          title: 'Start Image Url',
        },
        multi_prompt: {
          description:
            'List of prompts for multi-shot video generation. If provided, divides the video into multiple shots.',
          title: 'Multi Prompt',
          anyOf: [
            {
              type: 'array',
              items: {
                type: 'object',
                title: 'KlingV3MultiPromptElement',
                required: ['prompt'],
                properties: {
                  prompt: {
                    description: 'The prompt for this shot.',
                    type: 'string',
                    title: 'Prompt',
                  },
                  duration: {
                    enum: [
                      '1',
                      '2',
                      '3',
                      '4',
                      '5',
                      '6',
                      '7',
                      '8',
                      '9',
                      '10',
                      '11',
                      '12',
                      '13',
                      '14',
                      '15',
                    ],
                    description: 'The duration of this shot in seconds',
                    type: 'string',
                    title: 'Duration',
                    default: '5',
                  },
                },
              },
            },
            {
              type: 'null',
            },
          ],
        },
        generate_audio: {
          description:
            'Whether to generate native audio for the video. Supports Chinese and English voice output. Other languages are automatically translated to English. For English speech, use lowercase letters; for acronyms or proper nouns, use uppercase.',
          type: 'boolean',
          title: 'Generate Audio',
          default: true,
        },
        shot_type: {
          description:
            'The type of multi-shot video generation. Required when multi_prompt is provided.',
          type: 'string',
          title: 'Shot Type',
          const: 'customize',
          default: 'customize',
        },
        elements: {
          description:
            'Elements (characters/objects) to include in the video. Each example can either be an image set (frontal + reference images) or a video. Reference in prompt as @Element1, @Element2, etc.',
          title: 'Elements',
          anyOf: [
            {
              type: 'array',
              items: {
                type: 'object',
                title: 'KlingV3ComboElementInput',
                properties: {
                  video_url: {
                    description:
                      'The video URL of the element. A request can only have one element with a video.',
                    title: 'Video Url',
                    anyOf: [
                      {
                        type: 'string',
                      },
                      {
                        type: 'null',
                      },
                    ],
                  },
                  voice_id: {
                    description:
                      'The voice ID for this element. The voice will be binded to the element and references to this element will use the binded voice. Voice binding is only supported for video elements, and cannot be used with image elements. Get voice IDs from the following endpoint: https://fal.ai/models/fal-ai/kling-video/create-voice',
                    title: 'Voice Id',
                    anyOf: [
                      {
                        type: 'string',
                      },
                      {
                        type: 'null',
                      },
                    ],
                  },
                  reference_image_urls: {
                    description:
                      'Additional reference images from different angles. 1-3 images supported. At least one image is required.',
                    title: 'Reference Image Urls',
                    anyOf: [
                      {
                        type: 'array',
                        items: {
                          type: 'string',
                        },
                      },
                      {
                        type: 'null',
                      },
                    ],
                  },
                  frontal_image_url: {
                    description:
                      'The frontal image of the element (main view).',
                    title: 'Frontal Image Url',
                    anyOf: [
                      {
                        type: 'string',
                      },
                      {
                        type: 'null',
                      },
                    ],
                  },
                },
              },
            },
            {
              type: 'null',
            },
          ],
        },
        end_image_url: {
          description: 'URL of the image to be used for the end of the video',
          title: 'End Image Url',
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
        negative_prompt: {
          maxLength: 2500,
          type: 'string',
          title: 'Negative Prompt',
          default: 'blur, distort, and low quality',
        },
        cfg_scale: {
          minimum: 0,
          maximum: 1,
          type: 'number',
          description:
            '\n            The CFG (Classifier Free Guidance) scale is a measure of how close you want\n            the model to stick to your prompt.\n        ',
          title: 'Cfg Scale',
          default: 0.5,
        },
      },
    },
    output: {
      type: 'object',
      title: 'ImageToVideoV3ProOutput',
      required: ['video'],
      properties: {
        video: {
          type: 'object',
          title: 'File',
          required: ['url'],
          properties: {
            file_size: {
              description: 'The size of the file in bytes.',
              title: 'File Size',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            file_name: {
              description:
                'The name of the file. It will be auto-generated if not provided.',
              title: 'File Name',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            content_type: {
              description: 'The mime type of the file.',
              title: 'Content Type',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            url: {
              description: 'The URL where the file can be downloaded from.',
              type: 'string',
              title: 'Url',
            },
          },
        },
      },
    },
  },
  'xai/grok-imagine-video/image-to-video': {
    input: {
      title: 'XAIImageToVideoInput',
      type: 'object',
      required: ['prompt', 'image_url'],
      properties: {
        prompt: {
          description:
            'Text description of desired changes or motion in the video.',
          type: 'string',
          maxLength: 4096,
          title: 'Prompt',
        },
        aspect_ratio: {
          description: 'Aspect ratio of the generated video.',
          title: 'Aspect Ratio',
          default: 'auto',
          anyOf: [
            {
              enum: ['auto', '16:9', '4:3', '3:2', '1:1', '2:3', '3:4', '9:16'],
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
        resolution: {
          enum: ['480p', '720p'],
          description: 'Resolution of the output video.',
          type: 'string',
          title: 'Resolution',
          default: '720p',
        },
        duration: {
          description: 'Video duration in seconds.',
          type: 'integer',
          minimum: 1,
          title: 'Duration',
          maximum: 15,
          default: 6,
        },
        image_url: {
          description: 'URL of the input image for video generation.',
          type: 'string',
          title: 'Image URL',
        },
      },
    },
    output: {
      title: 'XAIImageToVideoOutput',
      type: 'object',
      required: ['video'],
      properties: {
        video: {
          title: 'VideoFile',
          type: 'object',
          required: ['url'],
          properties: {
            file_size: {
              description: 'The size of the file in bytes.',
              title: 'File Size',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            duration: {
              description: 'The duration of the video',
              title: 'Duration',
              anyOf: [
                {
                  type: 'number',
                },
                {
                  type: 'null',
                },
              ],
            },
            height: {
              description: 'The height of the video',
              title: 'Height',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            url: {
              description: 'The URL where the file can be downloaded from.',
              type: 'string',
              title: 'Url',
            },
            fps: {
              description: 'The FPS of the video',
              title: 'Fps',
              anyOf: [
                {
                  type: 'number',
                },
                {
                  type: 'null',
                },
              ],
            },
            width: {
              description: 'The width of the video',
              title: 'Width',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            file_name: {
              description:
                'The name of the file. It will be auto-generated if not provided.',
              title: 'File Name',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            content_type: {
              description: 'The mime type of the file.',
              title: 'Content Type',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            num_frames: {
              description: 'The number of frames in the video',
              title: 'Num Frames',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
          },
        },
      },
    },
  },
  'wan/v2.6/image-to-video/flash': {
    input: {
      title: 'ImageToVideoInput',
      type: 'object',
      description: 'Input for Wan 2.6 image-to-video generation',
      required: ['prompt', 'image_url'],
      properties: {
        prompt: {
          title: 'Prompt',
          type: 'string',
          minLength: 1,
          description:
            'The text prompt describing the desired video motion. Max 800 characters.',
          maxLength: 800,
        },
        duration: {
          enum: ['5', '10', '15'],
          title: 'Duration',
          type: 'string',
          description:
            'Duration of the generated video in seconds. Choose between 5, 10 or 15 seconds.',
          default: '5',
        },
        resolution: {
          enum: ['720p', '1080p'],
          title: 'Resolution',
          type: 'string',
          description: 'Video resolution. Valid values: 720p, 1080p',
          default: '1080p',
        },
        enable_safety_checker: {
          title: 'Enable Safety Checker',
          type: 'boolean',
          description: 'If set to true, the safety checker will be enabled.',
          default: true,
        },
        image_url: {
          title: 'Image URL',
          type: 'string',
          description:
            'URL of the image to use as the first frame. Must be publicly accessible or base64 data URI. Image dimensions must be between 240 and 7680.',
        },
        enable_prompt_expansion: {
          title: 'Enable Prompt Expansion',
          type: 'boolean',
          description: 'Whether to enable prompt rewriting using LLM.',
          default: true,
        },
        seed: {
          title: 'Seed',
          description:
            'Random seed for reproducibility. If None, a random seed is chosen.',
          anyOf: [
            {
              type: 'integer',
            },
            {
              type: 'null',
            },
          ],
        },
        multi_shots: {
          title: 'Multi Shots',
          type: 'boolean',
          description:
            'When true, enables intelligent multi-shot segmentation. Only active when enable_prompt_expansion is True. Set to false for single-shot generation.',
          default: false,
        },
        negative_prompt: {
          title: 'Negative Prompt',
          description:
            'Negative prompt to describe content to avoid. Max 500 characters.',
          default: '',
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
        audio_url: {
          title: 'Audio Url',
          description:
            '\nURL of the audio to use as the background music. Must be publicly accessible.\nLimit handling: If the audio duration exceeds the duration value (5, 10, or 15 seconds),\nthe audio is truncated to the first N seconds, and the rest is discarded. If\nthe audio is shorter than the video, the remaining part of the video will be silent.\nFor example, if the audio is 3 seconds long and the video duration is 5 seconds, the\nfirst 3 seconds of the output video will have sound, and the last 2 seconds will be silent.\n- Format: WAV, MP3.\n- Duration: 3 to 30 s.\n- File size: Up to 15 MB.\n',
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
      },
    },
    output: {
      title: 'ImageToVideoOutput',
      type: 'object',
      description: 'Output for image-to-video generation',
      required: ['video', 'seed'],
      properties: {
        actual_prompt: {
          title: 'Actual Prompt',
          description: 'The actual prompt used if prompt rewriting was enabled',
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
        seed: {
          title: 'Seed',
          type: 'integer',
          description: 'The seed used for generation',
        },
        video: {
          title: 'VideoFile',
          type: 'object',
          required: ['url'],
          properties: {
            file_size: {
              title: 'File Size',
              description: 'The size of the file in bytes.',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            duration: {
              title: 'Duration',
              description: 'The duration of the video',
              anyOf: [
                {
                  type: 'number',
                },
                {
                  type: 'null',
                },
              ],
            },
            height: {
              title: 'Height',
              description: 'The height of the video',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            url: {
              title: 'Url',
              type: 'string',
              description: 'The URL where the file can be downloaded from.',
            },
            width: {
              title: 'Width',
              description: 'The width of the video',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            fps: {
              title: 'Fps',
              description: 'The FPS of the video',
              anyOf: [
                {
                  type: 'number',
                },
                {
                  type: 'null',
                },
              ],
            },
            file_name: {
              title: 'File Name',
              description:
                'The name of the file. It will be auto-generated if not provided.',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
            num_frames: {
              title: 'Num Frames',
              description: 'The number of frames in the video',
              anyOf: [
                {
                  type: 'integer',
                },
                {
                  type: 'null',
                },
              ],
            },
            content_type: {
              title: 'Content Type',
              description: 'The mime type of the file.',
              anyOf: [
                {
                  type: 'string',
                },
                {
                  type: 'null',
                },
              ],
            },
          },
        },
      },
    },
  },
};

// -- Derived prompt limits ----------------------------------------------------

/** Prompt character limits by fal.ai endpoint ID. undefined = no limit documented in schema. */
export const MOTION_PROMPT_LIMITS: Record<string, number | undefined> =
  Object.fromEntries(
    Object.entries(MOTION_MODEL_SCHEMAS).map(([id, schema]) => {
      const promptProp = schema.input.properties?.prompt;
      const maxLength =
        promptProp?.maxLength ??
        promptProp?.anyOf?.find(
          (s): s is JSONSchema & { maxLength: number } =>
            typeof s === 'object' && 'maxLength' in s
        )?.maxLength;
      return [id, maxLength];
    })
  );
