/**
 * Type augmentation for Cloudflare Workflow bindings.
 *
 * cloudflare-env.d.ts is auto-generated by `wrangler types` and only includes
 * env vars (strings). Workflow bindings need to be declared separately because
 * wrangler doesn't auto-generate them yet.
 *
 * When wrangler types adds workflow support, this file can be removed.
 */

import type { ImageWorkflowInput } from '@/lib/workflow/types';

declare global {
  namespace Cloudflare {
    interface Env {
      /** Cloudflare Workflow binding for image generation (prototype) */
      CF_IMAGE_WORKFLOW: Workflow<ImageWorkflowInput>;
      /** Feature flag: set to "true" to route image generation through CF Workflows instead of Upstash */
      USE_CF_WORKFLOWS?: string;
    }
  }
}
