#!/usr/bin/env zsh

# Velro Services Startup Script
# Starts all required services for development

set -e  # Exit on error

echo "🚀 Starting Velro development services..."

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Start Docker if not running
if command_exists docker; then
    if ! docker info >/dev/null 2>&1; then
        echo "🐳 Starting Docker..."
        sudo service docker start || echo "⚠️  Could not start Docker service"
        sleep 2
    else
        echo "✅ Docker is running"
    fi
else
    echo "❌ Docker not found - Supabase requires Docker"
fi

# Check for environment files
echo "🔍 Checking environment files..."
if [ ! -f "/workspaces/velro/.env.local" ]; then
    echo "⚠️  Warning: .env.local not found"
    echo "   Run 'vercel env pull' to get production environment variables"
fi
if [ ! -f "/workspaces/velro/.env.development.local" ]; then
    echo "⚠️  Warning: .env.development.local not found"
    echo "   This file will be created with local Supabase credentials"
fi

# Start Supabase local services
    echo "🗄️ Starting Supabase local services..."
    cd /workspaces/velro
    
    # Check if Supabase is already running
    if pnpx supabase status 2>/dev/null | grep -q "RUNNING"; then
        echo "✅ Supabase is already running"
    else
        # Start Supabase in the background
        pnpx supabase start &
        SUPABASE_PID=$!
        
        # Wait for Supabase to be ready (max 30 seconds)
        echo "⏳ Waiting for Supabase to be ready..."
        for i in {1..30}; do
            if pnpx supabase status 2>/dev/null | grep -q "RUNNING"; then
                echo "✅ Supabase is ready!"
                break
            fi
            sleep 1
        done
    fi
    
    # Get Supabase credentials and update .env.development.local
    if pnpx supabase status 2>/dev/null | grep -q "RUNNING"; then
        echo "📋 Updating .env.development.local with Supabase credentials..."
        
        # Get the credentials
        SUPABASE_URL=$(pnpx supabase status 2>/dev/null | grep "API URL" | awk '{print $NF}')
        ANON_KEY=$(pnpx supabase status 2>/dev/null | grep "anon key" | awk '{print $NF}')
        SERVICE_ROLE_KEY=$(pnpx supabase status 2>/dev/null | grep "service_role key" | awk '{print $NF}')
        
        # Create or update .env.development.local
        if [ -n "$ANON_KEY" ] && [ -n "$SERVICE_ROLE_KEY" ]; then
            cat > /workspaces/velro/.env.development.local << EOF
# Local Development Environment Overrides
# This file is for development-specific variables that override .env.local
# Auto-generated by start-services.sh

# Supabase Local Configuration
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-http://127.0.0.1:54321}
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY

# Development flags
NODE_ENV=development
NEXT_PUBLIC_DEBUG=true

# Add any other local development overrides below
EOF
            echo "✅ Updated .env.development.local with local Supabase credentials"
        else
            echo "⚠️  Could not get Supabase credentials"
        fi
        
        echo ""
        echo "📋 Supabase Local Endpoints:"
        echo "   API: ${SUPABASE_URL:-http://127.0.0.1:54321}"
        echo "   Studio: http://127.0.0.1:54323"
        echo "   DB: postgresql://postgres:postgres@127.0.0.1:54322/postgres"
        echo ""
    fi
else
    echo "⚠️  Supabase CLI not available - use 'pnpx supabase' to run Supabase commands"
fi

# Start QStash development server
echo "📬 Starting QStash development server..."
cd /workspaces/velro

# Check if QStash dev server is already running
if lsof -Pi :9090 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo "✅ QStash dev server is already running on port 9090"
else
    echo "   Starting QStash dev server in the background..."
    nohup pnpx @upstash/qstash-cli dev > /tmp/qstash.log 2>&1 &
    echo $! > /tmp/qstash.pid
    
    # Wait a moment for the server to start
    sleep 2
    
    # Check if it started successfully
    if lsof -Pi :9090 -sTCP:LISTEN -t >/dev/null 2>&1; then
        echo "✅ QStash dev server started successfully on port 9090!"
        echo "   View logs: tail -f /tmp/qstash.log"
    else
        echo "⚠️  QStash dev server may still be starting. Check /tmp/qstash.log for details"
    fi
fi
echo ""

# Start Next.js development server
if [ -f "/workspaces/velro/package.json" ]; then
    echo "🌐 Starting Next.js development server..."
    cd /workspaces/velro
    
    # Check if dev server is already running on port 3000
    if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1; then
        echo "✅ Next.js dev server is already running on port 3000"
    else
        echo "📦 Starting Next.js with Turbopack..."
        echo "   Access the app at: http://localhost:3000"
        echo ""
        echo "💡 Running 'pnpm dev' in the background..."
        echo "   To see logs: pnpm dev (in a new terminal)"
        echo "   To stop: pkill -f 'next dev' or Ctrl+C in the terminal running dev"
        
        # Start in background and redirect output to a log file
        nohup pnpm dev > /tmp/nextjs.log 2>&1 &
        echo $! > /tmp/nextjs.pid
        
        # Wait a moment for the server to start
        sleep 3
        
        # Check if it started successfully
        if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1; then
            echo "✅ Next.js dev server started successfully!"
            echo "   View logs: tail -f /tmp/nextjs.log"
        else
            echo "⚠️  Next.js may still be starting. Check /tmp/nextjs.log for details"
        fi
    fi
else
    echo "❌ package.json not found in /workspaces/velro"
fi

echo ""
echo "🎉 Development services startup complete!"
echo ""
echo "📊 Service Status:"
echo "  • Next.js App: http://localhost:3000"
echo "  • Supabase Studio: http://localhost:54323"
echo "  • Inbucket (Email): http://localhost:54324"
echo "  • Supabase API: http://localhost:54321"
echo "  • QStash Dev Server: http://localhost:9090"
echo ""
echo "🛠️ Useful commands:"
echo "  • pnpx supabase status - Check Supabase services"
echo "  • pnpx supabase stop - Stop Supabase"
echo "  • pnpx @upstash/qstash-cli dev - Start QStash dev server"
echo "  • pnpm dev - Start Next.js dev server (if not running)"
echo "  • tail -f /tmp/nextjs.log - View Next.js logs"
echo "  • tail -f /tmp/qstash.log - View QStash logs"
echo ""