/**
 * Generate endpoint-map.ts and prompt-limits.ts for motion models
 *
 * Reads the generated types.gen.ts and zod.gen.ts to extract endpoint info,
 * then generates typed maps from endpoint ID → Zod schema and prompt limits.
 *
 * Usage: bun scripts/generate-motion-endpoint-map.ts
 * (Called automatically by pull-motion-schemas.ts after codegen)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const GENERATED_DIR = join(
  import.meta.dir,
  '..',
  'src',
  'lib',
  'motion',
  'generated'
);
const JSON_PATH = join(import.meta.dir, '..', 'json', 'fal.models.motion.json');

type EndpointInfo = {
  endpointId: string;
  inputType: string;
  outputType: string;
  zodInputSchema: string;
};

function extractEndpoints(): EndpointInfo[] {
  const typesContent = readFileSync(
    join(GENERATED_DIR, 'types.gen.ts'),
    'utf-8'
  );
  const zodContent = readFileSync(join(GENERATED_DIR, 'zod.gen.ts'), 'utf-8');
  const endpoints: EndpointInfo[] = [];

  // Match PostXxxData types to extract body type and URL
  const postTypeRegex =
    /export type (Post\w+)Data = \{[\s\S]*?body:\s*(\b\w+\b);?[\s\S]*?url:\s*["']([^"']+)["']/g;

  let match;
  while ((match = postTypeRegex.exec(typesContent)) !== null) {
    const inputType = match[2];
    const urlPath = match[3];
    if (!inputType || !urlPath) continue;

    const endpointId = urlPath.replace(/^\//, '');
    const outputType = inputType.replace(/Input(Type\d+)?$/, 'Output$1');

    // Find matching Zod schema name
    const zodInputSchema = `z${inputType}`;
    if (!zodContent.includes(`export const ${zodInputSchema}`)) {
      console.warn(
        `  Warning: No Zod schema ${zodInputSchema} for ${endpointId}`
      );
      continue;
    }

    // Skip non-POST endpoints (status, cancel, etc.)
    if (urlPath.includes('/requests/')) continue;

    endpoints.push({ endpointId, inputType, outputType, zodInputSchema });
  }

  return endpoints;
}

function extractPromptLimits(): Record<string, number | undefined> {
  const json = JSON.parse(readFileSync(JSON_PATH, 'utf-8'));
  const limits: Record<string, number | undefined> = {};

  for (const model of json.models) {
    const id = model.endpoint_id;
    const spec = model.openapi;
    const inputPath = `/${id}`;
    const postOp = spec.paths?.[inputPath]?.post;
    const schemaRef =
      postOp?.requestBody?.content?.['application/json']?.schema;

    if (!schemaRef) continue;

    // Resolve $ref to get the actual schema
    let inputSchema = schemaRef;
    if (schemaRef.$ref) {
      const refName = schemaRef.$ref.replace('#/components/schemas/', '');
      inputSchema = spec.components?.schemas?.[refName] ?? schemaRef;
    }

    // Extract prompt maxLength
    const promptProp = inputSchema.properties?.prompt;
    if (!promptProp) {
      limits[id] = undefined;
      continue;
    }

    // maxLength directly on prompt, or in anyOf for nullable prompts
    let maxLength = promptProp.maxLength;
    if (!maxLength && promptProp.anyOf) {
      for (const variant of promptProp.anyOf) {
        if (variant.maxLength) {
          maxLength = variant.maxLength;
          break;
        }
      }
    }
    // Wan: documented in description but not in schema
    if (!maxLength && promptProp.description?.includes('Max 800')) {
      maxLength = 800;
    }

    limits[id] = maxLength;
  }

  return limits;
}

function generateEndpointMap(endpoints: EndpointInfo[]): string {
  const zodImports = endpoints.map((e) => e.zodInputSchema).sort();

  return `// AUTO-GENERATED by scripts/generate-motion-endpoint-map.ts — do not edit
// Endpoint ID → generated Zod schema mapping for motion models

import { z } from 'zod';

import {
${zodImports.map((s) => `  ${s},`).join('\n')}
} from './zod.gen';

export const MOTION_INPUT_SCHEMAS = {
${endpoints.map((e) => `  ${JSON.stringify(e.endpointId)}: ${e.zodInputSchema},`).join('\n')}
};

export type MotionEndpointId = keyof typeof MOTION_INPUT_SCHEMAS;

export type MotionInputFor<T extends MotionEndpointId> = z.infer<
  (typeof MOTION_INPUT_SCHEMAS)[T]
>;
`;
}

function generatePromptLimits(
  limits: Record<string, number | undefined>,
  endpointIds: string[]
): string {
  return `// AUTO-GENERATED by scripts/generate-motion-endpoint-map.ts — do not edit
// Prompt character limits by fal.ai endpoint ID
// Source: maxLength from fal.ai OpenAPI schemas (json/fal.models.motion.json)

import type { MotionEndpointId } from './endpoint-map';

export const MOTION_PROMPT_LIMITS: Record<MotionEndpointId, number | undefined> = {
${endpointIds.map((id) => `  ${JSON.stringify(id)}: ${limits[id] === undefined ? 'undefined' : String(limits[id])},`).join('\n')}
};
`;
}

function main() {
  console.log('Generating motion endpoint map...\n');

  const endpoints = extractEndpoints();
  console.log(`  Found ${endpoints.length} endpoints:`);
  for (const e of endpoints) {
    console.log(`    ${e.endpointId} → ${e.zodInputSchema}`);
  }

  const limits = extractPromptLimits();
  console.log('\n  Prompt limits:');
  for (const e of endpoints) {
    const limit = limits[e.endpointId];
    console.log(`    ${e.endpointId}: ${limit ?? 'none'}`);
  }

  const endpointMapPath = join(GENERATED_DIR, 'endpoint-map.ts');
  writeFileSync(endpointMapPath, generateEndpointMap(endpoints));
  console.log(`\n  Written ${endpointMapPath}`);

  const promptLimitsPath = join(GENERATED_DIR, 'prompt-limits.ts');
  const endpointIds = endpoints.map((e) => e.endpointId);
  writeFileSync(promptLimitsPath, generatePromptLimits(limits, endpointIds));
  console.log(`  Written ${promptLimitsPath}`);
}

main();
