#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

ENV_FILE=".env.development.local"

echo -e "${BLUE}Setting up local development environment...${NC}"
echo ""

# Check if .env.development.local already exists
if [ -f "$ENV_FILE" ]; then
  echo -e "${YELLOW}$ENV_FILE already exists.${NC}"
  read -p "Overwrite? (y/N) " -n 1 -r
  echo ""
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${GREEN}Keeping existing $ENV_FILE${NC}"
    exit 0
  fi
fi

# Generate a random secret for BetterAuth
BETTER_AUTH_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 32)

# QStash local development credentials (defaults for Docker emulator)
QSTASH_URL="${QSTASH_URL:-http://127.0.0.1:8080}"
QSTASH_TOKEN="${QSTASH_TOKEN:-eyJVc2VySUQiOiJkZWZhdWx0VXNlciIsIlBhc3N3b3JkIjoiZGVmYXVsdFBhc3N3b3JkIn0=}"
QSTASH_CURRENT_SIGNING_KEY="${QSTASH_CURRENT_SIGNING_KEY:-sig_7kYjw48mhY7kAjqNGcy6cr29RJ6r}"
QSTASH_NEXT_SIGNING_KEY="${QSTASH_NEXT_SIGNING_KEY:-sig_5ZB6DVzB1wjE8S6rZ7eenA8Pdnhs}"
APP_URL="${APP_URL:-http://localhost:3000}"

cat > $ENV_FILE << EOF
# =============================================================================
# Local Development Configuration
# Generated by setup-env.sh — safe to edit
# =============================================================================

# App
APP_URL=$APP_URL
APP_NAME=AI Video Studio

# Auth
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET

# Database (local SQLite)
TURSO_DATABASE_URL=file:local.db

# QStash (local Docker emulator — run 'bun qstash:dev' in another terminal)
QSTASH_URL=$QSTASH_URL
QSTASH_TOKEN=$QSTASH_TOKEN
QSTASH_CURRENT_SIGNING_KEY=$QSTASH_CURRENT_SIGNING_KEY
QSTASH_NEXT_SIGNING_KEY=$QSTASH_NEXT_SIGNING_KEY

# Google OAuth (optional — falls back to email OTP)
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=

# AI Services (add your keys to enable generation)
# FAL_KEY=           # https://fal.ai
# OPENROUTER_KEY=    # https://openrouter.ai

# Storage (S3-compatible — add credentials to enable file uploads)
# R2_ACCOUNT_ID=
# R2_ACCESS_KEY_ID=
# R2_SECRET_ACCESS_KEY=
# R2_BUCKET_NAME=my-app-storage
# R2_PUBLIC_STORAGE_DOMAIN=storage.example.com
EOF

echo -e "${GREEN}Created $ENV_FILE${NC}"
echo ""
echo -e "${BLUE}Configuration:${NC}"
echo "  Database:  file:local.db (SQLite)"
echo "  QStash:    $QSTASH_URL (local Docker emulator)"
echo "  Auth:      BETTER_AUTH_SECRET generated"
echo "  App URL:   $APP_URL"
echo ""
echo -e "${YELLOW}Optional services (add keys to $ENV_FILE as needed):${NC}"
echo "  FAL_KEY           — Image & video generation (fal.ai)"
echo "  OPENROUTER_KEY    — LLM access for script analysis (openrouter.ai)"
echo "  GOOGLE_CLIENT_ID  — Google OAuth sign-in"
echo "  R2_*              — S3-compatible storage for media files"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "  1. bun db:setup          # Migrate & seed database"
echo "  2. bun qstash:dev        # Start workflow emulator (separate terminal)"
echo "  3. bun dev               # Start dev server"
echo ""
echo -e "${GREEN}Setup complete!${NC}"
