/**
 * Interactive setup script for OpenStory
 *
 * Usage:
 *   bun setup          — local dev (SQLite, QStash emulator, localhost defaults → .env.local)
 *   bun setup:prod     — production (hosting platform, database, email, services → .env.production)
 *   bun setup:staging  — push staging secrets to GitHub environment → .env.staging
 */

import * as p from '@clack/prompts';
import chalk from 'chalk';
import { execFileSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const MIN_BUN_VERSION = '1.3.9';

const isDeploy = process.argv.includes('--deploy');
const isStagingMode = process.argv.includes('--staging');
const isProd = isDeploy || process.argv.includes('--prod');
const ENV_FILE = resolve(
  process.cwd(),
  isStagingMode ? '.env.staging' : isProd ? '.env.production' : '.env.local'
);
const ENV_FILENAME = isStagingMode
  ? '.env.staging'
  : isProd
    ? '.env.production'
    : '.env.local';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function parseEnvString(text: string): Map<string, string> {
  const env = new Map<string, string>();
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    // Strip surrounding quotes (Upstash dashboard uses QSTASH_TOKEN="value")
    if (
      value.length >= 2 &&
      ((value[0] === '"' && value.at(-1) === '"') ||
        (value[0] === "'" && value.at(-1) === "'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key && value) env.set(key, value);
  }
  return env;
}

function parseEnvFile(path: string): Map<string, string> {
  if (!existsSync(path)) return new Map();
  return parseEnvString(readFileSync(path, 'utf-8'));
}

function loadExistingEnv(): Map<string, string> {
  const env = parseEnvFile(ENV_FILE);

  // For prod, also read legacy .env so existing keys are migrated
  if (isProd) {
    const legacyFile = resolve(process.cwd(), '.env');
    const legacy = parseEnvFile(legacyFile);
    legacy.forEach((value, key) => {
      if (!env.has(key)) env.set(key, value);
    });
  }

  return env;
}

function writeEnvFile(vars: Map<string, string>) {
  const lines: string[] = [
    '# =============================================================================',
    isProd ? '# Production Configuration' : '# Local Development Configuration',
    isProd
      ? '# Generated by `bun setup:prod` — safe to edit'
      : '# Generated by `bun setup` — safe to edit',
    '# =============================================================================',
    '',
  ];

  const sections: Array<{ header: string; keys: string[] }> = [
    {
      header: 'Core',
      keys: [
        'APP_URL',
        'APP_NAME',
        'DEPLOY_PLATFORM',
        'BETTER_AUTH_SECRET',
        'TURSO_DATABASE_URL',
        'TURSO_AUTH_TOKEN',
        'CLOUDFLARE_ACCOUNT_ID',
        'CLOUDFLARE_API_TOKEN',
      ],
    },
    {
      header: 'Email (Resend)',
      keys: ['RESEND_API_KEY', 'EMAIL_FROM'],
    },
    {
      header: 'Workflows (QStash)',
      keys: [
        'QSTASH_URL',
        'QSTASH_TOKEN',
        'QSTASH_CURRENT_SIGNING_KEY',
        'QSTASH_NEXT_SIGNING_KEY',
      ],
    },
    {
      header: 'AI Services',
      keys: [
        'FAL_KEY',
        'FAL_CONCURRENCY_LIMIT',
        'OPENROUTER_KEY',
        'CEREBRAS_API_KEY',
        'LETZAI_API_KEY',
      ],
    },
    {
      header: 'Storage (Cloudflare R2)',
      keys: [
        'R2_ACCOUNT_ID',
        'R2_ACCESS_KEY_ID',
        'R2_SECRET_ACCESS_KEY',
        'R2_BUCKET_NAME',
        'R2_PUBLIC_STORAGE_DOMAIN',
        'R2_PUBLIC_ASSETS_BUCKET',
        'R2_PUBLIC_ASSETS_DOMAIN',
      ],
    },
    {
      header: 'Google OAuth',
      keys: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    },
    {
      header: 'Observability (Langfuse)',
      keys: [
        'LANGFUSE_PUBLIC_KEY',
        'LANGFUSE_SECRET_KEY',
        'LANGFUSE_BASE_URL',
        'LANGFUSE_TRACING_ENVIRONMENT',
      ],
    },
    {
      header: 'Billing (Stripe)',
      keys: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'],
    },
    {
      header: 'Redis (Upstash)',
      keys: ['UPSTASH_REDIS_REST_URL', 'UPSTASH_REDIS_REST_TOKEN'],
    },
    {
      header: 'Security',
      keys: ['API_KEY_ENCRYPTION_KEY'],
    },
  ];

  for (const section of sections) {
    const sectionVars = section.keys.filter((k) => vars.has(k));
    if (sectionVars.length === 0) continue;

    lines.push(`# ${section.header}`);
    for (const key of sectionVars) {
      lines.push(`${key}=${vars.get(key)}`);
    }
    lines.push('');
  }

  writeFileSync(ENV_FILE, lines.join('\n'));
}

function commandExists(cmd: string): boolean {
  try {
    execFileSync('which', [cmd], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function getBunVersion(): string | null {
  try {
    return execFileSync('bun', ['--version'], { encoding: 'utf-8' }).trim();
  } catch {
    return null;
  }
}

function versionGte(version: string, minVersion: string): boolean {
  const parse = (v: string) => v.split('.').map(Number);
  const [aMajor, aMinor, aPatch] = parse(version);
  const [bMajor, bMinor, bPatch] = parse(minVersion);
  if (aMajor !== bMajor) return aMajor > bMajor;
  if (aMinor !== bMinor) return aMinor > bMinor;
  return aPatch >= bPatch;
}

function generateSecret(): string {
  try {
    return execFileSync('openssl', ['rand', '-hex', '32'], {
      encoding: 'utf-8',
    }).trim();
  } catch {
    const bytes = new Uint8Array(32);
    crypto.getRandomValues(bytes);
    return Array.from(bytes)
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
  }
}

// checkCancel and promptForKey are defined inside main() to capture `vars` for incremental saving

// ---------------------------------------------------------------------------
// Staging Setup — push secrets to GitHub environment
// ---------------------------------------------------------------------------

const STAGING_SECRETS = [
  'API_KEY_ENCRYPTION_KEY',
  'APP_NAME',
  'BETTER_AUTH_SECRET',
  'CEREBRAS_API_KEY',
  'EMAIL_FROM',
  'FAL_CONCURRENCY_LIMIT',
  'FAL_KEY',
  'GOOGLE_CLIENT_ID',
  'GOOGLE_CLIENT_SECRET',
  'LANGFUSE_BASE_URL',
  'LANGFUSE_PUBLIC_KEY',
  'LANGFUSE_SECRET_KEY',
  'LANGFUSE_TRACING_ENVIRONMENT',
  'LETZAI_API_KEY',
  'OPENROUTER_KEY',
  'QSTASH_CURRENT_SIGNING_KEY',
  'QSTASH_NEXT_SIGNING_KEY',
  'QSTASH_TOKEN',
  'QSTASH_URL',
  'RESEND_API_KEY',
  'STRIPE_SECRET_KEY',
  'STRIPE_WEBHOOK_SECRET',
  'UPSTASH_REDIS_REST_TOKEN',
  'UPSTASH_REDIS_REST_URL',
] as const;

const STAGING_VARIABLES = [
  'R2_PUBLIC_ASSETS_DOMAIN',
  'R2_PUBLIC_STORAGE_DOMAIN',
] as const;

function execGh(args: string[]): string {
  return execFileSync('gh', args, {
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'pipe'],
  }).trim();
}

async function stagingSetup() {
  p.intro(chalk.bold('OpenStory Staging Setup'));
  p.log.info(
    'Pushes secrets from .env.production to a GitHub "staging" environment.'
  );

  // 1. Check gh CLI
  if (!commandExists('gh')) {
    p.log.error(
      'GitHub CLI (gh) is not installed.\n' +
        'Install it: https://cli.github.com/'
    );
    process.exit(1);
  }

  try {
    execGh(['auth', 'status']);
  } catch {
    p.log.error('Not authenticated with gh. Run: gh auth login');
    process.exit(1);
  }
  p.log.success('GitHub CLI authenticated');

  // 2. Detect repo
  let repoName: string;
  try {
    const repoJson = execGh([
      'repo',
      'view',
      '--json',
      'nameWithOwner',
      '-q',
      '.nameWithOwner',
    ]);
    repoName = repoJson;
  } catch {
    p.log.error(
      'Could not detect GitHub repository. Are you in a git repo with a GitHub remote?'
    );
    process.exit(1);
  }
  p.log.success(`Repository: ${repoName}`);

  // 3. Load .env.production as base, layer .env.staging overrides
  const prodFile = resolve(process.cwd(), '.env.production');
  const stagingFile = resolve(process.cwd(), '.env.staging');
  const prodVars = parseEnvFile(prodFile);
  const stagingVars = parseEnvFile(stagingFile);

  if (prodVars.size === 0) {
    p.log.error(
      'No .env.production found. Run `bun setup:prod` first to configure production values.'
    );
    process.exit(1);
  }

  // Merge: staging overrides prod
  const merged = new Map(prodVars);
  for (const [k, v] of stagingVars) {
    merged.set(k, v);
  }

  // Delete APP_URL (dynamic per PR)
  merged.delete('APP_URL');

  // 4. Count ready/missing
  const allKeys = [...STAGING_SECRETS, ...STAGING_VARIABLES];
  const ready = allKeys.filter((k) => merged.get(k));
  const missing = allKeys.filter((k) => !merged.get(k));

  p.log.info(
    `${chalk.green(String(ready.length))} keys ready, ${chalk.yellow(String(missing.length))} missing`
  );

  if (missing.length > 0) {
    p.log.warn(`Missing: ${missing.join(', ')}`);
  }

  // 5. Optional override
  const wantOverride = await p.confirm({
    message: 'Override any values before pushing?',
    initialValue: missing.length > 0,
  });

  if (p.isCancel(wantOverride)) {
    p.cancel('Staging setup cancelled.');
    process.exit(0);
  }

  if (wantOverride) {
    const defaultSelected = missing;
    const toOverride = await p.multiselect<string>({
      message: 'Select keys to set/override',
      options: allKeys.map((k) => ({
        value: k,
        label: k,
        hint: merged.has(k)
          ? `current: ${merged.get(k)?.slice(0, 20)}…`
          : 'not set',
      })),
      initialValues: [...defaultSelected],
    });

    if (p.isCancel(toOverride)) {
      p.cancel('Staging setup cancelled.');
      process.exit(0);
    }

    for (const key of toOverride) {
      const value = await p.text({
        message: `${key}`,
        placeholder: merged.get(key) ?? `Paste your ${key} here…`,
        defaultValue: merged.get(key),
      });

      if (p.isCancel(value)) {
        p.cancel('Staging setup cancelled.');
        process.exit(0);
      }

      if (value && value.trim()) {
        merged.set(key, value.trim());
      }
    }
  }

  // 6. Ensure GitHub staging environment exists
  const envSpinner = p.spinner();
  envSpinner.start('Ensuring GitHub "staging" environment exists');
  try {
    execGh([
      'api',
      '--method',
      'PUT',
      `/repos/${repoName}/environments/staging`,
    ]);
    envSpinner.stop('GitHub "staging" environment ready');
  } catch (error) {
    envSpinner.stop('Failed to create staging environment');
    p.log.error(
      `Error: ${error instanceof Error ? error.message : String(error)}\n` +
        'You may need to create it manually in GitHub Settings > Environments.'
    );
    process.exit(1);
  }

  // 7. Push secrets
  const secretSpinner = p.spinner();
  const secretsToPush = STAGING_SECRETS.filter((k) => merged.get(k));
  secretSpinner.start(
    `Pushing ${secretsToPush.length} secrets to staging environment`
  );
  let secretsPushed = 0;
  let secretsFailed = 0;

  for (const key of secretsToPush) {
    const value = merged.get(key);
    if (!value) continue;
    try {
      execFileSync(
        'gh',
        ['secret', 'set', key, '--env', 'staging', '--body', value],
        {
          stdio: ['pipe', 'pipe', 'pipe'],
        }
      );
      secretsPushed++;
    } catch {
      secretsFailed++;
      p.log.warn(`Failed to push secret: ${key}`);
    }
  }

  if (secretsFailed > 0) {
    secretSpinner.stop(
      `Pushed ${secretsPushed} secrets (${secretsFailed} failed)`
    );
  } else {
    secretSpinner.stop(`Pushed ${secretsPushed} secrets`);
  }

  // 8. Push variables
  const varsToPush = STAGING_VARIABLES.filter((k) => merged.get(k));
  if (varsToPush.length > 0) {
    const varSpinner = p.spinner();
    varSpinner.start(
      `Pushing ${varsToPush.length} variables to staging environment`
    );
    let varsPushed = 0;
    let varsFailed = 0;

    for (const key of varsToPush) {
      const value = merged.get(key);
      if (!value) continue;
      try {
        execFileSync(
          'gh',
          ['variable', 'set', key, '--env', 'staging', '--body', value],
          {
            stdio: ['pipe', 'pipe', 'pipe'],
          }
        );
        varsPushed++;
      } catch {
        varsFailed++;
        p.log.warn(`Failed to push variable: ${key}`);
      }
    }

    if (varsFailed > 0) {
      varSpinner.stop(`Pushed ${varsPushed} variables (${varsFailed} failed)`);
    } else {
      varSpinner.stop(`Pushed ${varsPushed} variables`);
    }
  }

  // 9. Write .env.staging locally as record
  const lines: string[] = [
    '# =============================================================================',
    '# Staging Configuration (record of what was pushed to GitHub)',
    '# Generated by `bun setup:staging` — safe to edit',
    '# =============================================================================',
    '',
  ];

  for (const key of [...STAGING_SECRETS, ...STAGING_VARIABLES]) {
    const value = merged.get(key);
    if (value) {
      lines.push(`${key}=${value}`);
    }
  }
  lines.push('');

  writeFileSync(stagingFile, lines.join('\n'));
  p.log.success(`Wrote ${stagingFile}`);

  // 10. Summary
  p.note(
    [
      `Repository: ${repoName}`,
      `Environment: staging`,
      `Secrets pushed: ${secretsPushed}`,
      `Variables pushed: ${varsToPush.length}`,
      '',
      `Local record: .env.staging`,
    ].join('\n'),
    'Staging Setup Complete'
  );

  p.outro('Done! PR preview deploys will now use the staging environment.');
}

// ---------------------------------------------------------------------------
// Deploy Setup
// ---------------------------------------------------------------------------

const cliConfig: Record<
  string,
  {
    cmd: string;
    install: string;
    loginArgs: string[];
    whoamiArgs: string[];
  }
> = {
  cloudflare: {
    cmd: 'wrangler',
    install: 'bun add -g wrangler',
    loginArgs: ['login'],
    whoamiArgs: ['whoami'],
  },
  vercel: {
    cmd: 'vercel',
    install: 'bun add -g vercel',
    loginArgs: ['login'],
    whoamiArgs: ['whoami'],
  },
  railway: {
    cmd: 'railway',
    install: 'npm i -g @railway/cli',
    loginArgs: ['login'],
    whoamiArgs: ['whoami'],
  },
};

const platformLabels: Record<string, string> = {
  cloudflare: 'Cloudflare Workers',
  vercel: 'Vercel',
  railway: 'Railway',
};

async function deploySetup(
  vars: Map<string, string>,
  checkCancel: <T>(value: T | symbol) => T,
  _saveProgress: () => void
) {
  const platform = vars.get('DEPLOY_PLATFORM');
  if (!platform || !(platform in cliConfig)) {
    p.log.error(
      `Unknown or missing DEPLOY_PLATFORM: ${platform ?? '(not set)'}. Run ${chalk.bold('bun setup:prod')} first.`
    );
    return;
  }

  const config = cliConfig[platform];
  const label = platformLabels[platform] ?? platform;

  p.log.step(chalk.bold(`Deploy Setup — ${label}`));

  // 1. Check CLI installed
  if (!commandExists(config.cmd)) {
    const shouldInstall = checkCancel(
      await p.confirm({
        message: `${config.cmd} is not installed. Install it now?`,
        initialValue: true,
      })
    );

    if (shouldInstall) {
      const installSpinner = p.spinner();
      installSpinner.start(`Installing ${config.cmd}`);
      try {
        const [cmd, ...args] = config.install.split(' ');
        execFileSync(cmd, args, { stdio: 'pipe' });
        installSpinner.stop(`${config.cmd} installed`);
      } catch (error) {
        installSpinner.stop(`Failed to install ${config.cmd}`);
        p.log.error(
          `Install error: ${error instanceof Error ? error.message : String(error)}`
        );
        p.log.info(`Run manually: ${chalk.bold(config.install)}`);
        return;
      }
    } else {
      p.log.info(`Install manually: ${chalk.bold(config.install)}`);
      return;
    }
  } else {
    p.log.success(`${config.cmd} installed`);
  }

  // 2. Check auth
  let isAuthed = false;
  try {
    execFileSync(config.cmd, config.whoamiArgs, { stdio: 'pipe' });
    isAuthed = true;
  } catch {
    isAuthed = false;
  }

  if (!isAuthed) {
    const shouldLogin = checkCancel(
      await p.confirm({
        message: `Not logged in to ${config.cmd}. Log in now?`,
        initialValue: true,
      })
    );

    if (shouldLogin) {
      p.log.info('Opening browser for authentication…');
      try {
        execFileSync(config.cmd, config.loginArgs, { stdio: 'inherit' });
      } catch (error) {
        p.log.error(
          `Login failed: ${error instanceof Error ? error.message : String(error)}`
        );
        return;
      }

      // Re-check
      try {
        execFileSync(config.cmd, config.whoamiArgs, { stdio: 'pipe' });
        p.log.success(`Logged in to ${config.cmd}`);
      } catch {
        p.log.error(
          `Still not authenticated. Run ${chalk.bold(`${config.cmd} login`)} manually.`
        );
        return;
      }
    } else {
      p.log.info(`Run ${chalk.bold(`${config.cmd} login`)} when ready.`);
      return;
    }
  } else {
    p.log.success(`Authenticated with ${config.cmd}`);
  }

  // 3. Link project (Vercel + Railway only)
  if (platform === 'vercel' || platform === 'railway') {
    const shouldLink = checkCancel(
      await p.confirm({
        message: `Link this directory to your ${label} project?`,
        initialValue: true,
      })
    );

    if (shouldLink) {
      p.log.info(`Follow the prompts to link your ${label} project…`);
      if (platform === 'vercel') {
        p.log.info(
          chalk.dim(
            'Decline "pull environment variables" — we push them in the next step.'
          )
        );
      }
      try {
        execFileSync(config.cmd, ['link'], { stdio: 'inherit' });
        p.log.success(`Linked to ${label} project`);
      } catch (error) {
        p.log.error(
          `Link failed: ${error instanceof Error ? error.message : String(error)}`
        );
        return;
      }
    }
  }

  // 4. Push secrets
  if (platform === 'cloudflare') {
    const shouldPushSecrets = checkCancel(
      await p.confirm({
        message: 'Push secrets to Cloudflare Workers?',
        initialValue: true,
      })
    );

    if (shouldPushSecrets) {
      const secretsSpinner = p.spinner();
      secretsSpinner.start('Pushing secrets to Cloudflare');
      try {
        execFileSync('wrangler', ['secret', 'bulk', ENV_FILE], {
          stdio: 'pipe',
        });
        secretsSpinner.stop('Secrets pushed to Cloudflare');
      } catch (error) {
        secretsSpinner.stop('Failed to push secrets');
        p.log.error(
          `Error: ${error instanceof Error ? error.message : String(error)}`
        );
        p.log.info(
          `Run manually: ${chalk.bold(`wrangler secret bulk ${ENV_FILENAME}`)}`
        );
      }
    }
  } else if (platform === 'vercel') {
    const shouldPushSecrets = checkCancel(
      await p.confirm({
        message: 'Push environment variables to Vercel?',
        initialValue: true,
      })
    );

    if (shouldPushSecrets) {
      // Push production vars to production + preview
      const secretsSpinner = p.spinner();
      secretsSpinner.start(
        `Pushing ${vars.size} env vars to Vercel (production + preview)`
      );

      let pushed = 0;
      let failed = 0;

      for (const [key, value] of vars) {
        // Preview gets all vars except TURSO_DATABASE_URL (each preview branch should have its own DB)
        const envs =
          key === 'TURSO_DATABASE_URL'
            ? ['production']
            : ['production', 'preview'];

        try {
          execFileSync('vercel', ['env', 'add', key, ...envs, '--force'], {
            input: value,
            stdio: ['pipe', 'pipe', 'pipe'],
          });
          pushed++;
        } catch {
          failed++;
        }
      }

      if (failed > 0) {
        secretsSpinner.stop(
          `Pushed ${pushed} env vars to Vercel (${failed} failed)`
        );
      } else {
        secretsSpinner.stop(
          `Pushed ${vars.size} env vars to Vercel (production + preview)`
        );
      }

      // Optionally push .env.local as development environment
      const localEnvFile = resolve(process.cwd(), '.env.local');
      const localVars = parseEnvFile(localEnvFile);

      if (localVars.size > 0) {
        const shouldPushDev = checkCancel(
          await p.confirm({
            message: `Found .env.local with ${localVars.size} values. Push to Vercel development environment?`,
            initialValue: true,
          })
        );

        if (shouldPushDev) {
          const devSpinner = p.spinner();
          devSpinner.start(
            `Pushing ${localVars.size} env vars to Vercel (development)`
          );

          let devPushed = 0;
          let devFailed = 0;

          for (const [key, value] of localVars) {
            try {
              execFileSync(
                'vercel',
                ['env', 'add', key, 'development', '--force'],
                {
                  input: value,
                  stdio: ['pipe', 'pipe', 'pipe'],
                }
              );
              devPushed++;
            } catch {
              devFailed++;
            }
          }

          if (devFailed > 0) {
            devSpinner.stop(
              `Pushed ${devPushed} dev env vars to Vercel (${devFailed} failed)`
            );
          } else {
            devSpinner.stop(
              `Pushed ${localVars.size} env vars to Vercel (development)`
            );
          }
        }
      } else {
        p.log.info(
          `No .env.local found — skipping Vercel development environment. Run ${chalk.bold('bun setup')} first to create one.`
        );
      }
    }
  } else {
    // Railway — no bulk env push via CLI without specifying service
    p.log.info(
      `Copy environment variables from ${chalk.bold(ENV_FILENAME)} to your ${label} dashboard.`
    );
  }

  // 5. Deploy
  const shouldDeploy = checkCancel(
    await p.confirm({
      message: `Deploy to ${label} now?`,
      initialValue: true,
    })
  );

  if (!shouldDeploy) {
    p.log.info('Skipping deploy. You can deploy later manually.');
    return;
  }

  if (platform === 'cloudflare') {
    p.log.info(
      'D1 migrations and seeding are handled by the GitHub Actions deploy workflow.'
    );

    // Deploy
    p.log.info('Building and deploying to Cloudflare Workers…');
    try {
      execFileSync('bun', ['cf:deploy:prd'], {
        stdio: 'inherit',
        cwd: process.cwd(),
      });
      p.log.success('Deployed to Cloudflare Workers');
    } catch (error) {
      p.log.error(
        `Deploy failed: ${error instanceof Error ? error.message : String(error)}`
      );
      p.log.info(`Run manually: ${chalk.bold('bun cf:deploy:prd')}`);
    }
  } else if (platform === 'vercel') {
    p.log.info('Deploying to Vercel…');
    try {
      execFileSync('vercel', ['deploy', '--prod'], {
        stdio: 'inherit',
        cwd: process.cwd(),
      });
      p.log.success('Deployed to Vercel');
    } catch (error) {
      p.log.error(
        `Deploy failed: ${error instanceof Error ? error.message : String(error)}`
      );
      p.log.info(`Run manually: ${chalk.bold('vercel deploy --prod')}`);
    }
  } else if (platform === 'railway') {
    p.log.info('Deploying to Railway…');
    try {
      execFileSync('railway', ['up'], {
        stdio: 'inherit',
        cwd: process.cwd(),
      });
      p.log.success('Deployed to Railway');
    } catch (error) {
      p.log.error(
        `Deploy failed: ${error instanceof Error ? error.message : String(error)}`
      );
      p.log.info(`Run manually: ${chalk.bold('railway up')}`);
    }
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const existing = loadExistingEnv();
  const vars = new Map(existing);

  // Save progress incrementally so users can cancel mid-setup
  const saveProgress = () => writeEnvFile(vars);

  process.on('SIGINT', () => {
    saveProgress();
    console.log('');
    p.cancel(`Setup cancelled. Progress saved to ${ENV_FILENAME}`);
    process.exit(0);
  });

  function checkCancel<T>(value: T | symbol): T {
    if (p.isCancel(value)) {
      saveProgress();
      p.cancel(`Setup cancelled. Progress saved to ${ENV_FILENAME}`);
      process.exit(0);
    }
    return value;
  }

  // --staging: push secrets to GitHub staging environment
  if (isStagingMode) {
    await stagingSetup();
    return;
  }

  // --deploy: skip env var prompts, jump straight to deploy phase
  if (isDeploy) {
    p.intro(chalk.bold('OpenStory Deploy Setup'));

    if (existing.size === 0) {
      p.log.error(
        `No ${ENV_FILENAME} found. Run ${chalk.bold('bun setup:prod')} first to configure environment variables.`
      );
      process.exit(1);
    }

    p.log.info(`Loaded ${existing.size} values from ${ENV_FILENAME}`);

    // Prompt for platform if missing
    if (!vars.has('DEPLOY_PLATFORM')) {
      const platform = checkCancel(
        await p.select({
          message: 'Where will you deploy?',
          options: [
            {
              value: 'cloudflare',
              label: 'Cloudflare Workers',
              hint: 'recommended',
            },
            { value: 'vercel', label: 'Vercel' },
            { value: 'railway', label: 'Railway' },
          ],
        })
      );
      vars.set('DEPLOY_PLATFORM', platform);
      saveProgress();
    }

    await deploySetup(vars, checkCancel, saveProgress);
    p.outro('Deploy setup complete.');
    return;
  }

  p.intro(
    chalk.bold(
      isProd ? 'OpenStory Production Setup' : 'Welcome to OpenStory Setup'
    )
  );

  async function promptForKey(
    key: string,
    message: string,
    hint?: string
  ): Promise<void> {
    if (vars.has(key)) {
      p.log.success(`${key} — already configured`);
      return;
    }

    const raw = checkCancel(
      await p.text({
        message: hint ? `${message}\n${chalk.dim(hint)}` : message,
        placeholder: `Paste your ${key} here…`,
      })
    );

    if (!raw || !raw.trim()) return;

    // Try parsing as KEY=VALUE (stores under the parsed key, not the expected key,
    // so pasting KEY=VALUE into any prompt works correctly)
    const parsed = parseEnvString(raw);
    const envPairs = new Map<string, string>();
    for (const [k, v] of parsed) {
      if (/^[A-Z_][A-Z0-9_]*$/.test(k)) {
        envPairs.set(k, v);
      }
    }

    if (envPairs.size > 0) {
      for (const [k, v] of envPairs) {
        vars.set(k, v);
      }
      saveProgress();
      return;
    }

    // Raw value without KEY= prefix — store under expected key, strip quotes
    let value = raw.trim();
    if (
      value.length >= 2 &&
      ((value[0] === '"' && value.at(-1) === '"') ||
        (value[0] === "'" && value.at(-1) === "'"))
    ) {
      value = value.slice(1, -1);
    }

    vars.set(key, value);
    saveProgress();
  }

  // -------------------------------------------------------------------------
  // Prerequisites
  // -------------------------------------------------------------------------
  const prereqs = p.spinner();
  prereqs.start('Checking prerequisites');

  const bunVersion = getBunVersion();
  const hasDocker = isProd ? false : commandExists('docker');

  prereqs.stop('Prerequisites checked');

  if (!bunVersion) {
    p.log.error('Bun is not installed. Install it from https://bun.sh');
    process.exit(1);
  }

  if (!versionGte(bunVersion, MIN_BUN_VERSION)) {
    p.log.error(
      `Bun ${bunVersion} found, but ${MIN_BUN_VERSION}+ is required. Run: curl -fsSL https://bun.sh/install | bash`
    );
    process.exit(1);
  }
  p.log.success(`Bun ${bunVersion}`);

  if (!isProd) {
    if (hasDocker) {
      p.log.success('Docker installed');
    } else {
      p.log.warn(
        'Docker not found — QStash workflow emulator will be unavailable. Install OrbStack (https://orbstack.dev) or Docker Desktop.'
      );
    }
  }

  if (existing.size > 0) {
    p.log.info(
      `Found existing ${ENV_FILENAME} with ${existing.size} configured values`
    );
  }

  // Install dependencies (local only)
  if (!isProd) {
    const installSpinner = p.spinner();
    installSpinner.start('Installing dependencies');
    try {
      execFileSync('bun', ['install'], { stdio: 'pipe', cwd: process.cwd() });
      installSpinner.stop('Dependencies installed');
    } catch (error) {
      installSpinner.stop('Dependency installation failed');
      p.log.error(
        `Install error: ${error instanceof Error ? error.message : String(error)}`
      );
      process.exit(1);
    }
  }

  // -------------------------------------------------------------------------
  // Email (Resend)
  // -------------------------------------------------------------------------
  if (isProd) {
    p.log.step(chalk.bold('Email Setup'));
    await promptForKey(
      'RESEND_API_KEY',
      'Enter your Resend API key',
      'Required for production email delivery. Get one at: https://resend.com/api-keys'
    );
    if (!vars.has('RESEND_API_KEY')) {
      p.log.error('RESEND_API_KEY is required for production.');
      process.exit(1);
    }

    if (!vars.has('EMAIL_FROM')) {
      const emailFrom = checkCancel(
        await p.text({
          message: 'Enter sender email address',
          placeholder: 'noreply@example.com',
          validate: (v) =>
            !v ? 'Sender email is required for production' : undefined,
        })
      );
      if (emailFrom) {
        vars.set('EMAIL_FROM', emailFrom);
        saveProgress();
      }
    } else {
      p.log.success('EMAIL_FROM — already configured');
    }
  } else {
    const setupEmail = checkCancel(
      await p.confirm({
        message: 'Set up email delivery? (Resend)',
        initialValue: !existing.has('RESEND_API_KEY'),
      })
    );

    if (setupEmail) {
      await promptForKey(
        'RESEND_API_KEY',
        'Enter your Resend API key',
        'Get one at: https://resend.com/api-keys'
      );
      if (vars.has('RESEND_API_KEY') && !vars.has('EMAIL_FROM')) {
        const emailFrom = checkCancel(
          await p.text({
            message: 'Enter sender email address',
            placeholder: 'noreply@example.com',
          })
        );
        if (emailFrom) {
          vars.set('EMAIL_FROM', emailFrom);
          saveProgress();
        }
      }
    } else {
      p.log.info('Skipped — OTP codes will be logged to the console.');
    }
  }

  // -------------------------------------------------------------------------
  // Hosting Platform (prod only)
  // -------------------------------------------------------------------------
  if (isProd) {
    p.log.step(chalk.bold('Hosting Platform'));

    if (vars.has('DEPLOY_PLATFORM')) {
      p.log.success(
        `DEPLOY_PLATFORM — already configured (${vars.get('DEPLOY_PLATFORM')})`
      );
    } else {
      const platform = checkCancel(
        await p.select({
          message: 'Where will you host this app?',
          options: [
            {
              value: 'cloudflare',
              label: 'Cloudflare Workers',
              hint: 'recommended',
            },
            { value: 'vercel', label: 'Vercel' },
            { value: 'railway', label: 'Railway' },
          ],
        })
      );
      vars.set('DEPLOY_PLATFORM', platform);
      saveProgress();
    }
  }

  // -------------------------------------------------------------------------
  // Core
  // -------------------------------------------------------------------------
  p.log.step(chalk.bold('Core Setup'));

  if (isProd) {
    await promptForKey(
      'APP_URL',
      'Enter your production URL',
      'e.g. https://app.example.com'
    );

    // Branch database setup by hosting platform
    const platform = vars.get('DEPLOY_PLATFORM');

    if (platform === 'cloudflare') {
      p.log.step(chalk.bold('Cloudflare'));
      await promptForKey(
        'CLOUDFLARE_ACCOUNT_ID',
        'Enter your Cloudflare Account ID',
        'Find in Cloudflare console → Compute → Workers & Pages → Account ID (sidebar)'
      );
      await promptForKey(
        'CLOUDFLARE_API_TOKEN',
        'Enter your Cloudflare API token',
        'Create at: https://dash.cloudflare.com/profile/api-tokens (needs D1 + Workers edit permissions)'
      );
      p.log.info(
        'D1 database is configured in wrangler.jsonc — deploy handles migrations automatically.'
      );
    } else {
      // Vercel / Railway → Turso
      p.log.step(chalk.bold('Database (Turso)'));
      await promptForKey(
        'TURSO_DATABASE_URL',
        'Enter your Turso database URL',
        'e.g. libsql://your-db-name-org.turso.io'
      );
      await promptForKey(
        'TURSO_AUTH_TOKEN',
        'Enter your Turso auth token',
        'Get one at: https://turso.tech/app'
      );
    }
  } else {
    if (!vars.has('APP_URL')) vars.set('APP_URL', 'http://localhost:3000');
    if (!vars.has('TURSO_DATABASE_URL'))
      vars.set('TURSO_DATABASE_URL', 'file:local.db');
  }

  if (!vars.has('APP_NAME')) vars.set('APP_NAME', 'OpenStory');

  if (!vars.has('BETTER_AUTH_SECRET')) {
    const secret = generateSecret();
    vars.set('BETTER_AUTH_SECRET', secret);
    p.log.success('Auth secret generated');
  } else {
    p.log.success('Auth secret — already configured');
  }

  if (!vars.has('API_KEY_ENCRYPTION_KEY')) {
    try {
      const key = execFileSync('openssl', ['rand', '-base64', '32'], {
        encoding: 'utf-8',
      }).trim();
      vars.set('API_KEY_ENCRYPTION_KEY', key);
    } catch {
      const bytes = new Uint8Array(32);
      crypto.getRandomValues(bytes);
      vars.set('API_KEY_ENCRYPTION_KEY', btoa(String.fromCharCode(...bytes)));
    }
    p.log.success('Encryption key generated');
  } else {
    p.log.success('Encryption key — already configured');
  }

  if (vars.get('DEPLOY_PLATFORM') === 'cloudflare') {
    p.log.success('Database: Cloudflare D1 (via wrangler.jsonc)');
  } else if (vars.has('TURSO_DATABASE_URL')) {
    p.log.success(`Database: ${vars.get('TURSO_DATABASE_URL')}`);
  }
  p.log.success(`App URL: ${vars.get('APP_URL')}`);
  saveProgress();

  // Run DB migrations + seed (local only)
  if (!isProd) {
    const dbSpinner = p.spinner();
    dbSpinner.start('Running database migrations');
    try {
      execFileSync(
        'bun',
        ['--bun', 'drizzle-kit', 'migrate', '--config=drizzle.config.local.ts'],
        { stdio: 'pipe', cwd: process.cwd() }
      );
      dbSpinner.stop('Database migrations applied');
    } catch (error) {
      dbSpinner.stop('Database migration failed');
      p.log.error(
        `Migration error: ${error instanceof Error ? error.message : String(error)}`
      );
      process.exit(1);
    }

    const seedSpinner = p.spinner();
    seedSpinner.start('Seeding database');
    try {
      execFileSync('bun', ['--bun', 'scripts/seed.ts', '--local'], {
        stdio: 'pipe',
        cwd: process.cwd(),
      });
      seedSpinner.stop('Database seeded');
    } catch (error) {
      seedSpinner.stop('Database seed failed');
      p.log.error(
        `Seed error: ${error instanceof Error ? error.message : String(error)}`
      );
      process.exit(1);
    }
  }

  // -------------------------------------------------------------------------
  // AI Generation (FAL_KEY)
  // -------------------------------------------------------------------------
  if (vars.has('FAL_KEY')) {
    p.log.success('FAL_KEY — already configured');
  } else {
    const setupAI = checkCancel(
      await p.confirm({
        message: 'Set up AI image & video generation?',
        initialValue: true,
      })
    );

    if (setupAI) {
      await promptForKey(
        'FAL_KEY',
        'Enter your Fal.ai API key',
        'Get one at: https://fal.ai/dashboard/keys'
      );
    }
  }

  if (vars.has('FAL_KEY') && !vars.has('FAL_CONCURRENCY_LIMIT')) {
    const concLimit = checkCancel(
      await p.text({
        message: 'Fal.ai concurrency limit',
        placeholder: '10',
        defaultValue: '10',
      })
    );
    if (concLimit) {
      vars.set('FAL_CONCURRENCY_LIMIT', concLimit.trim() || '10');
      saveProgress();
    }
  } else if (vars.has('FAL_CONCURRENCY_LIMIT')) {
    p.log.success('FAL_CONCURRENCY_LIMIT — already configured');
  }

  // -------------------------------------------------------------------------
  // Script Analysis (OPENROUTER_KEY)
  // -------------------------------------------------------------------------
  if (vars.has('OPENROUTER_KEY')) {
    p.log.success('OPENROUTER_KEY — already configured');
  } else {
    const setupLLM = checkCancel(
      await p.confirm({
        message: 'Set up LLM-powered script analysis?',
        initialValue: true,
      })
    );

    if (setupLLM) {
      await promptForKey(
        'OPENROUTER_KEY',
        'Enter your OpenRouter API key',
        'Get one at: https://openrouter.ai/settings/keys'
      );
    }
  }

  // -------------------------------------------------------------------------
  // Additional AI Providers (optional)
  // -------------------------------------------------------------------------
  const hasAdditionalAI =
    vars.has('CEREBRAS_API_KEY') || vars.has('LETZAI_API_KEY');
  if (hasAdditionalAI) {
    if (vars.has('CEREBRAS_API_KEY'))
      p.log.success('CEREBRAS_API_KEY — already configured');
    if (vars.has('LETZAI_API_KEY'))
      p.log.success('LETZAI_API_KEY — already configured');
  } else {
    const setupAdditionalAI = checkCancel(
      await p.confirm({
        message: 'Set up additional AI providers? (optional)',
        initialValue: false,
      })
    );

    if (setupAdditionalAI) {
      await promptForKey(
        'CEREBRAS_API_KEY',
        'Cerebras API key (fast inference)',
        'Get one at: https://cloud.cerebras.ai'
      );
      await promptForKey(
        'LETZAI_API_KEY',
        'LetzAI API key (alternative image gen)',
        'Get one at: https://letz.ai'
      );
    }
  }

  // -------------------------------------------------------------------------
  // Workflows (QStash)
  // -------------------------------------------------------------------------
  if (isProd) {
    const qstashKeys = [
      'QSTASH_URL',
      'QSTASH_TOKEN',
      'QSTASH_CURRENT_SIGNING_KEY',
      'QSTASH_NEXT_SIGNING_KEY',
    ] as const;

    if (qstashKeys.every((k) => vars.has(k))) {
      p.log.success('QStash — already configured');
    } else {
      const setupWorkflows = checkCancel(
        await p.confirm({
          message: 'Set up async workflows? (Upstash QStash)',
          initialValue: true,
        })
      );

      if (setupWorkflows) {
        // Write placeholder keys so the user can paste values directly into the file
        for (const k of qstashKeys) {
          if (!vars.has(k)) vars.set(k, '');
        }
        saveProgress();

        p.log.info(
          `Paste your QStash credentials from the Upstash dashboard\n` +
            `into ${chalk.bold(ENV_FILENAME)}, then press Enter to continue.\n` +
            chalk.dim('https://console.upstash.com/qstash')
        );

        checkCancel(
          await p.text({
            message: `Press Enter after editing ${ENV_FILENAME}`,
            placeholder: 'Enter to continue…',
          })
        );

        // Re-read the file to pick up pasted values
        const refreshed = parseEnvFile(ENV_FILE);
        for (const k of qstashKeys) {
          const v = refreshed.get(k);
          if (v) vars.set(k, v);
        }
        saveProgress();

        const filled = qstashKeys.filter((k) => vars.get(k));
        const missing = qstashKeys.filter((k) => !vars.get(k));
        for (const k of filled) {
          p.log.success(`${k} — configured`);
        }
        if (missing.length > 0) {
          p.log.warn(
            `Missing: ${missing.join(', ')}. Add them to ${ENV_FILENAME} before deploying.`
          );
        }
      }
    }
  } else if (hasDocker) {
    const setupWorkflows = checkCancel(
      await p.confirm({
        message: 'Set up async workflows? (requires Docker)',
        initialValue: !existing.has('QSTASH_TOKEN'),
      })
    );

    if (setupWorkflows) {
      if (existing.has('QSTASH_TOKEN')) {
        p.log.success('QStash — already configured');
      } else {
        vars.set('QSTASH_URL', 'http://127.0.0.1:8080');
        vars.set(
          'QSTASH_TOKEN',
          'eyJVc2VySUQiOiJkZWZhdWx0VXNlciIsIlBhc3N3b3JkIjoiZGVmYXVsdFBhc3N3b3JkIn0='
        );
        vars.set(
          'QSTASH_CURRENT_SIGNING_KEY',
          'sig_7kYjw48mhY7kAjqNGcy6cr29RJ6r'
        );
        vars.set('QSTASH_NEXT_SIGNING_KEY', 'sig_5ZB6DVzB1wjE8S6rZ7eenA8Pdnhs');
        saveProgress();
        p.log.success('QStash configured for local Docker emulator');
      }

      p.note(
        'Run `bun qstash:dev` in a separate terminal to start the emulator.',
        'QStash Emulator'
      );
    }
  }

  // -------------------------------------------------------------------------
  // Redis (Upstash) — real-time progress updates
  // -------------------------------------------------------------------------
  const redisKeys = [
    'UPSTASH_REDIS_REST_URL',
    'UPSTASH_REDIS_REST_TOKEN',
  ] as const;
  if (redisKeys.every((k) => vars.has(k))) {
    p.log.success('Upstash Redis — already configured');
  } else {
    const setupRedis = checkCancel(
      await p.confirm({
        message: 'Set up Upstash Redis? (real-time progress updates)',
        initialValue: false,
      })
    );

    if (setupRedis) {
      await promptForKey(
        'UPSTASH_REDIS_REST_URL',
        'Upstash Redis REST URL',
        'Get one at: https://console.upstash.com/redis'
      );
      await promptForKey(
        'UPSTASH_REDIS_REST_TOKEN',
        'Upstash Redis REST Token'
      );
    }
  }

  // -------------------------------------------------------------------------
  // Storage (R2)
  // -------------------------------------------------------------------------
  if (vars.get('DEPLOY_PLATFORM') === 'cloudflare') {
    p.log.info(
      'R2 storage is handled by native bindings configured in wrangler.jsonc.\n' +
        'S3 credentials (for signed URLs) can be added to .env and deployed\n' +
        'via `bun setup-cloudflare-secrets.sh`.'
    );

    if (
      !vars.has('R2_PUBLIC_STORAGE_DOMAIN') ||
      !vars.has('R2_PUBLIC_ASSETS_DOMAIN')
    ) {
      // Derive R2 domains from APP_URL base domain
      const appUrl = vars.get('APP_URL') ?? '';
      let baseDomain = '';
      try {
        const host = new URL(appUrl).hostname; // e.g. app.openstory.so
        const parts = host.split('.');
        baseDomain = parts.length >= 2 ? parts.slice(-2).join('.') : host;
      } catch {
        // APP_URL not set or invalid — fall through to manual prompt
      }

      const isStaging = checkCancel(
        await p.select({
          message: 'Which R2 environment is this?',
          options: [
            { value: 'production', label: 'Production' },
            {
              value: 'staging',
              label: 'Staging / Preview',
              hint: 'uses -stg/-dev subdomains',
            },
          ],
        })
      );

      const storageSub = isStaging === 'staging' ? 'storage-dev' : 'storage';
      const assetsSub = isStaging === 'staging' ? 'assets-stg' : 'assets';

      if (baseDomain) {
        const storageDomain = `${storageSub}.${baseDomain}`;
        const assetsDomain = `${assetsSub}.${baseDomain}`;

        p.log.info(
          `Derived from ${chalk.bold(baseDomain)}:\n` +
            `  R2_PUBLIC_STORAGE_DOMAIN = ${storageDomain}\n` +
            `  R2_PUBLIC_ASSETS_DOMAIN  = ${assetsDomain}`
        );

        const useDefaults = checkCancel(
          await p.confirm({
            message: 'Use these derived domains?',
            initialValue: true,
          })
        );

        if (useDefaults) {
          vars.set('R2_PUBLIC_STORAGE_DOMAIN', storageDomain);
          vars.set('R2_PUBLIC_ASSETS_DOMAIN', assetsDomain);
          saveProgress();
        } else {
          await promptForKey(
            'R2_PUBLIC_STORAGE_DOMAIN',
            `R2 Public Storage Domain (e.g. ${storageSub}.example.com)`
          );
          await promptForKey(
            'R2_PUBLIC_ASSETS_DOMAIN',
            `R2 Public Assets Domain (e.g. ${assetsSub}.example.com)`
          );
        }
      } else {
        await promptForKey(
          'R2_PUBLIC_STORAGE_DOMAIN',
          `R2 Public Storage Domain (e.g. ${storageSub}.example.com)`
        );
        await promptForKey(
          'R2_PUBLIC_ASSETS_DOMAIN',
          `R2 Public Assets Domain (e.g. ${assetsSub}.example.com)`
        );
      }
    } else {
      p.log.success(
        `R2_PUBLIC_STORAGE_DOMAIN = ${vars.get('R2_PUBLIC_STORAGE_DOMAIN')}`
      );
      p.log.success(
        `R2_PUBLIC_ASSETS_DOMAIN  = ${vars.get('R2_PUBLIC_ASSETS_DOMAIN')}`
      );
    }
  } else {
    const setupStorage = checkCancel(
      await p.confirm({
        message: 'Set up cloud storage for media? (Cloudflare R2)',
        initialValue: false,
      })
    );

    if (setupStorage) {
      const r2Keys: Array<{
        key: string;
        message: string;
        hint?: string;
      }> = [
        {
          key: 'R2_ACCOUNT_ID',
          message: 'Cloudflare Account ID',
          hint: 'Find in Cloudflare Dashboard > R2 > Overview',
        },
        {
          key: 'R2_ACCESS_KEY_ID',
          message: 'R2 Access Key ID',
        },
        {
          key: 'R2_SECRET_ACCESS_KEY',
          message: 'R2 Secret Access Key',
        },
        { key: 'R2_BUCKET_NAME', message: 'R2 Bucket Name' },
        {
          key: 'R2_PUBLIC_STORAGE_DOMAIN',
          message: 'R2 Public Domain (e.g. storage.example.com)',
        },
      ];

      for (const { key, message, hint } of r2Keys) {
        await promptForKey(key, message, hint);
      }
    }
  }

  // -------------------------------------------------------------------------
  // Google OAuth
  // -------------------------------------------------------------------------
  const googleKeys = ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'] as const;
  const hasGoogle = googleKeys.some((k) => vars.has(k));

  if (hasGoogle) {
    for (const k of googleKeys) {
      if (vars.has(k)) p.log.success(`${k} — already configured`);
    }
  }

  const setupGoogle =
    hasGoogle ||
    checkCancel(
      await p.confirm({
        message: 'Set up Google sign-in? (or use email OTP)',
        initialValue: false,
      })
    );

  if (setupGoogle) {
    await promptForKey(
      'GOOGLE_CLIENT_ID',
      'Google OAuth Client ID',
      'Get one at: https://console.cloud.google.com/apis/credentials'
    );
    await promptForKey('GOOGLE_CLIENT_SECRET', 'Google OAuth Client Secret');
  }

  // -------------------------------------------------------------------------
  // Observability (Langfuse)
  // -------------------------------------------------------------------------
  const langfuseKeys = [
    'LANGFUSE_PUBLIC_KEY',
    'LANGFUSE_SECRET_KEY',
    'LANGFUSE_BASE_URL',
  ] as const;
  const hasLangfuse = langfuseKeys.some((k) => vars.has(k));

  if (hasLangfuse) {
    for (const k of langfuseKeys) {
      if (vars.has(k)) p.log.success(`${k} — already configured`);
    }
  }

  const setupLangfuse =
    hasLangfuse ||
    checkCancel(
      await p.confirm({
        message:
          'Set up Langfuse for prompt management & LLM tracing? (optional)',
        initialValue: false,
      })
    );

  if (setupLangfuse) {
    await promptForKey(
      'LANGFUSE_PUBLIC_KEY',
      'Langfuse Public Key',
      'Get one at: https://cloud.langfuse.com/project/settings'
    );
    await promptForKey('LANGFUSE_SECRET_KEY', 'Langfuse Secret Key');
    await promptForKey(
      'LANGFUSE_BASE_URL',
      'Langfuse Base URL (leave empty for cloud)',
      'Default: https://cloud.langfuse.com'
    );

    if (!vars.has('LANGFUSE_TRACING_ENVIRONMENT')) {
      const defaultEnv = isProd ? 'production' : 'development';
      const tracingEnv = checkCancel(
        await p.text({
          message: 'Langfuse tracing environment',
          placeholder: defaultEnv,
          defaultValue: defaultEnv,
        })
      );
      if (tracingEnv) {
        vars.set(
          'LANGFUSE_TRACING_ENVIRONMENT',
          tracingEnv.trim() || defaultEnv
        );
        saveProgress();
      }
    } else {
      p.log.success('LANGFUSE_TRACING_ENVIRONMENT — already configured');
    }
  }

  // -------------------------------------------------------------------------
  // Billing (Stripe)
  // -------------------------------------------------------------------------
  const stripeKeys = ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'] as const;
  const hasStripe = stripeKeys.some((k) => vars.has(k));

  if (hasStripe) {
    for (const k of stripeKeys) {
      if (vars.has(k)) p.log.success(`${k} — already configured`);
    }
  }

  const setupBilling =
    hasStripe ||
    checkCancel(
      await p.confirm({
        message: 'Set up Stripe billing?',
        initialValue: false,
      })
    );

  if (setupBilling) {
    if (isProd) {
      await promptForKey(
        'STRIPE_SECRET_KEY',
        'Stripe Secret Key (sk_live_...)',
        'Get one at: https://dashboard.stripe.com/apikeys'
      );
      await promptForKey(
        'STRIPE_WEBHOOK_SECRET',
        'Stripe Webhook Secret (whsec_...)',
        'From your webhook endpoint in the Stripe dashboard'
      );

      const appUrl = vars.get('APP_URL') ?? '<your-app-url>';
      p.note(
        [
          `Endpoint URL: ${appUrl}/api/billing/webhook`,
          '',
          'Events to enable:',
          '  - checkout.session.completed',
          '  - payment_intent.succeeded',
          '',
          'If using a restricted key, required permissions:',
          '  Charges (Read), Customers (Write),',
          '  Payment Intents (Read), Checkout Sessions (Write)',
        ].join('\n'),
        'Production Webhook Setup'
      );
    } else {
      await promptForKey(
        'STRIPE_SECRET_KEY',
        'Stripe Secret Key (sk_test_...)',
        'Get one at: https://dashboard.stripe.com/test/apikeys'
      );
      await promptForKey(
        'STRIPE_WEBHOOK_SECRET',
        'Stripe Webhook Secret (whsec_...)',
        'Run `stripe listen` to get this'
      );

      p.note(
        'Run `bun stripe:dev` in a separate terminal for webhook forwarding.',
        'Stripe Webhooks'
      );
    }
  }

  // -------------------------------------------------------------------------
  // Write env file
  // -------------------------------------------------------------------------
  writeEnvFile(vars);
  p.log.success(`Wrote ${ENV_FILE}`);

  // -------------------------------------------------------------------------
  // Summary
  // -------------------------------------------------------------------------
  const features = [
    [
      'Hosting',
      isProd
        ? (platformLabels[vars.get('DEPLOY_PLATFORM') ?? ''] ?? 'Unknown')
        : 'Local',
    ],
    [
      'Database',
      isProd
        ? vars.get('DEPLOY_PLATFORM') === 'cloudflare'
          ? 'Cloudflare D1'
          : vars.has('TURSO_DATABASE_URL')
            ? 'Turso'
            : 'Skipped'
        : 'SQLite (local.db)',
    ],
    ['Auth', 'Better Auth (secret generated)'],
    ['Email', vars.has('RESEND_API_KEY') ? 'Configured' : 'Skipped'],
    ['AI Generation', vars.has('FAL_KEY') ? 'Configured' : 'Skipped'],
    ['Script Analysis', vars.has('OPENROUTER_KEY') ? 'Configured' : 'Skipped'],
    ['Workflows', vars.has('QSTASH_TOKEN') ? 'Configured' : 'Skipped'],
    ['Storage', vars.has('R2_ACCOUNT_ID') ? 'Configured' : 'Skipped'],
    ['Google OAuth', vars.has('GOOGLE_CLIENT_ID') ? 'Configured' : 'Skipped'],
    [
      'Langfuse',
      vars.has('LANGFUSE_PUBLIC_KEY')
        ? 'Configured'
        : 'Skipped (using local prompts)',
    ],
    ['Billing', vars.has('STRIPE_SECRET_KEY') ? 'Configured' : 'Skipped'],
  ];

  const summaryLines = features
    .map(
      ([name, status]) =>
        `${status.includes('Skip') || status.includes('Disabled') ? '○' : '●'} ${name}: ${status}`
    )
    .join('\n');

  p.note(summaryLines, 'Configuration Summary');

  if (isProd) {
    await deploySetup(vars, checkCancel, saveProgress);
    p.outro(`Production config written to ${chalk.bold(ENV_FILENAME)}`);
  } else {
    p.outro(
      `Run ${chalk.bold('bun dev')} to start the development server.\nTo set up production deployment, run: ${chalk.bold('bun setup:prod')}`
    );
  }
}

main().catch((error) => {
  p.log.error(
    `Setup failed: ${error instanceof Error ? error.message : String(error)}`
  );
  process.exit(1);
});
