/**
 * Interactive setup script for Velro
 * Walks through each feature, checks prerequisites, and writes .env.local
 *
 * Usage: npx tsx scripts/setup.ts (or bun setup)
 */

import * as p from '@clack/prompts';
import chalk from 'chalk';
import { execFileSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const MIN_BUN_VERSION = '1.3.9';

const ENV_FILE = resolve(process.cwd(), '.env.local');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function loadExistingEnv(): Map<string, string> {
  const env = new Map<string, string>();
  if (!existsSync(ENV_FILE)) return env;

  for (const line of readFileSync(ENV_FILE, 'utf-8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    if (key && value) env.set(key, value);
  }
  return env;
}

function writeEnvFile(vars: Map<string, string>) {
  const lines: string[] = [
    '# =============================================================================',
    '# Local Development Configuration',
    '# Generated by `bun setup` — safe to edit',
    '# =============================================================================',
    '',
  ];

  const sections: Array<{ header: string; keys: string[] }> = [
    {
      header: 'Core',
      keys: ['APP_URL', 'APP_NAME', 'BETTER_AUTH_SECRET', 'TURSO_DATABASE_URL'],
    },
    {
      header: 'Workflows (QStash)',
      keys: [
        'QSTASH_URL',
        'QSTASH_TOKEN',
        'QSTASH_CURRENT_SIGNING_KEY',
        'QSTASH_NEXT_SIGNING_KEY',
      ],
    },
    {
      header: 'AI Services',
      keys: ['FAL_KEY', 'OPENROUTER_KEY'],
    },
    {
      header: 'Storage (Cloudflare R2)',
      keys: [
        'R2_ACCOUNT_ID',
        'R2_ACCESS_KEY_ID',
        'R2_SECRET_ACCESS_KEY',
        'R2_BUCKET_NAME',
        'R2_PUBLIC_STORAGE_DOMAIN',
      ],
    },
    {
      header: 'Google OAuth',
      keys: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    },
    {
      header: 'Billing (Stripe)',
      keys: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'],
    },
  ];

  for (const section of sections) {
    const sectionVars = section.keys.filter((k) => vars.has(k));
    if (sectionVars.length === 0) continue;

    lines.push(`# ${section.header}`);
    for (const key of sectionVars) {
      lines.push(`${key}=${vars.get(key)}`);
    }
    lines.push('');
  }

  writeFileSync(ENV_FILE, lines.join('\n'));
}

function commandExists(cmd: string): boolean {
  try {
    execFileSync('which', [cmd], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function getBunVersion(): string | null {
  try {
    return execFileSync('bun', ['--version'], { encoding: 'utf-8' }).trim();
  } catch {
    return null;
  }
}

function versionGte(version: string, minVersion: string): boolean {
  const parse = (v: string) => v.split('.').map(Number);
  const [aMajor, aMinor, aPatch] = parse(version);
  const [bMajor, bMinor, bPatch] = parse(minVersion);
  if (aMajor !== bMajor) return aMajor > bMajor;
  if (aMinor !== bMinor) return aMinor > bMinor;
  return aPatch >= bPatch;
}

function generateSecret(): string {
  try {
    return execFileSync('openssl', ['rand', '-hex', '32'], {
      encoding: 'utf-8',
    }).trim();
  } catch {
    const bytes = new Uint8Array(32);
    crypto.getRandomValues(bytes);
    return Array.from(bytes)
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
  }
}

function checkCancel<T>(value: T | symbol): T {
  if (p.isCancel(value)) {
    p.cancel('Setup cancelled.');
    process.exit(0);
  }
  return value;
}

async function promptForKey(
  existing: Map<string, string>,
  key: string,
  message: string,
  hint?: string
): Promise<string | undefined> {
  if (existing.has(key)) {
    p.log.success(`${key} — already configured`);
    return undefined;
  }

  const value = checkCancel(
    await p.text({
      message: hint ? `${message}\n${chalk.dim(hint)}` : message,
      placeholder: `Paste your ${key} here…`,
    })
  );

  return value || undefined;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  p.intro(chalk.bold('Welcome to Velro Setup'));

  const existing = loadExistingEnv();
  const vars = new Map(existing);

  // -------------------------------------------------------------------------
  // Prerequisites
  // -------------------------------------------------------------------------
  const prereqs = p.spinner();
  prereqs.start('Checking prerequisites');

  const bunVersion = getBunVersion();
  const hasDocker = commandExists('docker');

  prereqs.stop('Prerequisites checked');

  if (!bunVersion) {
    p.log.error('Bun is not installed. Install it from https://bun.sh');
    process.exit(1);
  }

  if (!versionGte(bunVersion, MIN_BUN_VERSION)) {
    p.log.error(
      `Bun ${bunVersion} found, but ${MIN_BUN_VERSION}+ is required. Run: curl -fsSL https://bun.sh/install | bash`
    );
    process.exit(1);
  }
  p.log.success(`Bun ${bunVersion}`);

  if (hasDocker) {
    p.log.success('Docker installed');
  } else {
    p.log.warn(
      'Docker not found — QStash workflow emulator will be unavailable. Install OrbStack (https://orbstack.dev) or Docker Desktop.'
    );
  }

  if (existing.size > 0) {
    p.log.info(
      `Found existing .env.local with ${existing.size} configured values`
    );
  }

  // Install dependencies
  const installSpinner = p.spinner();
  installSpinner.start('Installing dependencies');
  try {
    execFileSync('bun', ['install'], { stdio: 'pipe', cwd: process.cwd() });
    installSpinner.stop('Dependencies installed');
  } catch (error) {
    installSpinner.stop('Dependency installation failed');
    p.log.error(
      `Install error: ${error instanceof Error ? error.message : String(error)}`
    );
    process.exit(1);
  }

  // -------------------------------------------------------------------------
  // Core (auto-configured, no prompts)
  // -------------------------------------------------------------------------
  p.log.step(chalk.bold('Core Setup'));

  if (!vars.has('APP_URL')) vars.set('APP_URL', 'http://localhost:3000');
  if (!vars.has('APP_NAME')) vars.set('APP_NAME', 'Velro');
  if (!vars.has('TURSO_DATABASE_URL'))
    vars.set('TURSO_DATABASE_URL', 'file:local.db');

  if (!vars.has('BETTER_AUTH_SECRET')) {
    const secret = generateSecret();
    vars.set('BETTER_AUTH_SECRET', secret);
    p.log.success('Auth secret generated');
  } else {
    p.log.success('Auth secret — already configured');
  }

  p.log.success(`Database: ${vars.get('TURSO_DATABASE_URL')}`);
  p.log.success(`App URL: ${vars.get('APP_URL')}`);

  // Run DB migrations + seed
  const dbSpinner = p.spinner();
  dbSpinner.start('Running database migrations');
  try {
    execFileSync(
      'bun',
      ['--bun', 'drizzle-kit', 'migrate', '--config=drizzle.config.local.ts'],
      { stdio: 'pipe', cwd: process.cwd() }
    );
    dbSpinner.stop('Database migrations applied');
  } catch (error) {
    dbSpinner.stop('Database migration failed');
    p.log.error(
      `Migration error: ${error instanceof Error ? error.message : String(error)}`
    );
    process.exit(1);
  }

  const seedSpinner = p.spinner();
  seedSpinner.start('Seeding database');
  try {
    execFileSync('bun', ['--bun', 'scripts/seed.ts', '--local'], {
      stdio: 'pipe',
      cwd: process.cwd(),
    });
    seedSpinner.stop('Database seeded');
  } catch (error) {
    seedSpinner.stop('Database seed failed');
    p.log.error(
      `Seed error: ${error instanceof Error ? error.message : String(error)}`
    );
    process.exit(1);
  }

  // -------------------------------------------------------------------------
  // AI Generation (FAL_KEY)
  // -------------------------------------------------------------------------
  const setupAI = checkCancel(
    await p.confirm({
      message: 'Set up AI image & video generation?',
      initialValue: !existing.has('FAL_KEY'),
    })
  );

  if (setupAI) {
    const val = await promptForKey(
      existing,
      'FAL_KEY',
      'Enter your Fal.ai API key',
      'Get one at: https://fal.ai/dashboard/keys'
    );
    if (val) vars.set('FAL_KEY', val);
  }

  // -------------------------------------------------------------------------
  // Script Analysis (OPENROUTER_KEY)
  // -------------------------------------------------------------------------
  const setupLLM = checkCancel(
    await p.confirm({
      message: 'Set up LLM-powered script analysis?',
      initialValue: !existing.has('OPENROUTER_KEY'),
    })
  );

  if (setupLLM) {
    const val = await promptForKey(
      existing,
      'OPENROUTER_KEY',
      'Enter your OpenRouter API key',
      'Get one at: https://openrouter.ai/settings/keys'
    );
    if (val) vars.set('OPENROUTER_KEY', val);
  }

  // -------------------------------------------------------------------------
  // Workflows (QStash)
  // -------------------------------------------------------------------------
  if (hasDocker) {
    const setupWorkflows = checkCancel(
      await p.confirm({
        message: 'Set up async workflows? (requires Docker)',
        initialValue: !existing.has('QSTASH_TOKEN'),
      })
    );

    if (setupWorkflows) {
      if (existing.has('QSTASH_TOKEN')) {
        p.log.success('QStash — already configured');
      } else {
        vars.set('QSTASH_URL', 'http://127.0.0.1:8080');
        vars.set(
          'QSTASH_TOKEN',
          'eyJVc2VySUQiOiJkZWZhdWx0VXNlciIsIlBhc3N3b3JkIjoiZGVmYXVsdFBhc3N3b3JkIn0='
        );
        vars.set(
          'QSTASH_CURRENT_SIGNING_KEY',
          'sig_7kYjw48mhY7kAjqNGcy6cr29RJ6r'
        );
        vars.set('QSTASH_NEXT_SIGNING_KEY', 'sig_5ZB6DVzB1wjE8S6rZ7eenA8Pdnhs');
        p.log.success('QStash configured for local Docker emulator');
      }

      p.note(
        'Run `bun qstash:dev` in a separate terminal to start the emulator.',
        'QStash Emulator'
      );
    }
  }

  // -------------------------------------------------------------------------
  // Storage (R2)
  // -------------------------------------------------------------------------
  const setupStorage = checkCancel(
    await p.confirm({
      message: 'Set up cloud storage for media? (Cloudflare R2)',
      initialValue: false,
    })
  );

  if (setupStorage) {
    const r2Keys: Array<{ key: string; message: string }> = [
      { key: 'R2_ACCOUNT_ID', message: 'Cloudflare Account ID' },
      { key: 'R2_ACCESS_KEY_ID', message: 'R2 Access Key ID' },
      { key: 'R2_SECRET_ACCESS_KEY', message: 'R2 Secret Access Key' },
      { key: 'R2_BUCKET_NAME', message: 'R2 Bucket Name' },
      {
        key: 'R2_PUBLIC_STORAGE_DOMAIN',
        message: 'R2 Public Domain (e.g. storage.example.com)',
      },
    ];

    for (const { key, message } of r2Keys) {
      const val = await promptForKey(
        existing,
        key,
        message,
        key === 'R2_ACCOUNT_ID'
          ? 'Find in Cloudflare Dashboard > R2 > Overview'
          : undefined
      );
      if (val) vars.set(key, val);
    }
  }

  // -------------------------------------------------------------------------
  // Google OAuth
  // -------------------------------------------------------------------------
  const setupGoogle = checkCancel(
    await p.confirm({
      message: 'Set up Google sign-in? (or use email OTP)',
      initialValue: false,
    })
  );

  if (setupGoogle) {
    const clientId = await promptForKey(
      existing,
      'GOOGLE_CLIENT_ID',
      'Google OAuth Client ID',
      'Get one at: https://console.cloud.google.com/apis/credentials'
    );
    if (clientId) vars.set('GOOGLE_CLIENT_ID', clientId);

    const clientSecret = await promptForKey(
      existing,
      'GOOGLE_CLIENT_SECRET',
      'Google OAuth Client Secret'
    );
    if (clientSecret) vars.set('GOOGLE_CLIENT_SECRET', clientSecret);
  }

  // -------------------------------------------------------------------------
  // Billing (Stripe)
  // -------------------------------------------------------------------------
  const setupBilling = checkCancel(
    await p.confirm({
      message: 'Set up Stripe billing?',
      initialValue: false,
    })
  );

  if (setupBilling) {
    const secretKey = await promptForKey(
      existing,
      'STRIPE_SECRET_KEY',
      'Stripe Secret Key (sk_test_...)',
      'Get one at: https://dashboard.stripe.com/test/apikeys'
    );
    if (secretKey) vars.set('STRIPE_SECRET_KEY', secretKey);

    const webhookSecret = await promptForKey(
      existing,
      'STRIPE_WEBHOOK_SECRET',
      'Stripe Webhook Secret (whsec_...)',
      'Run `stripe listen` to get this'
    );
    if (webhookSecret) vars.set('STRIPE_WEBHOOK_SECRET', webhookSecret);

    p.note(
      'Run `bun stripe:dev` in a separate terminal for webhook forwarding.',
      'Stripe Webhooks'
    );
  }

  // -------------------------------------------------------------------------
  // Write .env.local
  // -------------------------------------------------------------------------
  writeEnvFile(vars);
  p.log.success(`Wrote ${ENV_FILE}`);

  // -------------------------------------------------------------------------
  // Summary
  // -------------------------------------------------------------------------
  const features = [
    ['Database', 'SQLite (local.db)'],
    ['Auth', 'Better Auth (secret generated)'],
    ['AI Generation', vars.has('FAL_KEY') ? 'Configured' : 'Skipped'],
    ['Script Analysis', vars.has('OPENROUTER_KEY') ? 'Configured' : 'Skipped'],
    ['Workflows', vars.has('QSTASH_TOKEN') ? 'Configured' : 'Skipped'],
    ['Storage', vars.has('R2_ACCOUNT_ID') ? 'Configured' : 'Skipped'],
    ['Google OAuth', vars.has('GOOGLE_CLIENT_ID') ? 'Configured' : 'Skipped'],
    ['Billing', vars.has('STRIPE_SECRET_KEY') ? 'Configured' : 'Skipped'],
  ];

  const summaryLines = features
    .map(
      ([name, status]) =>
        `${status.includes('Skip') || status.includes('Disabled') ? '○' : '●'} ${name}: ${status}`
    )
    .join('\n');

  p.note(summaryLines, 'Configuration Summary');

  p.outro(`Run ${chalk.bold('bun dev')} to start the development server.`);
}

main().catch((error) => {
  p.log.error(
    `Setup failed: ${error instanceof Error ? error.message : String(error)}`
  );
  process.exit(1);
});
