/**
 * Interactive setup script for Velro
 *
 * Usage:
 *   bun setup          — local dev (SQLite, QStash emulator, localhost defaults → .env.local)
 *   bun setup:prod     — production (hosting platform, database, email, services → .env.production)
 */

import * as p from '@clack/prompts';
import chalk from 'chalk';
import { execFileSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const MIN_BUN_VERSION = '1.3.9';

const isProd = process.argv.includes('--prod');
const ENV_FILE = resolve(
  process.cwd(),
  isProd ? '.env.production' : '.env.local'
);
const ENV_FILENAME = isProd ? '.env.production' : '.env.local';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function loadExistingEnv(): Map<string, string> {
  const env = new Map<string, string>();
  if (!existsSync(ENV_FILE)) return env;

  for (const line of readFileSync(ENV_FILE, 'utf-8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    if (key && value) env.set(key, value);
  }
  return env;
}

function writeEnvFile(vars: Map<string, string>) {
  const lines: string[] = [
    '# =============================================================================',
    isProd ? '# Production Configuration' : '# Local Development Configuration',
    isProd
      ? '# Generated by `bun setup:prod` — safe to edit'
      : '# Generated by `bun setup` — safe to edit',
    '# =============================================================================',
    '',
  ];

  const sections: Array<{ header: string; keys: string[] }> = [
    {
      header: 'Core',
      keys: [
        'APP_URL',
        'APP_NAME',
        'DEPLOY_PLATFORM',
        'BETTER_AUTH_SECRET',
        'TURSO_DATABASE_URL',
        'TURSO_AUTH_TOKEN',
        'CLOUDFLARE_ACCOUNT_ID',
        'CLOUDFLARE_D1_DATABASE_ID',
        'CLOUDFLARE_API_TOKEN',
      ],
    },
    {
      header: 'Email (Resend)',
      keys: ['RESEND_API_KEY', 'EMAIL_FROM'],
    },
    {
      header: 'Workflows (QStash)',
      keys: [
        'QSTASH_URL',
        'QSTASH_TOKEN',
        'QSTASH_CURRENT_SIGNING_KEY',
        'QSTASH_NEXT_SIGNING_KEY',
      ],
    },
    {
      header: 'AI Services',
      keys: ['FAL_KEY', 'OPENROUTER_KEY'],
    },
    {
      header: 'Storage (Cloudflare R2)',
      keys: [
        'R2_ACCOUNT_ID',
        'R2_ACCESS_KEY_ID',
        'R2_SECRET_ACCESS_KEY',
        'R2_BUCKET_NAME',
        'R2_PUBLIC_STORAGE_DOMAIN',
      ],
    },
    {
      header: 'Google OAuth',
      keys: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    },
    {
      header: 'Observability (Langfuse)',
      keys: ['LANGFUSE_PUBLIC_KEY', 'LANGFUSE_SECRET_KEY', 'LANGFUSE_BASE_URL'],
    },
    {
      header: 'Billing (Stripe)',
      keys: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'],
    },
  ];

  for (const section of sections) {
    const sectionVars = section.keys.filter((k) => vars.has(k));
    if (sectionVars.length === 0) continue;

    lines.push(`# ${section.header}`);
    for (const key of sectionVars) {
      lines.push(`${key}=${vars.get(key)}`);
    }
    lines.push('');
  }

  writeFileSync(ENV_FILE, lines.join('\n'));
}

function commandExists(cmd: string): boolean {
  try {
    execFileSync('which', [cmd], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function getBunVersion(): string | null {
  try {
    return execFileSync('bun', ['--version'], { encoding: 'utf-8' }).trim();
  } catch {
    return null;
  }
}

function versionGte(version: string, minVersion: string): boolean {
  const parse = (v: string) => v.split('.').map(Number);
  const [aMajor, aMinor, aPatch] = parse(version);
  const [bMajor, bMinor, bPatch] = parse(minVersion);
  if (aMajor !== bMajor) return aMajor > bMajor;
  if (aMinor !== bMinor) return aMinor > bMinor;
  return aPatch >= bPatch;
}

function generateSecret(): string {
  try {
    return execFileSync('openssl', ['rand', '-hex', '32'], {
      encoding: 'utf-8',
    }).trim();
  } catch {
    const bytes = new Uint8Array(32);
    crypto.getRandomValues(bytes);
    return Array.from(bytes)
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
  }
}

// checkCancel and promptForKey are defined inside main() to capture `vars` for incremental saving

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  p.intro(
    chalk.bold(isProd ? 'Velro Production Setup' : 'Welcome to Velro Setup')
  );

  const existing = loadExistingEnv();
  const vars = new Map(existing);

  // Save progress incrementally so users can cancel mid-setup
  const saveProgress = () => writeEnvFile(vars);

  process.on('SIGINT', () => {
    saveProgress();
    console.log('');
    p.cancel(`Setup cancelled. Progress saved to ${ENV_FILENAME}`);
    process.exit(0);
  });

  function checkCancel<T>(value: T | symbol): T {
    if (p.isCancel(value)) {
      saveProgress();
      p.cancel(`Setup cancelled. Progress saved to ${ENV_FILENAME}`);
      process.exit(0);
    }
    return value;
  }

  async function promptForKey(
    key: string,
    message: string,
    hint?: string
  ): Promise<void> {
    if (vars.has(key)) {
      p.log.success(`${key} — already configured`);
      return;
    }

    const value = checkCancel(
      await p.text({
        message: hint ? `${message}\n${chalk.dim(hint)}` : message,
        placeholder: `Paste your ${key} here…`,
      })
    );

    if (value) {
      vars.set(key, value);
      saveProgress();
    }
  }

  // -------------------------------------------------------------------------
  // Prerequisites
  // -------------------------------------------------------------------------
  const prereqs = p.spinner();
  prereqs.start('Checking prerequisites');

  const bunVersion = getBunVersion();
  const hasDocker = isProd ? false : commandExists('docker');

  prereqs.stop('Prerequisites checked');

  if (!bunVersion) {
    p.log.error('Bun is not installed. Install it from https://bun.sh');
    process.exit(1);
  }

  if (!versionGte(bunVersion, MIN_BUN_VERSION)) {
    p.log.error(
      `Bun ${bunVersion} found, but ${MIN_BUN_VERSION}+ is required. Run: curl -fsSL https://bun.sh/install | bash`
    );
    process.exit(1);
  }
  p.log.success(`Bun ${bunVersion}`);

  if (!isProd) {
    if (hasDocker) {
      p.log.success('Docker installed');
    } else {
      p.log.warn(
        'Docker not found — QStash workflow emulator will be unavailable. Install OrbStack (https://orbstack.dev) or Docker Desktop.'
      );
    }
  }

  if (existing.size > 0) {
    p.log.info(
      `Found existing ${ENV_FILENAME} with ${existing.size} configured values`
    );
  }

  // Install dependencies (local only)
  if (!isProd) {
    const installSpinner = p.spinner();
    installSpinner.start('Installing dependencies');
    try {
      execFileSync('bun', ['install'], { stdio: 'pipe', cwd: process.cwd() });
      installSpinner.stop('Dependencies installed');
    } catch (error) {
      installSpinner.stop('Dependency installation failed');
      p.log.error(
        `Install error: ${error instanceof Error ? error.message : String(error)}`
      );
      process.exit(1);
    }
  }

  // -------------------------------------------------------------------------
  // Email (Resend)
  // -------------------------------------------------------------------------
  if (isProd) {
    p.log.step(chalk.bold('Email Setup'));
    await promptForKey(
      'RESEND_API_KEY',
      'Enter your Resend API key',
      'Required for production email delivery. Get one at: https://resend.com/api-keys'
    );
    if (!vars.has('RESEND_API_KEY')) {
      p.log.error('RESEND_API_KEY is required for production.');
      process.exit(1);
    }

    if (!vars.has('EMAIL_FROM')) {
      const emailFrom = checkCancel(
        await p.text({
          message: 'Enter sender email address',
          placeholder: 'noreply@example.com',
          validate: (v) =>
            !v ? 'Sender email is required for production' : undefined,
        })
      );
      if (emailFrom) {
        vars.set('EMAIL_FROM', emailFrom);
        saveProgress();
      }
    } else {
      p.log.success('EMAIL_FROM — already configured');
    }
  } else {
    const setupEmail = checkCancel(
      await p.confirm({
        message: 'Set up email delivery? (Resend)',
        initialValue: !existing.has('RESEND_API_KEY'),
      })
    );

    if (setupEmail) {
      await promptForKey(
        'RESEND_API_KEY',
        'Enter your Resend API key',
        'Get one at: https://resend.com/api-keys'
      );
      if (vars.has('RESEND_API_KEY') && !vars.has('EMAIL_FROM')) {
        const emailFrom = checkCancel(
          await p.text({
            message: 'Enter sender email address',
            placeholder: 'noreply@example.com',
          })
        );
        if (emailFrom) {
          vars.set('EMAIL_FROM', emailFrom);
          saveProgress();
        }
      }
    } else {
      p.log.info('Skipped — OTP codes will be logged to the console.');
    }
  }

  // -------------------------------------------------------------------------
  // Hosting Platform (prod only)
  // -------------------------------------------------------------------------
  if (isProd) {
    p.log.step(chalk.bold('Hosting Platform'));

    if (vars.has('DEPLOY_PLATFORM')) {
      p.log.success(
        `DEPLOY_PLATFORM — already configured (${vars.get('DEPLOY_PLATFORM')})`
      );
    } else {
      const platform = checkCancel(
        await p.select({
          message: 'Where will you host this app?',
          options: [
            {
              value: 'cloudflare',
              label: 'Cloudflare Pages',
              hint: 'recommended',
            },
            { value: 'vercel', label: 'Vercel' },
            { value: 'railway', label: 'Railway' },
          ],
        })
      );
      vars.set('DEPLOY_PLATFORM', platform);
      saveProgress();
    }
  }

  // -------------------------------------------------------------------------
  // Core
  // -------------------------------------------------------------------------
  p.log.step(chalk.bold('Core Setup'));

  if (isProd) {
    await promptForKey(
      'APP_URL',
      'Enter your production URL',
      'e.g. https://app.example.com'
    );

    // Branch database setup by hosting platform
    const platform = vars.get('DEPLOY_PLATFORM');

    if (platform === 'cloudflare') {
      p.log.step(chalk.bold('Database (Cloudflare D1)'));
      await promptForKey(
        'CLOUDFLARE_ACCOUNT_ID',
        'Enter your Cloudflare Account ID',
        'Find in Cloudflare Dashboard → Overview → Account ID'
      );
      await promptForKey(
        'CLOUDFLARE_D1_DATABASE_ID',
        'Enter your D1 Database ID',
        'Find in Cloudflare Dashboard → D1 → your database'
      );
      await promptForKey(
        'CLOUDFLARE_API_TOKEN',
        'Enter your Cloudflare API token',
        'Create at: https://dash.cloudflare.com/profile/api-tokens (needs D1 edit permission)'
      );
    } else {
      // Vercel / Railway → Turso
      p.log.step(chalk.bold('Database (Turso)'));
      await promptForKey(
        'TURSO_DATABASE_URL',
        'Enter your Turso database URL',
        'e.g. libsql://your-db-name-org.turso.io'
      );
      await promptForKey(
        'TURSO_AUTH_TOKEN',
        'Enter your Turso auth token',
        'Get one at: https://turso.tech/app'
      );
    }
  } else {
    if (!vars.has('APP_URL')) vars.set('APP_URL', 'http://localhost:3000');
    if (!vars.has('TURSO_DATABASE_URL'))
      vars.set('TURSO_DATABASE_URL', 'file:local.db');
  }

  if (!vars.has('APP_NAME')) vars.set('APP_NAME', 'Velro');

  if (!vars.has('BETTER_AUTH_SECRET')) {
    const secret = generateSecret();
    vars.set('BETTER_AUTH_SECRET', secret);
    p.log.success('Auth secret generated');
  } else {
    p.log.success('Auth secret — already configured');
  }

  if (vars.has('TURSO_DATABASE_URL')) {
    p.log.success(`Database: ${vars.get('TURSO_DATABASE_URL')}`);
  } else if (vars.has('CLOUDFLARE_D1_DATABASE_ID')) {
    p.log.success(
      `Database: Cloudflare D1 (${vars.get('CLOUDFLARE_D1_DATABASE_ID')})`
    );
  }
  p.log.success(`App URL: ${vars.get('APP_URL')}`);
  saveProgress();

  // Run DB migrations + seed (local only)
  if (!isProd) {
    const dbSpinner = p.spinner();
    dbSpinner.start('Running database migrations');
    try {
      execFileSync(
        'bun',
        ['--bun', 'drizzle-kit', 'migrate', '--config=drizzle.config.local.ts'],
        { stdio: 'pipe', cwd: process.cwd() }
      );
      dbSpinner.stop('Database migrations applied');
    } catch (error) {
      dbSpinner.stop('Database migration failed');
      p.log.error(
        `Migration error: ${error instanceof Error ? error.message : String(error)}`
      );
      process.exit(1);
    }

    const seedSpinner = p.spinner();
    seedSpinner.start('Seeding database');
    try {
      execFileSync('bun', ['--bun', 'scripts/seed.ts', '--local'], {
        stdio: 'pipe',
        cwd: process.cwd(),
      });
      seedSpinner.stop('Database seeded');
    } catch (error) {
      seedSpinner.stop('Database seed failed');
      p.log.error(
        `Seed error: ${error instanceof Error ? error.message : String(error)}`
      );
      process.exit(1);
    }
  }

  // -------------------------------------------------------------------------
  // AI Generation (FAL_KEY)
  // -------------------------------------------------------------------------
  const setupAI = checkCancel(
    await p.confirm({
      message: 'Set up AI image & video generation?',
      initialValue: !existing.has('FAL_KEY'),
    })
  );

  if (setupAI) {
    await promptForKey(
      'FAL_KEY',
      'Enter your Fal.ai API key',
      'Get one at: https://fal.ai/dashboard/keys'
    );
  }

  // -------------------------------------------------------------------------
  // Script Analysis (OPENROUTER_KEY)
  // -------------------------------------------------------------------------
  const setupLLM = checkCancel(
    await p.confirm({
      message: 'Set up LLM-powered script analysis?',
      initialValue: !existing.has('OPENROUTER_KEY'),
    })
  );

  if (setupLLM) {
    await promptForKey(
      'OPENROUTER_KEY',
      'Enter your OpenRouter API key',
      'Get one at: https://openrouter.ai/settings/keys'
    );
  }

  // -------------------------------------------------------------------------
  // Workflows (QStash)
  // -------------------------------------------------------------------------
  if (isProd) {
    const setupWorkflows = checkCancel(
      await p.confirm({
        message: 'Set up async workflows? (Upstash QStash)',
        initialValue: !existing.has('QSTASH_TOKEN'),
      })
    );

    if (setupWorkflows) {
      await promptForKey(
        'QSTASH_TOKEN',
        'Enter your QStash token',
        'Get one at: https://console.upstash.com/qstash'
      );
      await promptForKey(
        'QSTASH_CURRENT_SIGNING_KEY',
        'Enter your QStash current signing key'
      );
      await promptForKey(
        'QSTASH_NEXT_SIGNING_KEY',
        'Enter your QStash next signing key'
      );
    }
  } else if (hasDocker) {
    const setupWorkflows = checkCancel(
      await p.confirm({
        message: 'Set up async workflows? (requires Docker)',
        initialValue: !existing.has('QSTASH_TOKEN'),
      })
    );

    if (setupWorkflows) {
      if (existing.has('QSTASH_TOKEN')) {
        p.log.success('QStash — already configured');
      } else {
        vars.set('QSTASH_URL', 'http://127.0.0.1:8080');
        vars.set(
          'QSTASH_TOKEN',
          'eyJVc2VySUQiOiJkZWZhdWx0VXNlciIsIlBhc3N3b3JkIjoiZGVmYXVsdFBhc3N3b3JkIn0='
        );
        vars.set(
          'QSTASH_CURRENT_SIGNING_KEY',
          'sig_7kYjw48mhY7kAjqNGcy6cr29RJ6r'
        );
        vars.set('QSTASH_NEXT_SIGNING_KEY', 'sig_5ZB6DVzB1wjE8S6rZ7eenA8Pdnhs');
        saveProgress();
        p.log.success('QStash configured for local Docker emulator');
      }

      p.note(
        'Run `bun qstash:dev` in a separate terminal to start the emulator.',
        'QStash Emulator'
      );
    }
  }

  // -------------------------------------------------------------------------
  // Storage (R2)
  // -------------------------------------------------------------------------
  const setupStorage = checkCancel(
    await p.confirm({
      message: 'Set up cloud storage for media? (Cloudflare R2)',
      initialValue: false,
    })
  );

  if (setupStorage) {
    const r2Keys: Array<{ key: string; message: string; hint?: string }> = [
      {
        key: 'R2_ACCOUNT_ID',
        message: 'Cloudflare Account ID',
        hint: 'Find in Cloudflare Dashboard > R2 > Overview',
      },
      { key: 'R2_ACCESS_KEY_ID', message: 'R2 Access Key ID' },
      { key: 'R2_SECRET_ACCESS_KEY', message: 'R2 Secret Access Key' },
      { key: 'R2_BUCKET_NAME', message: 'R2 Bucket Name' },
      {
        key: 'R2_PUBLIC_STORAGE_DOMAIN',
        message: 'R2 Public Domain (e.g. storage.example.com)',
      },
    ];

    for (const { key, message, hint } of r2Keys) {
      await promptForKey(key, message, hint);
    }
  }

  // -------------------------------------------------------------------------
  // Google OAuth
  // -------------------------------------------------------------------------
  const setupGoogle = checkCancel(
    await p.confirm({
      message: 'Set up Google sign-in? (or use email OTP)',
      initialValue: false,
    })
  );

  if (setupGoogle) {
    await promptForKey(
      'GOOGLE_CLIENT_ID',
      'Google OAuth Client ID',
      'Get one at: https://console.cloud.google.com/apis/credentials'
    );
    await promptForKey('GOOGLE_CLIENT_SECRET', 'Google OAuth Client Secret');
  }

  // -------------------------------------------------------------------------
  // Observability (Langfuse)
  // -------------------------------------------------------------------------
  const setupLangfuse = checkCancel(
    await p.confirm({
      message:
        'Set up Langfuse for prompt management & LLM tracing? (optional)',
      initialValue: false,
    })
  );

  if (setupLangfuse) {
    await promptForKey(
      'LANGFUSE_PUBLIC_KEY',
      'Langfuse Public Key',
      'Get one at: https://cloud.langfuse.com/project/settings'
    );
    await promptForKey('LANGFUSE_SECRET_KEY', 'Langfuse Secret Key');
    await promptForKey(
      'LANGFUSE_BASE_URL',
      'Langfuse Base URL (leave empty for cloud)',
      'Default: https://cloud.langfuse.com'
    );
  }

  // -------------------------------------------------------------------------
  // Billing (Stripe)
  // -------------------------------------------------------------------------
  const setupBilling = checkCancel(
    await p.confirm({
      message: 'Set up Stripe billing?',
      initialValue: false,
    })
  );

  if (setupBilling) {
    await promptForKey(
      'STRIPE_SECRET_KEY',
      'Stripe Secret Key (sk_test_...)',
      'Get one at: https://dashboard.stripe.com/test/apikeys'
    );
    await promptForKey(
      'STRIPE_WEBHOOK_SECRET',
      'Stripe Webhook Secret (whsec_...)',
      'Run `stripe listen` to get this'
    );

    p.note(
      'Run `bun stripe:dev` in a separate terminal for webhook forwarding.',
      'Stripe Webhooks'
    );
  }

  // -------------------------------------------------------------------------
  // Write env file
  // -------------------------------------------------------------------------
  writeEnvFile(vars);
  p.log.success(`Wrote ${ENV_FILE}`);

  // -------------------------------------------------------------------------
  // Summary
  // -------------------------------------------------------------------------
  const platformLabels: Record<string, string> = {
    cloudflare: 'Cloudflare Pages',
    vercel: 'Vercel',
    railway: 'Railway',
  };

  const features = [
    [
      'Hosting',
      isProd
        ? (platformLabels[vars.get('DEPLOY_PLATFORM') ?? ''] ?? 'Unknown')
        : 'Local',
    ],
    [
      'Database',
      isProd
        ? vars.has('CLOUDFLARE_D1_DATABASE_ID')
          ? 'Cloudflare D1'
          : vars.has('TURSO_DATABASE_URL')
            ? 'Turso'
            : 'Skipped'
        : 'SQLite (local.db)',
    ],
    ['Auth', 'Better Auth (secret generated)'],
    ['Email', vars.has('RESEND_API_KEY') ? 'Configured' : 'Skipped'],
    ['AI Generation', vars.has('FAL_KEY') ? 'Configured' : 'Skipped'],
    ['Script Analysis', vars.has('OPENROUTER_KEY') ? 'Configured' : 'Skipped'],
    ['Workflows', vars.has('QSTASH_TOKEN') ? 'Configured' : 'Skipped'],
    ['Storage', vars.has('R2_ACCOUNT_ID') ? 'Configured' : 'Skipped'],
    ['Google OAuth', vars.has('GOOGLE_CLIENT_ID') ? 'Configured' : 'Skipped'],
    [
      'Langfuse',
      vars.has('LANGFUSE_PUBLIC_KEY')
        ? 'Configured'
        : 'Skipped (using local prompts)',
    ],
    ['Billing', vars.has('STRIPE_SECRET_KEY') ? 'Configured' : 'Skipped'],
  ];

  const summaryLines = features
    .map(
      ([name, status]) =>
        `${status.includes('Skip') || status.includes('Disabled') ? '○' : '●'} ${name}: ${status}`
    )
    .join('\n');

  p.note(summaryLines, 'Configuration Summary');

  if (isProd) {
    const platform = vars.get('DEPLOY_PLATFORM');
    const nextSteps =
      platform === 'cloudflare'
        ? [
            `1. Upload secrets:  ${chalk.bold('bun scripts/setup-cloudflare-secrets.sh --production')}`,
            `2. Run migrations:  ${chalk.bold('bun db:migrate:d1')}`,
            `3. Deploy:          ${chalk.bold('bun cf:deploy:prd')}`,
          ]
        : platform === 'vercel'
          ? [
              `1. Set env vars in Vercel dashboard (copy from ${chalk.bold(ENV_FILENAME)})`,
              `2. Run migrations:  ${chalk.bold('bun db:migrate')}`,
              `3. Deploy:          ${chalk.bold('vercel deploy --prod')}`,
            ]
          : [
              `1. Set env vars in Railway dashboard (copy from ${chalk.bold(ENV_FILENAME)})`,
              `2. Run migrations:  ${chalk.bold('bun db:migrate')}`,
              `3. Deploy:          ${chalk.bold('railway up')}`,
            ];

    p.note(nextSteps.join('\n'), 'Next Steps');
  }

  p.outro(
    isProd
      ? `Production config written to ${chalk.bold(ENV_FILENAME)}`
      : `Run ${chalk.bold('bun dev')} to start the development server.`
  );
}

main().catch((error) => {
  p.log.error(
    `Setup failed: ${error instanceof Error ? error.message : String(error)}`
  );
  process.exit(1);
});
