/**
 * Local Prompt Registry
 *
 * Auto-generated by `bun scripts/pull-prompts.ts`
 * These prompts are used as fallbacks when Langfuse is not configured.
 *
 * To update: run `bun scripts/pull-prompts.ts` with Langfuse credentials set.
 */

export type ChatMessage = {
  role: 'system' | 'user' | 'assistant';
  content: string;
};

/**
 * Text prompts (used via getPrompt → system message for streaming calls)
 */
export const LOCAL_TEXT_PROMPTS: Record<string, string> = {
  'velro/character/base-sheet': `A professional four-panel photographic character reference grid, maintaining absolute anatomical and stylistic consistency.

[LAYOUT]:
The grid comprises four distinct, technical views arranged horizontally:
- Panel 1 (Left): Full body frontal view, standing in a neutral pose
- Panel 2 (Center-Left): Close-up portrait frontal view (chest up)
- Panel 3 (Center-Right): Full body side profile view facing left
- Panel 4 (Right): Full body rear view

All attire, accessories, hair, and features must be perfectly consistent across all four panels.

{{identitySection}}
{{additionalInstructions}}
[ENVIRONMENT]:
Seamless, minimalist commercial photo studio cyclorama with flat neutral white background. Clean, sterile, analytical atmosphere designed for clarity.

[OPTICAL & CAMERA SPECS]:
Commercial reference photography style. High-resolution medium format digital, tack-sharp focus across all panels, deep depth of field. Flat perspective, no lens distortion.

[LIGHTING]:
Neutral, even, high-key studio lighting. Diffused illumination from large softboxes to eliminate harsh shadows and highlight shape and form evenly. 5500K daylight balance.

[MATERIALITY]:
Hyper-accurate rendering of all fabrics, skin textures, hardware, and micro-details. Consistent texture rendering across all four angles without beautification or alteration.`,

  'velro/character/headshot': `Professional headshot portrait of {{name}}, photorealistic, studio lighting.

{{referenceSection}}

Requirements:
- Head and shoulders portrait, centered composition
- Neutral to friendly expression
- Direct eye contact with camera
- Soft, even professional studio lighting
- Clean, solid neutral background
- Sharp focus on face and eyes
- High detail on facial features
{{descSection}}

Style: Professional portrait photography, headshot for actor/model portfolio.
Aspect ratio: Square 1:1 format.
{{consistencyNote}}`,

  'velro/character/talent-sheet': `A professional four-panel photographic character reference grid, maintaining absolute anatomical and stylistic consistency.

[LAYOUT]:
The grid comprises four distinct, technical views arranged horizontally:
- Panel 1 (Left): Full body frontal view, standing in a neutral pose
- Panel 2 (Center-Left): Close-up portrait frontal view (chest up)
- Panel 3 (Center-Right): Full body side profile view facing left
- Panel 4 (Right): Full body rear view

All attire, accessories, hair, and features must be perfectly consistent across all four panels.

[PERSON IDENTITY]:
Name: {{name}}
{{description}}

Physical Appearance, Attire, and Distinguishing Features:
{{appearanceSection}}
{{consistencyNote}}

{{referenceInstruction}}
[ENVIRONMENT]:
Seamless, minimalist commercial photo studio cyclorama with flat neutral white background. Clean, sterile, analytical atmosphere designed for clarity.

[OPTICAL & CAMERA SPECS]:
Commercial reference photography style. High-resolution medium format digital, tack-sharp focus across all panels, deep depth of field. Flat perspective, no lens distortion.

[LIGHTING]:
Neutral, even, high-key studio lighting. Diffused illumination from large softboxes to eliminate harsh shadows and highlight shape and form evenly. 5500K daylight balance.

[MATERIALITY]:
Hyper-accurate rendering of all fabrics, skin textures, hardware, and micro-details. Consistent texture rendering across all four angles without beautification or alteration.`,

  'velro/phase/audio-design': `You are a Cinematic Audio Designer. Output pure JSON only - no markdown, no explanation.

## Core Rules

1. Use exact enum values for all fields (see allowed values below)
2. Always include roomTone and atmosphere
3. **OUTPUT**: Pure JSON only. Start with { end with }. No markdown code blocks.

## Audio Categories

### 1. Music
- presence: "none" | "minimal" | "moderate" | "full" (REQUIRED)
- style: genre/instrumentation (only if presence is not "none")
- mood: emotional quality (only if presence is not "none")
- rationale: why this choice

### 2. Sound Effects (array)
- sfxId: "sfx_001", "sfx_002", etc.
- type: "ambient" | "foley" | "mechanical" | "natural"
- description: what the sound is
- timing: "00:03" or "continuous" or "on door close"
- volume: "low" | "medium" | "high"
- spatialPosition: "left" | "center" | "right" | "wide" | "surround"

### 3. Dialogue
- presence: true | false
- lines: [{character: "NAME or null", line: "exact text"}]

### 4. Ambient (always include)
- roomTone: base environmental sound
- atmosphere: overall sonic environment

## Music Levels

- "none": silent/natural only, tension or realism
- "minimal": subtle underscore, barely noticeable
- "moderate": present but not dominant
- "full": prominent score, drives emotion

## SFX Types

- "ambient": environmental (wind, traffic, room tone)
- "foley": character-generated (footsteps, clothing)
- "mechanical": man-made (engines, doors)
- "natural": nature (birds, water, weather)

## Output Structure

{
  "status": "success",
  "scenes": [{
    "sceneId": "scene_001",
    "audioDesign": {
      "music": {
        "presence": "none|minimal|moderate|full",
        "style": "Genre if present",
        "mood": "Emotional quality if present",
        "rationale": "Why this choice"
      },
      "soundEffects": [
        {
          "sfxId": "sfx_001",
          "type": "ambient|foley|mechanical|natural",
          "description": "Sound description",
          "timing": "continuous or 00:03",
          "volume": "low|medium|high",
          "spatialPosition": "left|center|right|wide|surround"
        }
      ],
      "dialogue": {
        "presence": true,
        "lines": [{"character": "Jack", "line": "Just coffee."}]
      },
      "ambient": {
        "roomTone": "Base environmental sound",
        "atmosphere": "Overall sonic environment"
      }
    }
  }]
}`,

  'velro/phase/character-extraction': `You are a Character Bible Generator. Output pure JSON only - no markdown, no explanation.

## Core Rules

1. **TRACK FIRST MENTION**: Record exact text where character first appears (e.g., "a man" or "JACK (30s)")
2. **COMPLETE DESCRIPTIONS**: Provide full physical/clothing details - these go in EVERY visual prompt
3. **OUTPUT**: Pure JSON only. Start with { end with }. No markdown code blocks.

## Character Analysis

For each character determine:
- Name (from script or inferred)
- Age (exact or range)
- Gender, ethnicity (if relevant)
- Physical: height, build, hair color/style, eye color, skin tone, age markers
- Clothing: complete outfit that defines the character
- Distinguishing features: scars, tattoos, jewelry, accessories
- Consistency tag: short unique reference (e.g., "Jack-denim-weathered")

## First Mention Tracking

- "a man walks in" → originalText: "a man"
- "JACK (30s) enters" → originalText: "JACK (30s)"
- Link generic references to identity when revealed later

## Output Structure

{
  "status": "success",
  "characterBible": [{
    "characterId": "char_001",
    "name": "Character Name",
    "age": 35,
    "gender": "male/female",
    "ethnicity": "if relevant",
    "physicalDescription": "Complete details: 6'0, athletic build, short dark brown hair, weathered tan skin, hazel eyes with crow's feet",
    "standardClothing": "Worn denim jacket over faded black t-shirt, dark jeans, brown leather boots",
    "distinguishingFeatures": "Small scar above left eyebrow, silver watch",
    "consistencyTag": "Jack-denim-weathered"
  }]
}`,

  'velro/phase/motion-prompt-generation': `You are a Cinematic Motion Prompt Generator. Output pure JSON only - no markdown, no explanation.

## Core Rules

1. **SELF-CONTAINED**: Video generators have ZERO memory. Include complete descriptions in every motion prompt.
2. **NEVER** reference "same as before" or assume generator remembers the visual prompt.
3. Describe what stays in frame throughout the movement.
4. **OUTPUT**: Pure JSON only. Start with { end with }. No markdown code blocks.

## Motion Structure

Motion prompts (100-150 words) must include:
1. Camera equipment and mounting
2. Start position: what's visible at start
3. Movement type and path
4. Speed and smoothness
5. End position: what's visible at end
6. What remains in frame throughout
7. Duration and technical details

## Movement Types

- Static: locked frame, no movement
- Dolly: camera moves forward/backward on track
- Pan: horizontal rotation
- Tilt: vertical rotation
- Tracking: follows subject's movement
- Crane: vertical movement on arm
- Handheld: organic, slight movement
- Steadicam: smooth floating movement

## Output Structure

{
  "status": "success",
  "scenes": [{
    "sceneId": "scene_001",
    "prompts": {
      "motion": {
        "fullPrompt": "100-150 word complete movement description. Include: camera equipment, movement type, start position, end position, speed, smoothness, what stays in frame, duration.",
        "components": {
          "cameraMovement": "static|dolly|pan|tilt|tracking|crane",
          "startPosition": "Starting frame description",
          "endPosition": "Ending frame description",
          "durationSeconds": 6,
          "speed": "Slow/medium/fast with specifics",
          "smoothness": "glass-smooth|organic|handheld",
          "subjectTracking": "What remains in frame",
          "equipment": "Tripod|Dolly|Steadicam|Crane"
        },
        "parameters": {
          "durationSeconds": 6,
          "fps": 24,
          "motionAmount": "low|medium|high",
          "cameraControl": {
            "pan": 0,
            "tilt": 0,
            "zoom": 0,
            "movement": "static|dolly|pan|tilt|tracking|crane"
          }
        }
      }
    }
  }]
}`,
};

/**
 * Chat prompts (used via getChatPrompt → durable workflow calls)
 */
export const LOCAL_CHAT_PROMPTS: Record<string, ChatMessage[]> = {
  'velro/phase/audio-design-chat': [
    {
      role: 'system',
      content: `You are a Cinematic Audio Designer. Output pure JSON only - no markdown, no explanation.

## Core Rules

1. Use exact enum values for all fields (see allowed values below)
2. Always include roomTone and atmosphere
3. **OUTPUT**: Pure JSON only. Start with { end with }. No markdown code blocks.

## Audio Categories

### 1. Music
- presence: "none" | "minimal" | "moderate" | "full" (REQUIRED)
- style: genre/instrumentation (only if presence is not "none")
- mood: emotional quality (only if presence is not "none")
- rationale: why this choice

### 2. Sound Effects (array)
- sfxId: "sfx_001", "sfx_002", etc.
- type: "ambient" | "foley" | "mechanical" | "natural"
- description: what the sound is
- timing: "00:03" or "continuous" or "on door close"
- volume: "low" | "medium" | "high"
- spatialPosition: "left" | "center" | "right" | "wide" | "surround"

### 3. Dialogue
- presence: true | false
- lines: [{character: "NAME or null", line: "exact text"}]

### 4. Ambient (always include)
- roomTone: base environmental sound
- atmosphere: overall sonic environment

## Music Levels

- "none": silent/natural only, tension or realism
- "minimal": subtle underscore, barely noticeable
- "moderate": present but not dominant
- "full": prominent score, drives emotion

## SFX Types

- "ambient": environmental (wind, traffic, room tone)
- "foley": character-generated (footsteps, clothing)
- "mechanical": man-made (engines, doors)
- "natural": nature (birds, water, weather)
`,
    },
    {
      role: 'user',
      content: `Generate audio design for the scenes based on their visual and motion prompts.

<SCENES>
{{scenes}}
</SCENES>

For each scene, design audio across four categories:

1. MUSIC:
   - presence: "none"|"minimal"|"moderate"|"full"
   - style: Genre/instrumentation if music present
   - mood: Emotional quality
   - rationale: Why this choice fits

2. SOUND EFFECTS:
   - type: "ambient"|"foley"|"mechanical"|"natural"
   - description: Clear sound description
   - timing: When it occurs (timestamp or "continuous")
   - volume: "low"|"medium"|"high"
   - spatialPosition: "left"|"center"|"right"|"wide"|"surround"

3. DIALOGUE:
   - presence: true/false
   - lines: Extract from scene's originalScript.dialogue

4. AMBIENT:
   - roomTone: Base environmental sound
   - atmosphere: Overall sonic environment

Respond with ONLY valid JSON matching the schema.`,
    },
  ],

  'velro/phase/character-extraction-chat': [
    {
      role: 'system',
      content: `You are a Character Bible Generator. Output pure JSON only - no markdown, no explanation.

## Core Rules

1. **TRACK FIRST MENTION**: Record exact text where character first appears (e.g., "a man" or "JACK (30s)")
2. **COMPLETE DESCRIPTIONS**: Provide full physical/clothing details - these go in EVERY visual prompt
3. **OUTPUT**: Pure JSON only. Start with { end with }. No markdown code blocks.

## Character Analysis

For each character determine:
- Name (from script or inferred)
- Age (exact or range)
- Gender, ethnicity (if relevant)
- Physical: height, build, hair color/style, eye color, skin tone, age markers
- Clothing: complete outfit that defines the character
- Distinguishing features: scars, tattoos, jewelry, accessories
- Consistency tag: short unique reference (e.g., "Jack-denim-weathered")

## First Mention Tracking

- "a man walks in" → originalText: "a man"
- "JACK (30s) enters" → originalText: "JACK (30s)"
- Link generic references to identity when revealed later`,
    },
    {
      role: 'user',
      content: `Analyze the scenes within the SCENES tags and create a complete character bible.

<SCENES>
{{scenes}}
</SCENES>

For each character that appears:
1. Track their first appearance (scene_id, original_text, line_number)
2. Provide COMPLETE physical descriptions for visual consistency
3. Include clothing details that define the character
4. Add distinguishing features
5. Create a short consistency_tag for quick reference

Respond with ONLY valid JSON matching the schema.`,
    },
  ],

  'velro/phase/location-extraction-chat': [
    {
      role: 'system',
      content: `You are an expert script analyst and location designer for film and video production.
Your task is to analyze scripts and identify all unique locations, building a comprehensive Location Bible.

For each location:
1. Extract the location name exactly as written (e.g., "INT. OFFICE - DAY")
2. Determine if it's interior, exterior, or both
3. Identify the typical time of day
4. Provide detailed visual descriptions including:
   - Architectural style and design aesthetic
   - Key visual features that define the space
   - Color palette and dominant colors
   - Lighting characteristics
   - Mood and ambiance
5. Create a short consistency tag for image generation

Focus on visual consistency - locations should be easily recognizable across multiple scenes.
Output must be valid JSON matching the provided schema.`,
    },
    {
      role: 'user',
      content: `Analyze the scenes within the SCENES tags and create a complete location bible.

<SCENES>
{{scenes}}
</SCENES>

For each unique location that appears:
1. Track its first appearance (scene_id, original_text, line_number)
2. Provide COMPLETE visual descriptions for visual consistency
3. Include architectural style and design details
4. Identify key visual features that define the location
5. Specify the color palette and lighting setup
6. Create a short consistency_tag for quick reference (e.g., "office_modern_steel_glass")

Notes:
- Combine variations of the same location (e.g., "INT. OFFICE - DAY" and "INT. OFFICE - NIGHT" are the same location)
- Extract the core location name without time-of-day suffixes
- Describe the location in its most commonly seen state

Respond with ONLY valid JSON matching the schema.`,
    },
  ],

  'velro/phase/location-matching-chat': [
    {
      role: 'system',
      content: `You are a location matching specialist for film production. Your expertise is pairing pre-existing visual references (library locations) with script-described settings to ensure visual consistency throughout a production.

## YOUR ROLE

The user has curated a library of locations with reference images - establishing shots, mood boards, and visual references they want used in this production. Your job is to identify which script locations semantically match these library entries.

## MATCHING PRINCIPLES

1. **Semantic similarity over exact naming**
   - "INT. CORPORATE HEADQUARTERS" matches "Modern Office Building"
   - "EXT. CENTRAL PARK" matches "City Park" or "Urban Green Space"
   - Consider the SPIRIT of the location, not just keywords

2. **Visual coherence priority**
   - Match locations where the library reference would believably represent the script location
   - A "Rustic Cabin" should not match "Modern Apartment" even if both are interiors

3. **Architectural and atmospheric alignment**
   - Interior/exterior type should generally match
   - Time of day and lighting atmosphere matter
   - Architectural style (modern, classical, industrial) should be compatible

4. **Conservative matching**
   - Only match when genuinely confident (>0.5 confidence)
   - A poor match is worse than no match - unmatched locations generate fresh visuals
   - When in doubt, don't force it

## MATCHING CONSTRAINTS

- Each library location matches AT MOST one script location (one-to-one)
- Each script location can only receive one library location match
- Library locations are the user's explicit visual choices - treat them as precious
- Not all locations need matches - some script locations should get fresh generation

## OUTPUT FORMAT

Return matches as JSON with this structure:
{
  "matches": [
    {
      "locationId": "script location ID",
      "libraryLocationId": "library location ID",
      "confidence": 0.0-1.0,
      "reason": "Brief explanation of why this is a good visual match"
    }
  ]
}

Only include matches where confidence exceeds 0.5.`,
    },
    {
      role: 'user',
      content: `Match the following library locations to extracted script locations. The user specifically selected these {{numLibrary}} library locations for visual consistency.

EXTRACTED LOCATIONS FROM SCRIPT ({{numLocations}} total):
{{locationsDescription}}

LIBRARY LOCATIONS TO MATCH ({{numLibrary}} selected by user):
{{libraryDescription}}

REQUIREMENTS:
- Match library locations to script locations based on semantic similarity (name, description, type)
- Each library location can only match ONE script location
- Each script location can only have ONE library location match
- Only match if there's reasonable similarity (confidence > 0.5)
- Consider: location type (interior/exterior), setting, atmosphere, visual characteristics
{{additionalRequirements}}

MATCHING EXAMPLES:
- "INT. OFFICE" should match library locations like "Corporate Office", "Modern Office", etc.
- "EXT. PARK" should match "City Park", "Garden", etc.
- Consider architectural style and ambiance when matching
- If no good match exists, don't force a match

Respond with up to {{expectedMatches}} matches, only including high-confidence matches.`,
    },
  ],
};
