// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.letz.ai' | (string & {});
};

export type ImageRequest = {
    prompt: string;
    width: number;
    height: number;
    quality: number;
    creativity: number;
    hasWatermark: boolean;
    systemVersion: number;
    hideFromUserProfile: boolean;
    mode: 'default' | 'sigma';
    webhookUrl: string;
    /**
     * Organization ID to deduct credits from. If provided, credits will be deducted from the organization account instead of the user account. User must be a member of the organization.
     */
    organizationId?: string;
    /**
     * Base model identifier used for generation
     */
    baseModel?: string;
};

export type PublicUserDto = {
    id: string;
    name: string;
    username: string;
    profilePicture: string;
    description: string;
    website: string;
    socialMediaAccounts: {
        [key: string]: unknown;
    };
    imagesGenerated: number;
    imagesAvailable: number;
    modelsAvailable: number;
    followersCount: number;
    followingCount: number;
    isVerified: boolean;
};

export type ModelVersionDto = {
    id: string;
    version: number;
    storagePath: string;
    systemVersions: Array<string>;
    status: string;
    createdAt: string;
    trainedAt: string;
};

export type PublicOrganizationDto = {
    [key: string]: unknown;
};

export type ModelOrganizationDto = {
    /**
     * Unique identifier of the model-organization relationship
     */
    id: string;
    /**
     * Organization that has access to the model
     */
    organization: PublicOrganizationDto;
    /**
     * User who shared the model with the organization
     */
    sharedByUser?: PublicUserDto;
    /**
     * Date when the model was shared
     */
    createdAt: string;
    /**
     * Date when the sharing was last updated
     */
    updatedAt: string;
};

export type ModelDto = {
    id: string;
    user: PublicUserDto;
    userId: string;
    name: string;
    username: string;
    class: string;
    type: string;
    description: string;
    website: string;
    status: string;
    progress: number;
    privacy: string;
    usages: number;
    imagesAvailable: number;
    likes: number;
    version: number;
    thumbnail: string;
    thumbnailOptions: {
        [key: string]: unknown;
    };
    settings: {
        [key: string]: unknown;
    };
    images: {
        [key: string]: unknown;
    };
    isActive: boolean;
    blockedAt: string;
    createdAt: string;
    systemVersions: Array<string>;
    versions: Array<ModelVersionDto>;
};

export type ImageCompletionDto = {
    id: string;
    user: PublicUserDto;
    userId: string;
    regeneratedFromId: string;
    /**
     * Original image completions
     */
    originalImageCompletions: Array<ImageCompletionDto>;
    /**
     * Original image completion (top level)
     */
    originalImageCompletion: ImageCompletionDto;
    /**
     * Original image completion IDs
     */
    originalImageCompletionIds: Array<string>;
    imageEdit: ImageEditDto;
    prompt: string;
    baseModel: string;
    promptSystem: string;
    status: string;
    statusDetail: string;
    progress: number;
    previewImage: string;
    username: string;
    queue: string;
    isUserVerified: boolean;
    isHot: boolean;
    privacy: string;
    likes: number;
    comments: number;
    liked: boolean;
    regenerations: number;
    reports: number;
    storageBucket: string;
    storagePath: string;
    generationSettings: {
        [key: string]: unknown;
    };
    generationData: string;
    generatedByUnit: string;
    generationSeconds: number;
    imagePaths: {
        [key: string]: unknown;
    };
    imageVersions: {
        [key: string]: unknown;
    };
    systemVersion: number;
    hasWatermark: boolean;
    isNsfw: boolean;
    webhookUrl: string;
    isBookmarked: boolean;
    isUnsafe: boolean;
    hidePrompt: boolean;
    blockedAt: string;
    createdAt: string;
    models: Array<ModelDto>;
    /**
     * Primary model ID used for generation (first model)
     */
    modelId?: string;
};

export type ImageEditDto = {
    /**
     * Unique identifier for the image edit
     */
    id: string;
    /**
     * Original image completions
     */
    originalImageCompletions: Array<ImageCompletionDto>;
    /**
     * Original image completion (top level)
     */
    originalImageCompletion: ImageCompletionDto;
    /**
     * Original image completion IDs
     */
    originalImageCompletionIds: Array<string>;
    /**
     * Source image completion of the edit
     */
    originalImageEdit: ImageEditDto;
    /**
     * Generated image completion
     */
    generatedImageCompletion: ImageCompletionDto;
    /**
     * Generated image completion choices
     */
    imageCompletionChoices: Array<string>;
    /**
     * Edit mode, either "in" or "out"
     */
    mode: string;
    /**
     * Width of the edited image
     */
    width: number;
    /**
     * Height of the edited image
     */
    height: number;
    /**
     * Number of image completions to be generated
     */
    imageCompletionsCount: number;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Base model identifier used for generation
     */
    baseModel: string;
    /**
     * Inpainting mask
     */
    mask: string;
    /**
     * Input image URLs
     */
    inputImageUrls: Array<string>;
    /**
     * Input image URL
     */
    imageUrl: string;
    /**
     * Webhook URL
     */
    webhookUrl: string;
    settings: {
        [key: string]: unknown;
    };
    models: Array<ModelDto>;
    /**
     * Status of the image edit process
     */
    status?: string;
    hidePrompt: boolean;
};

export type ImageDto = {
    id: string;
    user: PublicUserDto;
    imageEdit: ImageEditDto;
    prompt: string;
    baseModel: string;
    status: string;
    progressMessage: string;
    progress: number;
    previewImage: string;
    isHot: boolean;
    privacy: string;
    likes: number;
    regenerations: number;
    imageVersions: {
        [key: string]: unknown;
    };
    systemVersion: number;
    hasWatermark: boolean;
    generationSettings: {
        [key: string]: unknown;
    };
    isNsfw: boolean;
    webhookUrl: string;
    hidePrompt: boolean;
    createdAt: string;
    models: Array<ModelDto>;
};

export type ImagePrivacyRequest = {
    privacy: 'public' | 'private' | 'licensed';
};

export type ImagePromptPrivacyRequest = {
    hidePrompt: {
        [key: string]: unknown;
    };
};

export type ImageEditRequest = {
    /**
     * Original image completion IDs
     */
    originalImageCompletionIds?: Array<string>;
    /**
     * Original image completion ID
     */
    originalImageCompletionId?: string;
    /**
     * Input image URL
     */
    imageUrl: string;
    /**
     * Edit mode, either "in", "out", "skin", or "context"
     */
    mode: string;
    /**
     * Width of the edited image
     */
    width?: number;
    /**
     * Height of the edited image
     */
    height?: number;
    /**
     * Number of image completions to generate
     */
    imageCompletionsCount?: number;
    /**
     * Prompt
     */
    prompt?: string;
    /**
     * Inpainting mask
     */
    mask?: string;
    /**
     * Input image URLs
     */
    inputImageUrls: Array<string>;
    settings?: {
        [key: string]: unknown;
    };
    webhookUrl: string;
    hidePrompt: {
        [key: string]: unknown;
    };
    /**
     * Base model identifier used for generation
     */
    baseModel?: string;
    /**
     * Organization ID to deduct credits from. If provided, credits will be deducted from the organization account instead of the user account. User must be a member of the organization.
     */
    organizationId?: string;
};

export type ImageEditMaskDto = {
    /**
     * Inpainting mask
     */
    mask: string;
};

export type SettingsEnum = 'NO_VIOLENCE' | 'NO_HATE_SPEECH' | 'NO_ILLEGAL_CONTENT' | 'NO_COPYRIGHTED_CONTENT' | 'NO_ADULT_CONTENT' | 'NO_RELIGIOUS_CONTENT' | 'NO_POLITICAL_CONTENT' | 'NO_BRANDED_CONTENT' | 'NO_OTHER';

export type ModelCreateRequest = {
    name: string;
    privacy: 'public' | 'private' | 'licensed';
    type: string;
    class: 'person' | 'style' | 'object';
    description: string;
    website: string;
    settings?: Array<SettingsEnum>;
    trainingDataUrls?: Array<string>;
    webhookUrl: string;
    trainingMode: string;
    /**
     * Organization ID to deduct credits from. If provided, credits will be deducted from the organization account instead of the user account. User must be a member of the organization.
     */
    organizationId?: string;
};

export type ModelUpdateRequest = {
    privacy: 'public' | 'private' | 'licensed';
    type: string;
    description: string;
    website: string;
    settings?: Array<'NO_VIOLENCE' | 'NO_HATE_SPEECH' | 'NO_ILLEGAL_CONTENT' | 'NO_COPYRIGHTED_CONTENT' | 'NO_ADULT_CONTENT' | 'NO_RELIGIOUS_CONTENT' | 'NO_POLITICAL_CONTENT' | 'NO_BRANDED_CONTENT' | 'NO_OTHER'>;
    webhookUrl?: string;
};

export type ModelThumbnailRequest = {
    /**
     * Image completion that should be used as thumbnail for the given model
     */
    imageCompletionId: string;
};

export type UpscaleRequest = {
    prompt: string;
    mode: string;
    size: number;
    imageId: string;
    imageUrl: string;
    strength: {
        [key: string]: unknown;
    };
    webhookUrl: string;
    /**
     * Organization ID to deduct credits from. If provided, credits will be deducted from the organization account instead of the user account. User must be a member of the organization.
     */
    organizationId?: string;
};

export type UpscaleDto = {
    id: string;
    user: PublicUserDto;
    userId: string;
    imageCompletionId: string;
    imageUrl: string;
    originalImageThumbnail: string;
    status: string;
    mode: string;
    statusDetail: string;
    progress: number;
    username: string;
    createdByUsername: string;
    createdByThumbnail: string;
    isUserVerified: boolean;
    imageVersions: {
        [key: string]: unknown;
    };
    webhookUrl: string;
    selected: boolean;
    size: number;
    blockedAt: string;
    createdAt: string;
};

export type UserImageRequest = {
    /**
     * File extension of the image. This determines the file format that will be uploaded.
     */
    extension: 'jpg' | 'jpeg' | 'png' | 'gif' | 'webp';
    /**
     * Number of images to generate upload URLs for. If you need to upload multiple images at once, increase this value.
     */
    numberOfImages?: {
        [key: string]: unknown;
    };
    /**
     * Original filename of the image. This is stored for reference but does not affect the actual filename used in storage.
     */
    originalFilename?: string;
    /**
     * Additional metadata for the image. This can be any JSON object with custom properties you want to associate with the image.
     */
    metadata?: {
        [key: string]: unknown;
    };
};

export type UserImageDto = {
    id: string;
    userId: string;
    /**
     * URL to access the uploaded image. This URL will be available after uploading the image using the uploadUrl.
     */
    imageUrl: string;
    /**
     * Pre-signed S3 URL for uploading the image file. Make a PUT request to this URL with the image as the request body and appropriate Content-Type header.
     */
    uploadUrl?: string;
    originalFilename?: string;
    mimeType?: string;
    fileSize?: number;
    metadata?: {
        [key: string]: unknown;
    };
    createdAt: string;
    updatedAt: string;
};

export type VideoDto = {
    /**
     * Unique identifier for the video animation
     */
    id: string;
    /**
     * User who created the video
     */
    user: PublicUserDto;
    /**
     * User ID of the video creator
     */
    userId: string;
    /**
     * ID of the video this was regenerated from
     */
    regeneratedFromId: string;
    /**
     * Original image completion being animated
     */
    originalImageCompletion: ImageCompletionDto;
    /**
     * Original image completion ID
     */
    originalImageCompletionId: string;
    /**
     * Video animation prompt
     */
    prompt: string;
    /**
     * System prompt for video generation
     */
    promptSystem: string;
    /**
     * Base model identifier used for video generation
     */
    baseModel: string;
    /**
     * Input image URLs
     */
    imageUrls: Array<string>;
    /**
     * Input image URL
     */
    imageUrl: string;
    /**
     * Video width in pixels
     */
    width: number;
    /**
     * Video height in pixels
     */
    height: number;
    /**
     * Video resolution
     */
    resolution: number;
    /**
     * Video generation settings
     */
    settings: {
        [key: string]: unknown;
    };
    /**
     * Generation settings used for the video
     */
    generationSettings: {
        [key: string]: unknown;
    };
    /**
     * Status of the video animation process
     */
    status?: string;
    /**
     * Detailed status information
     */
    statusDetail: string;
    /**
     * Generation progress percentage (0-100)
     */
    progress: number;
    /**
     * Preview image URL for the video
     */
    previewImage: string;
    /**
     * Processing queue type
     */
    queue: string;
    /**
     * System version used for generation
     */
    systemVersion: number;
    /**
     * Generation time in seconds
     */
    generationSeconds: number;
    /**
     * Generated video file versions
     */
    videoVersions: {
        [key: string]: unknown;
    };
    /**
     * Generated image file versions
     */
    imageVersions: {
        [key: string]: unknown;
    };
    /**
     * Storage bucket for video files
     */
    storageBucket: string;
    /**
     * Storage path for video files
     */
    storagePath: string;
    /**
     * Webhook URL for completion notification
     */
    webhookUrl: string;
    /**
     * Whether to hide the prompt from public view
     */
    hidePrompt: boolean;
    /**
     * Whether the video has a watermark
     */
    hasWatermark: boolean;
    /**
     * Number of likes for this video
     */
    likes: number;
    /**
     * Number of comments for this video
     */
    comments: number;
    /**
     * Number of regenerations/remixes of this video
     */
    regenerations: number;
    /**
     * Number of reports for inappropriate content
     */
    reports: number;
    /**
     * Privacy setting for the video
     */
    privacy: string;
    /**
     * Whether the video contains NSFW content
     */
    isNsfw: boolean;
    /**
     * Whether the video is flagged as trending/hot
     */
    isHot: boolean;
    /**
     * Whether the current user has liked this video
     */
    liked: boolean;
    /**
     * Whether the video is flagged as unsafe content
     */
    isUnsafe: boolean;
    /**
     * Whether the video is actively available
     */
    isActive: boolean;
    /**
     * Whether to hide the video from user profile
     */
    hideFromUserProfile: boolean;
    /**
     * Whether the current user has bookmarked this video
     */
    isBookmarked: boolean;
    /**
     * Username of the video creator
     */
    username: string;
    /**
     * Whether the creator is a verified user
     */
    isUserVerified: boolean;
    /**
     * When the video was published/made public
     */
    publishedAt: string;
    /**
     * When the video was blocked (if applicable)
     */
    blockedAt: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Models used for video generation
     */
    models: Array<ModelDto>;
};

export type PublicVideoRequest = {
    /**
     * Original image completion ID to create video from
     */
    originalImageCompletionId?: string;
    /**
     * Input image URLs
     */
    imageUrls?: Array<string>;
    /**
     * Image URL to create video from (alternative to originalImageCompletionId)
     */
    imageUrl?: string;
    /**
     * Organization ID (for organization accounts)
     */
    organizationId?: string;
    /**
     * Width of the video
     */
    width?: number;
    /**
     * Height of the video
     */
    height?: number;
    /**
     * Resolution of the video
     */
    resolution?: number;
    /**
     * Prompt for video generation
     */
    prompt: string;
    /**
     * Base model identifier for video generation
     */
    baseModel?: string;
    /**
     * Webhook URL to receive notifications about video generation progress
     */
    webhookUrl?: string;
    /**
     * Whether to hide the prompt in public listings
     */
    hidePrompt?: {
        [key: string]: unknown;
    };
    /**
     * Additional settings for video generation
     */
    settings?: {
        [key: string]: unknown;
    };
};

export type VideoPrivacyRequest = {
    privacy: 'public' | 'private' | 'licensed';
};

export type VideoPromptPrivacyRequest = {
    /**
     * Whether to hide the prompt from public view
     */
    hidePrompt: {
        [key: string]: unknown;
    };
};

export type ImagesFindData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Field to sort by
         */
        sortBy?: string;
        /**
         * Sort order (case insensitive)
         */
        sortOrder?: 'ASC' | 'DESC' | 'asc' | 'desc';
        userId?: string;
        username?: string;
        privacy: 'public' | 'private' | 'licensed';
        status: 'new' | 'pending' | 'training' | 'finished' | 'available' | 'failed';
        systemVersion?: number;
        isHot?: boolean;
        includeNsfw: boolean;
        onlyFollowing?: boolean;
        modelIds?: Array<unknown>;
    };
    url: '/images';
};

export type ImagesFindErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - `page`: Must be a positive integer.
     * - `limit`: Must be a positive integer between 1 and 100.
     * - `sortBy`: Must be one of the allowed sort fields.
     * - `sortOrder`: Must be either 'ASC' or 'DESC'.
     * - Invalid filter parameters provided.
     * - Malformed query parameters.
     *
     */
    400: unknown;
    /**
     * Unauthorized. Authentication token is missing or invalid
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to access these images
     */
    403: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while retrieving images
     */
    500: unknown;
};

export type ImagesFindResponses = {
    /**
     * Successfully retrieved the list of images
     */
    200: Array<ImageDto>;
};

export type ImagesFindResponse = ImagesFindResponses[keyof ImagesFindResponses];

export type ImagesCreateData = {
    /**
     * The image creation request parameters including prompt, dimensions, and quality settings
     */
    body: ImageRequest;
    path?: never;
    query?: never;
    url: '/images';
};

export type ImagesCreateErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - `width`: Must be between 480 and 2160 pixels.
     * - `height`: Must be between 480 and 2160 pixels.
     * - `quality`: Must be between 1 and 6.
     * - `creativity`: Must be between 1 and 6.
     * - `systemVersion`: Must be either 2 or 3.
     * - `mode`: Must be a valid value from the `ModeEnum`.
     * - `organizationId`: Must be a valid UUID format.
     * - Invalid or unavailable model referenced in prompt.
     * - Failed to analyze prompt or parameters.
     * - Organization does not exist.
     *
     */
    400: unknown;
    /**
     * Unauthorized. Authentication token is missing or invalid, or user is not a member of the specified organization
     */
    401: unknown;
    /**
     * Payment Required. Insufficient credits to create the image (either user or organization credits depending on request)
     */
    402: unknown;
    /**
     * Forbidden. User does not have permission to create images
     */
    403: unknown;
    /**
     * Internal Server Error. An unexpected error occurred during image creation
     */
    500: unknown;
};

export type ImagesCreateResponses = {
    /**
     * The image generation request was successfully created and queued for processing
     */
    201: ImageDto;
};

export type ImagesCreateResponse = ImagesCreateResponses[keyof ImagesCreateResponses];

export type ImagesGetData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the image
         */
        id: string;
    };
    query?: never;
    url: '/images/{id}';
};

export type ImagesGetErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - `id`: Must be a valid UUID format.
     * - Invalid image identifier provided.
     *
     */
    400: unknown;
    /**
     * Unauthorized. Authentication token is missing or invalid
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to access this image
     */
    403: unknown;
    /**
     * Not Found. The requested image does not exist
     */
    404: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while retrieving the image
     */
    500: unknown;
};

export type ImagesGetResponses = {
    /**
     * Successfully retrieved the image details
     */
    200: ImageDto;
};

export type ImagesGetResponse = ImagesGetResponses[keyof ImagesGetResponses];

export type ImagesInterruptData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the image to interrupt
         */
        id: string;
    };
    query?: never;
    url: '/images/{id}/interruption';
};

export type ImagesInterruptErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Image is not in a processing state
     * - Image does not exist
     * - Image belongs to another user
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Not Found. The requested image could not be found.
     */
    404: unknown;
    /**
     * Internal Server Error. An unexpected error occurred.
     */
    500: unknown;
};

export type ImagesInterruptResponses = {
    /**
     * The image generation was successfully interrupted.
     */
    204: void;
};

export type ImagesInterruptResponse = ImagesInterruptResponses[keyof ImagesInterruptResponses];

export type ImagesPrivacyChangeData = {
    body: ImagePrivacyRequest;
    path: {
        /**
         * The unique identifier of the image to update
         */
        id: string;
    };
    query?: never;
    url: '/images/{id}/privacy';
};

export type ImagesPrivacyChangeErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Image is not in READY state
     * - Image contains NSFW content
     * - Image uses private models
     * - Invalid privacy value
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Not Found. The requested image could not be found.
     */
    404: unknown;
    /**
     * Internal Server Error. An unexpected error occurred.
     */
    500: unknown;
};

export type ImagesPrivacyChangeResponses = {
    /**
     * The image privacy was successfully updated.
     */
    204: void;
};

export type ImagesPrivacyChangeResponse = ImagesPrivacyChangeResponses[keyof ImagesPrivacyChangeResponses];

export type ImagesPromptPrivacyChangeData = {
    body: ImagePromptPrivacyRequest;
    path: {
        /**
         * The unique identifier of the image to update prompt privacy
         */
        id: string;
    };
    query?: never;
    url: '/images/{id}/prompt-privacy';
};

export type ImagesPromptPrivacyChangeErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Invalid prompt privacy value
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Not Found. The requested image could not be found.
     */
    404: unknown;
    /**
     * Internal Server Error. An unexpected error occurred.
     */
    500: unknown;
};

export type ImagesPromptPrivacyChangeResponses = {
    204: void;
};

export type ImagesPromptPrivacyChangeResponse = ImagesPromptPrivacyChangeResponses[keyof ImagesPromptPrivacyChangeResponses];

export type ImageEditFindData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Field to sort by
         */
        sortBy?: string;
        /**
         * Sort order (case insensitive)
         */
        sortOrder?: 'ASC' | 'DESC' | 'asc' | 'desc';
        status: 'new' | 'generating' | 'ready' | 'saved' | 'failed' | 'interrupted';
    };
    url: '/image-edits';
};

export type ImageEditFindErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Invalid pagination parameters
     * - Invalid sort parameters
     * - Invalid filter values
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while retrieving the image edits.
     */
    500: unknown;
};

export type ImageEditFindResponses = {
    /**
     * List of image edits successfully retrieved.
     */
    200: Array<ImageEditDto>;
};

export type ImageEditFindResponse = ImageEditFindResponses[keyof ImageEditFindResponses];

export type ImageEditCreateData = {
    /**
     * The image edit request parameters
     */
    body: ImageEditRequest;
    path?: never;
    query?: never;
    url: '/image-edits';
};

export type ImageEditCreateErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Invalid input parameters
     * - Source image does not exist
     * - Source image is not in a valid state
     * - Invalid edit settings
     * - organizationId: Must be a valid UUID format
     * - Organization does not exist
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated, or user is not a member of the specified organization.
     */
    401: unknown;
    /**
     * Payment Required. Insufficient credits to create the image edit (either user or organization credits depending on request).
     */
    402: unknown;
    /**
     * Forbidden. User does not have permission to create image edits.
     */
    403: unknown;
    /**
     * Internal Server Error. An unexpected error occurred during image edit creation.
     */
    500: unknown;
};

export type ImageEditCreateResponses = {
    /**
     * The image edit was successfully created.
     */
    201: ImageEditDto;
};

export type ImageEditCreateResponse = ImageEditCreateResponses[keyof ImageEditCreateResponses];

export type ImageEditGetData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the image edit to retrieve
         */
        id: string;
    };
    query?: never;
    url: '/image-edits/{id}';
};

export type ImageEditGetErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Invalid ID format
     * - Image edit does not exist
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to access this image edit.
     */
    403: unknown;
    /**
     * Not Found. The requested image edit could not be found.
     */
    404: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while retrieving the image edit.
     */
    500: unknown;
};

export type ImageEditGetResponses = {
    /**
     * The image edit was successfully retrieved.
     */
    200: ImageEditDto;
};

export type ImageEditGetResponse = ImageEditGetResponses[keyof ImageEditGetResponses];

export type ImageEditGetMaskData = {
    body?: never;
    path: {
        /**
         * ID of the image completion to retrieve the mask for
         */
        imageCompletionId: string;
    };
    query?: never;
    url: '/image-edits/{imageCompletionId}/mask';
};

export type ImageEditGetMaskErrors = {
    400: unknown;
};

export type ImageEditGetMaskResponses = {
    200: ImageEditMaskDto;
};

export type ImageEditGetMaskResponse = ImageEditGetMaskResponses[keyof ImageEditGetMaskResponses];

export type ModelsFindData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Field to sort by
         */
        sortBy?: string;
        /**
         * Sort order (case insensitive)
         */
        sortOrder?: 'ASC' | 'DESC' | 'asc' | 'desc';
        search?: string;
        name?: string;
        userId?: string;
        username?: string;
        class?: string;
        type?: string;
        description?: string;
        privacy?: 'public' | 'private' | 'licensed';
        systemVersion?: number;
        status?: 'new' | 'pending' | 'training' | 'finished' | 'available' | 'failed';
        isActive?: boolean;
    };
    url: '/models';
};

export type ModelsFindErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Invalid query parameters
     * - Invalid pagination values
     * - Invalid sort parameters
     * - Malformed filters
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to access these models.
     */
    403: unknown;
    /**
     * Unprocessable Entity. The search request contains invalid data.
     */
    422: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while retrieving models.
     */
    500: unknown;
};

export type ModelsFindResponses = {
    /**
     * List of models matching the search criteria.
     */
    200: Array<ModelDto>;
};

export type ModelsFindResponse = ModelsFindResponses[keyof ModelsFindResponses];

export type ModelsCreateData = {
    /**
     * The model creation request payload
     */
    body: ModelCreateRequest;
    path?: never;
    query?: never;
    url: '/models';
};

export type ModelsCreateErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - `name`: Must contain only alphanumeric characters, underscores, and dots.
     * - `name`: Must be shorter than or equal to 255 characters.
     * - `privacy`: Must be a valid value from the `PrivacyEnum`.
     * - `type`: Must contain only allowed characters (alphanumeric, commas, hyphens, etc.).
     * - `class`: Must be a valid value from the `ClassEnum`.
     * - `trainingDataUrls`: Must be an array of valid URLs (max 50).
     * - `webhookUrl`: Must be a valid URL.
     * - `trainingMode`: Must be a valid value from the `TrainingModeEnum`.
     * - `organizationId`: Must be a valid UUID format.
     * - Missing or invalid `class` field (mandatory).
     * - Failed to analyze model type due to invalid training data URLs.
     * - Organization does not exist.
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated, or user is not a member of the specified organization.
     */
    401: unknown;
    /**
     * Payment Required. Insufficient credits to create the model (either user or organization credits depending on request).
     */
    402: unknown;
    /**
     * Not Found. The requested resource could not be found.
     */
    404: unknown;
    /**
     * Internal Server Error. An unexpected error occurred.
     */
    500: unknown;
};

export type ModelsCreateResponses = {
    /**
     * The model was successfully created.
     */
    200: ModelDto;
};

export type ModelsCreateResponse = ModelsCreateResponses[keyof ModelsCreateResponses];

export type ModelsDeleteData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the model to delete
         */
        id: string;
    };
    query?: never;
    url: '/models/{id}';
};

export type ModelsDeleteErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Invalid ID format
     * - Model does not exist
     * - Model is in use by active generations
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to delete this model.
     */
    403: unknown;
    /**
     * Not Found. The requested model could not be found.
     */
    404: unknown;
    /**
     * Conflict. The model cannot be deleted because it is being used by other resources.
     */
    409: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while deleting the model.
     */
    500: unknown;
};

export type ModelsDeleteResponses = {
    /**
     * The model was successfully deleted.
     */
    204: void;
};

export type ModelsDeleteResponse = ModelsDeleteResponses[keyof ModelsDeleteResponses];

export type ModelsGetData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the model to retrieve
         */
        id: string;
    };
    query?: never;
    url: '/models/{id}';
};

export type ModelsGetErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Invalid ID format
     * - Model does not exist
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to view this model.
     */
    403: unknown;
    /**
     * Not Found. The requested model could not be found.
     */
    404: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while retrieving the model.
     */
    500: unknown;
};

export type ModelsGetResponses = {
    /**
     * The requested model details.
     */
    200: ModelDto;
};

export type ModelsGetResponse = ModelsGetResponses[keyof ModelsGetResponses];

export type ModelUpdateData = {
    body: ModelUpdateRequest;
    path: {
        /**
         * Model ID
         */
        id: string;
    };
    query?: never;
    url: '/models/{id}';
};

export type ModelUpdateErrors = {
    /**
     * Invalid request parameters or model ID format
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to update this model
     */
    403: unknown;
    /**
     * Not Found. The model to update could not be found
     */
    404: unknown;
};

export type ModelUpdateResponses = {
    /**
     * The model was successfully updated
     */
    200: ModelDto;
};

export type ModelUpdateResponse = ModelUpdateResponses[keyof ModelUpdateResponses];

export type ModelThumbnailData = {
    /**
     * The thumbnail update request containing the image completion ID
     */
    body: ModelThumbnailRequest;
    path: {
        /**
         * The unique identifier of the model to update
         */
        id: string;
    };
    query?: never;
    url: '/models/{id}/thumbnail';
};

export type ModelThumbnailErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Invalid model ID format
     * - Invalid image completion ID
     * - Image completion not found
     * - Image completion not ready
     * - Image completion belongs to different user
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to update this model.
     */
    403: unknown;
    /**
     * Not Found. The model to update could not be found.
     */
    404: unknown;
    /**
     *
     * Conflict. Possible reasons:
     * - Model is currently being processed
     * - Model is in an invalid state for updates
     *
     */
    409: unknown;
    /**
     * Unprocessable Entity. The request payload contains invalid data.
     */
    422: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while updating the thumbnail.
     */
    500: unknown;
};

export type ModelThumbnailResponses = {
    /**
     * The model thumbnail was successfully updated.
     */
    200: ModelDto;
};

export type ModelThumbnailResponse = ModelThumbnailResponses[keyof ModelThumbnailResponses];

export type UpscaleFindData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Field to sort by
         */
        sortBy?: string;
        /**
         * Sort order (case insensitive)
         */
        sortOrder?: 'ASC' | 'DESC' | 'asc' | 'desc';
        userId?: string;
        username?: string;
        imageId?: string;
        status?: 'new' | 'generating' | 'ready' | 'failed';
        onlyFollowing?: boolean;
    };
    url: '/upscale';
};

export type UpscaleFindErrors = {
    /**
     * Bad Request. The request parameters are invalid.
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to access these upscales.
     */
    403: unknown;
    /**
     * Unprocessable Entity. Invalid search parameters.
     */
    422: unknown;
    /**
     * Internal Server Error. An unexpected error occurred.
     */
    500: unknown;
};

export type UpscaleFindResponses = {
    /**
     * List of upscales matching the search criteria.
     */
    200: Array<UpscaleDto>;
};

export type UpscaleFindResponse = UpscaleFindResponses[keyof UpscaleFindResponses];

export type UpscaleCreateData = {
    /**
     * The upscale request parameters
     */
    body: UpscaleRequest;
    path?: never;
    query?: never;
    url: '/upscale';
};

export type UpscaleCreateErrors = {
    /**
     *
     * Bad Request. Possible reasons:
     * - Invalid image ID
     * - Invalid upscale parameters
     * - Source image not found
     * - Source image not in ready state
     * - organizationId: Must be a valid UUID format
     * - Organization does not exist
     * - User is not a member of the organization
     * - Size must be at least 2
     * - Size must be at most 12
     * - Mode must be a valid value from the `ModeEnum`.
     *
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated, or user is not a member of the specified organization.
     */
    401: unknown;
    /**
     * Payment Required. Insufficient credit balance (either user or organization credits depending on request).
     */
    402: unknown;
    /**
     * Forbidden. User does not have permission to upscale this image.
     */
    403: unknown;
    /**
     * Unprocessable Entity. The request payload contains invalid data.
     */
    422: unknown;
    /**
     * Internal Server Error. An unexpected error occurred.
     */
    500: unknown;
};

export type UpscaleCreateResponses = {
    /**
     * The upscale request was successfully created.
     */
    201: UpscaleDto;
};

export type UpscaleCreateResponse = UpscaleCreateResponses[keyof UpscaleCreateResponses];

export type UpscaleDeleteData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the upscale to delete
         */
        id: string;
    };
    query?: never;
    url: '/upscale/{id}';
};

export type UpscaleDeleteErrors = {
    /**
     * Bad Request. The request parameters are invalid.
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to delete this upscale.
     */
    403: unknown;
    /**
     * Not Found. The upscale to delete could not be found.
     */
    404: unknown;
    /**
     * Unprocessable Entity. Invalid request parameters.
     */
    422: unknown;
    /**
     * Internal Server Error. An unexpected error occurred.
     */
    500: unknown;
};

export type UpscaleDeleteResponses = {
    /**
     * The upscale was successfully deleted.
     */
    204: void;
};

export type UpscaleDeleteResponse = UpscaleDeleteResponses[keyof UpscaleDeleteResponses];

export type UpscaleGetData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the upscale to retrieve
         */
        id: string;
    };
    query?: never;
    url: '/upscale/{id}';
};

export type UpscaleGetErrors = {
    /**
     * Bad Request. The request parameters are invalid.
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated.
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to access this upscale.
     */
    403: unknown;
    /**
     * Not Found. The requested upscale could not be found.
     */
    404: unknown;
    /**
     * Internal Server Error. An unexpected error occurred.
     */
    500: unknown;
};

export type UpscaleGetResponses = {
    /**
     * The requested upscale details.
     */
    200: UpscaleDto;
};

export type UpscaleGetResponse = UpscaleGetResponses[keyof UpscaleGetResponses];

export type UserImageListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user-images';
};

export type UserImageListErrors = {
    /**
     * Invalid request parameters
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to list images
     */
    403: unknown;
    /**
     * Unprocessable Entity. Invalid request parameters
     */
    422: unknown;
    /**
     * Too Many Requests. Please try again later
     */
    429: unknown;
    /**
     * Internal Server Error. An unexpected error occurred
     */
    500: unknown;
};

export type UserImageListResponses = {
    /**
     * List of user images retrieved successfully
     */
    200: Array<UserImageDto>;
};

export type UserImageListResponse = UserImageListResponses[keyof UserImageListResponses];

export type UserImageCreateData = {
    body: UserImageRequest;
    path?: never;
    query?: never;
    url: '/user-images';
};

export type UserImageCreateErrors = {
    /**
     * Invalid request parameters
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated
     */
    401: unknown;
    /**
     * Payment Required. Insufficient credit balance.
     */
    402: unknown;
    /**
     * Forbidden. User does not have permission to create images
     */
    403: unknown;
    /**
     * Not Found. The requested resource could not be found.
     */
    404: unknown;
    /**
     * Unprocessable Entity. The request payload contains invalid data.
     */
    422: unknown;
    /**
     * Too Many Requests. Please try again later.
     */
    429: unknown;
    /**
     * Internal Server Error. An unexpected error occurred.
     */
    500: unknown;
};

export type UserImageCreateResponses = {
    /**
     * The user image was successfully created
     */
    200: UserImageDto;
};

export type UserImageCreateResponse = UserImageCreateResponses[keyof UserImageCreateResponses];

export type UserImageDeleteData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: string;
    };
    query?: never;
    url: '/user-images/{id}';
};

export type UserImageDeleteErrors = {
    /**
     * Invalid image ID format
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to delete this image
     */
    403: unknown;
    /**
     * Not Found. The image to delete could not be found
     */
    404: unknown;
    /**
     * Unprocessable Entity. Invalid request parameters
     */
    422: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while deleting the image
     */
    500: unknown;
};

export type UserImageDeleteResponses = {
    /**
     * The image was successfully deleted
     */
    204: void;
};

export type UserImageDeleteResponse = UserImageDeleteResponses[keyof UserImageDeleteResponses];

export type UserImageGetData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: string;
    };
    query?: never;
    url: '/user-images/{id}';
};

export type UserImageGetErrors = {
    /**
     * Invalid image ID format
     */
    400: unknown;
    /**
     * Unauthorized. The user is not authenticated
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to access this image
     */
    403: unknown;
    /**
     * Not Found. The requested image could not be found
     */
    404: unknown;
    /**
     * Unprocessable Entity. Invalid request parameters
     */
    422: unknown;
    /**
     * Too Many Requests. Please try again later
     */
    429: unknown;
    /**
     * Internal Server Error. An unexpected error occurred
     */
    500: unknown;
};

export type UserImageGetResponses = {
    /**
     * The user image was successfully retrieved
     */
    200: UserImageDto;
};

export type UserImageGetResponse = UserImageGetResponses[keyof UserImageGetResponses];

export type PublicVideoListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Field to sort by
         */
        sortBy?: string;
        /**
         * Sort order (case insensitive)
         */
        sortOrder?: 'ASC' | 'DESC' | 'asc' | 'desc';
        /**
         * Filter by user ID
         */
        userId?: string;
        /**
         * Filter by username
         */
        username?: string;
        /**
         * Filter by organization ID
         */
        organizationId?: string;
        /**
         * Filter by original image completion ID
         */
        originalImageCompletionId?: string;
        /**
         * Filter by prompt text
         */
        prompt?: string;
        /**
         * Filter by video status
         */
        status?: 'new' | 'generating' | 'ready' | 'saved' | 'failed' | 'interrupted';
        /**
         * Filter by width
         */
        width?: number;
        /**
         * Filter by height
         */
        height?: number;
        /**
         * Filter by resolution
         */
        resolution?: number;
        /**
         * Filter by NSFW content
         */
        isNsfw?: boolean;
        /**
         * Filter by hot content
         */
        isHot?: boolean;
        /**
         * Filter by unsafe content
         */
        isUnsafe?: boolean;
        /**
         * Filter by hidden prompts
         */
        hidePrompt?: boolean;
    };
    url: '/videos';
};

export type PublicVideoListErrors = {
    /**
     * Bad Request. Possible reasons:
     *
     * - Pagination parameters (page, limit) must be positive integers between 1 and 50.
     * - Sort parameters (sortBy, sortOrder) must be valid values.
     * - Filter parameters must be valid values.
     * - userId: Must be a valid UUID.
     * - username: Must be a valid username.
     * - status: Must be a valid video status.
     * - width/height/resolution: Must be valid numbers.
     *
     */
    400: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while retrieving videos.
     */
    500: unknown;
};

export type PublicVideoListResponses = {
    /**
     * Paginated list of videos
     */
    200: Array<VideoDto>;
};

export type PublicVideoListResponse = PublicVideoListResponses[keyof PublicVideoListResponses];

export type PublicVideoCreateData = {
    /**
     * Video creation request parameters
     */
    body: PublicVideoRequest;
    path?: never;
    query?: never;
    url: '/videos';
};

export type PublicVideoCreateErrors = {
    /**
     * Bad Request. Possible reasons:
     *
     * - Missing required fields (prompt, originalImageCompletionId or imageUrl)
     * - Invalid field values or formats
     * - Invalid UUID format for originalImageCompletionId or organizationId
     * - Invalid URL format for imageUrl or webhookUrl
     * - Width, height, resolution must be positive integers
     * - Settings must be a valid object
     *
     */
    400: unknown;
    /**
     * Unauthorized. Valid JWT token required.
     */
    401: unknown;
    /**
     * Forbidden. User does not have permission to create videos.
     */
    403: unknown;
    /**
     * Not Found. Referenced originalImageCompletionId does not exist.
     */
    404: unknown;
    /**
     * Too Many Requests. Rate limit exceeded.
     */
    429: unknown;
    /**
     * Internal Server Error. An unexpected error occurred during video creation.
     */
    500: unknown;
};

export type PublicVideoCreateResponses = {
    /**
     * Video creation request submitted successfully
     */
    201: VideoDto;
};

export type PublicVideoCreateResponse = PublicVideoCreateResponses[keyof PublicVideoCreateResponses];

export type PublicVideoGetData = {
    body?: never;
    path: {
        /**
         * UUID of the video to retrieve.
         */
        id: string;
    };
    query?: never;
    url: '/videos/{id}';
};

export type PublicVideoGetErrors = {
    /**
     * Bad Request. Possible reasons:
     *
     * - id: Must be a valid UUID.
     * - Video does not exist.
     * - Invalid or unavailable parameters.
     *
     */
    400: unknown;
    /**
     * Not Found. Video with the specified ID does not exist.
     */
    404: unknown;
    /**
     * Internal Server Error. An unexpected error occurred while retrieving the video.
     */
    500: unknown;
};

export type PublicVideoGetResponses = {
    /**
     * Returns the video with the specified ID.
     */
    200: VideoDto;
};

export type PublicVideoGetResponse = PublicVideoGetResponses[keyof PublicVideoGetResponses];

export type PublicVideosPrivacyChangeData = {
    /**
     * Privacy update parameters.
     */
    body: VideoPrivacyRequest;
    path: {
        /**
         * The unique identifier of the video to update
         */
        id: string;
    };
    query?: never;
    url: '/videos/{id}/privacy';
};

export type PublicVideosPrivacyChangeErrors = {
    /**
     * Bad Request. Invalid video ID or parameters
     */
    400: unknown;
    /**
     * Unauthorized. Authentication required
     */
    401: unknown;
    /**
     * Not Found. The video could not be found
     */
    404: unknown;
    /**
     * Internal Server Error. Unexpected error occurred
     */
    500: unknown;
};

export type PublicVideosPrivacyChangeResponses = {
    /**
     * Video privacy updated successfully
     */
    204: void;
};

export type PublicVideosPrivacyChangeResponse = PublicVideosPrivacyChangeResponses[keyof PublicVideosPrivacyChangeResponses];

export type PublicVideosPromptPrivacyChangeData = {
    /**
     * Prompt privacy update parameters.
     */
    body: VideoPromptPrivacyRequest;
    path: {
        /**
         * The unique identifier of the video to update
         */
        id: string;
    };
    query?: never;
    url: '/videos/{id}/prompt-privacy';
};

export type PublicVideosPromptPrivacyChangeErrors = {
    /**
     * Bad Request. Invalid video ID or parameters
     */
    400: unknown;
    /**
     * Unauthorized. Authentication required
     */
    401: unknown;
    /**
     * Not Found. The video could not be found
     */
    404: unknown;
    /**
     * Internal Server Error. Unexpected error occurred
     */
    500: unknown;
};

export type PublicVideosPromptPrivacyChangeResponses = {
    /**
     * Video prompt privacy updated successfully
     */
    204: void;
};

export type PublicVideosPromptPrivacyChangeResponse = PublicVideosPromptPrivacyChangeResponses[keyof PublicVideosPromptPrivacyChangeResponses];
