/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route';
import { Route as AuthRouteRouteImport } from './routes/_auth/route';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ApiRealtimeRouteImport } from './routes/api/realtime';
import { Route as ApiMcpRouteImport } from './routes/api/mcp';
import { Route as ApiHealthRouteImport } from './routes/api/health';
import { Route as ProtectedEvalRouteImport } from './routes/_protected/eval';
import { Route as AuthLoginRouteImport } from './routes/_auth/login';
import { Route as AuthInviteCodeRouteImport } from './routes/_auth/invite-code';
import { Route as ProtectedSequencesIndexRouteImport } from './routes/_protected/sequences/index';
import { Route as ProtectedCharactersIndexRouteImport } from './routes/_protected/characters/index';
import { Route as ApiWorkflowsSplatRouteImport } from './routes/api/workflows/$';
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$';
import { Route as ProtectedSequencesNewRouteImport } from './routes/_protected/sequences/new';
import { Route as ProtectedCharactersIdRouteImport } from './routes/_protected/characters/$id';
import { Route as ApiWorkflowsStatusRunIdRouteImport } from './routes/api/workflows/status/$runId';
import { Route as ApiMcpStreamVisualPromptsRouteImport } from './routes/api/mcp/stream/visual-prompts';
import { Route as ApiMcpStreamSplitScenesRouteImport } from './routes/api/mcp/stream/split-scenes';
import { Route as ApiMcpStreamMotionPromptsRouteImport } from './routes/api/mcp/stream/motion-prompts';
import { Route as ApiMcpStreamExtractCharactersRouteImport } from './routes/api/mcp/stream/extract-characters';
import { Route as ApiMcpStreamAudioDesignRouteImport } from './routes/api/mcp/stream/audio-design';
import { Route as ApiMcpStreamAnalyzeScriptRouteImport } from './routes/api/mcp/stream/analyze-script';
import { Route as ProtectedSequencesIdScriptRouteImport } from './routes/_protected/sequences/$id/script';
import { Route as ProtectedSequencesIdScenesRouteImport } from './routes/_protected/sequences/$id/scenes';
import { Route as ApiTeamsInvitationsInvitationIdAcceptRouteImport } from './routes/api/teams/invitations/$invitationId/accept';
import { Route as ApiSequencesSequenceIdChaptersVttRouteImport } from './routes/api/sequences/$sequenceId/chapters/vtt';

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedEvalRoute = ProtectedEvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => ProtectedRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthInviteCodeRoute = AuthInviteCodeRouteImport.update({
  id: '/invite-code',
  path: '/invite-code',
  getParentRoute: () => AuthRouteRoute,
} as any);
const ProtectedSequencesIndexRoute = ProtectedSequencesIndexRouteImport.update({
  id: '/sequences/',
  path: '/sequences/',
  getParentRoute: () => ProtectedRouteRoute,
} as any);
const ProtectedCharactersIndexRoute =
  ProtectedCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any);
const ApiWorkflowsSplatRoute = ApiWorkflowsSplatRouteImport.update({
  id: '/api/workflows/$',
  path: '/api/workflows/$',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedSequencesNewRoute = ProtectedSequencesNewRouteImport.update({
  id: '/sequences/new',
  path: '/sequences/new',
  getParentRoute: () => ProtectedRouteRoute,
} as any);
const ProtectedCharactersIdRoute = ProtectedCharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any);
const ApiWorkflowsStatusRunIdRoute = ApiWorkflowsStatusRunIdRouteImport.update({
  id: '/api/workflows/status/$runId',
  path: '/api/workflows/status/$runId',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiMcpStreamVisualPromptsRoute =
  ApiMcpStreamVisualPromptsRouteImport.update({
    id: '/stream/visual-prompts',
    path: '/stream/visual-prompts',
    getParentRoute: () => ApiMcpRoute,
  } as any);
const ApiMcpStreamSplitScenesRoute = ApiMcpStreamSplitScenesRouteImport.update({
  id: '/stream/split-scenes',
  path: '/stream/split-scenes',
  getParentRoute: () => ApiMcpRoute,
} as any);
const ApiMcpStreamMotionPromptsRoute =
  ApiMcpStreamMotionPromptsRouteImport.update({
    id: '/stream/motion-prompts',
    path: '/stream/motion-prompts',
    getParentRoute: () => ApiMcpRoute,
  } as any);
const ApiMcpStreamExtractCharactersRoute =
  ApiMcpStreamExtractCharactersRouteImport.update({
    id: '/stream/extract-characters',
    path: '/stream/extract-characters',
    getParentRoute: () => ApiMcpRoute,
  } as any);
const ApiMcpStreamAudioDesignRoute = ApiMcpStreamAudioDesignRouteImport.update({
  id: '/stream/audio-design',
  path: '/stream/audio-design',
  getParentRoute: () => ApiMcpRoute,
} as any);
const ApiMcpStreamAnalyzeScriptRoute =
  ApiMcpStreamAnalyzeScriptRouteImport.update({
    id: '/stream/analyze-script',
    path: '/stream/analyze-script',
    getParentRoute: () => ApiMcpRoute,
  } as any);
const ProtectedSequencesIdScriptRoute =
  ProtectedSequencesIdScriptRouteImport.update({
    id: '/sequences/$id/script',
    path: '/sequences/$id/script',
    getParentRoute: () => ProtectedRouteRoute,
  } as any);
const ProtectedSequencesIdScenesRoute =
  ProtectedSequencesIdScenesRouteImport.update({
    id: '/sequences/$id/scenes',
    path: '/sequences/$id/scenes',
    getParentRoute: () => ProtectedRouteRoute,
  } as any);
const ApiTeamsInvitationsInvitationIdAcceptRoute =
  ApiTeamsInvitationsInvitationIdAcceptRouteImport.update({
    id: '/api/teams/invitations/$invitationId/accept',
    path: '/api/teams/invitations/$invitationId/accept',
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiSequencesSequenceIdChaptersVttRoute =
  ApiSequencesSequenceIdChaptersVttRouteImport.update({
    id: '/api/sequences/$sequenceId/chapters/vtt',
    path: '/api/sequences/$sequenceId/chapters/vtt',
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/invite-code': typeof AuthInviteCodeRoute;
  '/login': typeof AuthLoginRoute;
  '/eval': typeof ProtectedEvalRoute;
  '/api/health': typeof ApiHealthRoute;
  '/api/mcp': typeof ApiMcpRouteWithChildren;
  '/api/realtime': typeof ApiRealtimeRoute;
  '/characters/$id': typeof ProtectedCharactersIdRoute;
  '/sequences/new': typeof ProtectedSequencesNewRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute;
  '/characters': typeof ProtectedCharactersIndexRoute;
  '/sequences': typeof ProtectedSequencesIndexRoute;
  '/sequences/$id/scenes': typeof ProtectedSequencesIdScenesRoute;
  '/sequences/$id/script': typeof ProtectedSequencesIdScriptRoute;
  '/api/mcp/stream/analyze-script': typeof ApiMcpStreamAnalyzeScriptRoute;
  '/api/mcp/stream/audio-design': typeof ApiMcpStreamAudioDesignRoute;
  '/api/mcp/stream/extract-characters': typeof ApiMcpStreamExtractCharactersRoute;
  '/api/mcp/stream/motion-prompts': typeof ApiMcpStreamMotionPromptsRoute;
  '/api/mcp/stream/split-scenes': typeof ApiMcpStreamSplitScenesRoute;
  '/api/mcp/stream/visual-prompts': typeof ApiMcpStreamVisualPromptsRoute;
  '/api/workflows/status/$runId': typeof ApiWorkflowsStatusRunIdRoute;
  '/api/sequences/$sequenceId/chapters/vtt': typeof ApiSequencesSequenceIdChaptersVttRoute;
  '/api/teams/invitations/$invitationId/accept': typeof ApiTeamsInvitationsInvitationIdAcceptRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/invite-code': typeof AuthInviteCodeRoute;
  '/login': typeof AuthLoginRoute;
  '/eval': typeof ProtectedEvalRoute;
  '/api/health': typeof ApiHealthRoute;
  '/api/mcp': typeof ApiMcpRouteWithChildren;
  '/api/realtime': typeof ApiRealtimeRoute;
  '/characters/$id': typeof ProtectedCharactersIdRoute;
  '/sequences/new': typeof ProtectedSequencesNewRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute;
  '/characters': typeof ProtectedCharactersIndexRoute;
  '/sequences': typeof ProtectedSequencesIndexRoute;
  '/sequences/$id/scenes': typeof ProtectedSequencesIdScenesRoute;
  '/sequences/$id/script': typeof ProtectedSequencesIdScriptRoute;
  '/api/mcp/stream/analyze-script': typeof ApiMcpStreamAnalyzeScriptRoute;
  '/api/mcp/stream/audio-design': typeof ApiMcpStreamAudioDesignRoute;
  '/api/mcp/stream/extract-characters': typeof ApiMcpStreamExtractCharactersRoute;
  '/api/mcp/stream/motion-prompts': typeof ApiMcpStreamMotionPromptsRoute;
  '/api/mcp/stream/split-scenes': typeof ApiMcpStreamSplitScenesRoute;
  '/api/mcp/stream/visual-prompts': typeof ApiMcpStreamVisualPromptsRoute;
  '/api/workflows/status/$runId': typeof ApiWorkflowsStatusRunIdRoute;
  '/api/sequences/$sequenceId/chapters/vtt': typeof ApiSequencesSequenceIdChaptersVttRoute;
  '/api/teams/invitations/$invitationId/accept': typeof ApiTeamsInvitationsInvitationIdAcceptRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteRouteWithChildren;
  '/_protected': typeof ProtectedRouteRouteWithChildren;
  '/_auth/invite-code': typeof AuthInviteCodeRoute;
  '/_auth/login': typeof AuthLoginRoute;
  '/_protected/eval': typeof ProtectedEvalRoute;
  '/api/health': typeof ApiHealthRoute;
  '/api/mcp': typeof ApiMcpRouteWithChildren;
  '/api/realtime': typeof ApiRealtimeRoute;
  '/_protected/characters/$id': typeof ProtectedCharactersIdRoute;
  '/_protected/sequences/new': typeof ProtectedSequencesNewRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute;
  '/_protected/characters/': typeof ProtectedCharactersIndexRoute;
  '/_protected/sequences/': typeof ProtectedSequencesIndexRoute;
  '/_protected/sequences/$id/scenes': typeof ProtectedSequencesIdScenesRoute;
  '/_protected/sequences/$id/script': typeof ProtectedSequencesIdScriptRoute;
  '/api/mcp/stream/analyze-script': typeof ApiMcpStreamAnalyzeScriptRoute;
  '/api/mcp/stream/audio-design': typeof ApiMcpStreamAudioDesignRoute;
  '/api/mcp/stream/extract-characters': typeof ApiMcpStreamExtractCharactersRoute;
  '/api/mcp/stream/motion-prompts': typeof ApiMcpStreamMotionPromptsRoute;
  '/api/mcp/stream/split-scenes': typeof ApiMcpStreamSplitScenesRoute;
  '/api/mcp/stream/visual-prompts': typeof ApiMcpStreamVisualPromptsRoute;
  '/api/workflows/status/$runId': typeof ApiWorkflowsStatusRunIdRoute;
  '/api/sequences/$sequenceId/chapters/vtt': typeof ApiSequencesSequenceIdChaptersVttRoute;
  '/api/teams/invitations/$invitationId/accept': typeof ApiTeamsInvitationsInvitationIdAcceptRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/invite-code'
    | '/login'
    | '/eval'
    | '/api/health'
    | '/api/mcp'
    | '/api/realtime'
    | '/characters/$id'
    | '/sequences/new'
    | '/api/auth/$'
    | '/api/workflows/$'
    | '/characters'
    | '/sequences'
    | '/sequences/$id/scenes'
    | '/sequences/$id/script'
    | '/api/mcp/stream/analyze-script'
    | '/api/mcp/stream/audio-design'
    | '/api/mcp/stream/extract-characters'
    | '/api/mcp/stream/motion-prompts'
    | '/api/mcp/stream/split-scenes'
    | '/api/mcp/stream/visual-prompts'
    | '/api/workflows/status/$runId'
    | '/api/sequences/$sequenceId/chapters/vtt'
    | '/api/teams/invitations/$invitationId/accept';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/invite-code'
    | '/login'
    | '/eval'
    | '/api/health'
    | '/api/mcp'
    | '/api/realtime'
    | '/characters/$id'
    | '/sequences/new'
    | '/api/auth/$'
    | '/api/workflows/$'
    | '/characters'
    | '/sequences'
    | '/sequences/$id/scenes'
    | '/sequences/$id/script'
    | '/api/mcp/stream/analyze-script'
    | '/api/mcp/stream/audio-design'
    | '/api/mcp/stream/extract-characters'
    | '/api/mcp/stream/motion-prompts'
    | '/api/mcp/stream/split-scenes'
    | '/api/mcp/stream/visual-prompts'
    | '/api/workflows/status/$runId'
    | '/api/sequences/$sequenceId/chapters/vtt'
    | '/api/teams/invitations/$invitationId/accept';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/invite-code'
    | '/_auth/login'
    | '/_protected/eval'
    | '/api/health'
    | '/api/mcp'
    | '/api/realtime'
    | '/_protected/characters/$id'
    | '/_protected/sequences/new'
    | '/api/auth/$'
    | '/api/workflows/$'
    | '/_protected/characters/'
    | '/_protected/sequences/'
    | '/_protected/sequences/$id/scenes'
    | '/_protected/sequences/$id/script'
    | '/api/mcp/stream/analyze-script'
    | '/api/mcp/stream/audio-design'
    | '/api/mcp/stream/extract-characters'
    | '/api/mcp/stream/motion-prompts'
    | '/api/mcp/stream/split-scenes'
    | '/api/mcp/stream/visual-prompts'
    | '/api/workflows/status/$runId'
    | '/api/sequences/$sequenceId/chapters/vtt'
    | '/api/teams/invitations/$invitationId/accept';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren;
  ApiHealthRoute: typeof ApiHealthRoute;
  ApiMcpRoute: typeof ApiMcpRouteWithChildren;
  ApiRealtimeRoute: typeof ApiRealtimeRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiWorkflowsSplatRoute: typeof ApiWorkflowsSplatRoute;
  ApiWorkflowsStatusRunIdRoute: typeof ApiWorkflowsStatusRunIdRoute;
  ApiSequencesSequenceIdChaptersVttRoute: typeof ApiSequencesSequenceIdChaptersVttRoute;
  ApiTeamsInvitationsInvitationIdAcceptRoute: typeof ApiTeamsInvitationsInvitationIdAcceptRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof ProtectedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/realtime': {
      id: '/api/realtime';
      path: '/api/realtime';
      fullPath: '/api/realtime';
      preLoaderRoute: typeof ApiRealtimeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/mcp': {
      id: '/api/mcp';
      path: '/api/mcp';
      fullPath: '/api/mcp';
      preLoaderRoute: typeof ApiMcpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/health': {
      id: '/api/health';
      path: '/api/health';
      fullPath: '/api/health';
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/eval': {
      id: '/_protected/eval';
      path: '/eval';
      fullPath: '/eval';
      preLoaderRoute: typeof ProtectedEvalRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
    '/_auth/login': {
      id: '/_auth/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    '/_auth/invite-code': {
      id: '/_auth/invite-code';
      path: '/invite-code';
      fullPath: '/invite-code';
      preLoaderRoute: typeof AuthInviteCodeRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    '/_protected/sequences/': {
      id: '/_protected/sequences/';
      path: '/sequences';
      fullPath: '/sequences';
      preLoaderRoute: typeof ProtectedSequencesIndexRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
    '/_protected/characters/': {
      id: '/_protected/characters/';
      path: '/characters';
      fullPath: '/characters';
      preLoaderRoute: typeof ProtectedCharactersIndexRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
    '/api/workflows/$': {
      id: '/api/workflows/$';
      path: '/api/workflows/$';
      fullPath: '/api/workflows/$';
      preLoaderRoute: typeof ApiWorkflowsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/$': {
      id: '/api/auth/$';
      path: '/api/auth/$';
      fullPath: '/api/auth/$';
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/sequences/new': {
      id: '/_protected/sequences/new';
      path: '/sequences/new';
      fullPath: '/sequences/new';
      preLoaderRoute: typeof ProtectedSequencesNewRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
    '/_protected/characters/$id': {
      id: '/_protected/characters/$id';
      path: '/characters/$id';
      fullPath: '/characters/$id';
      preLoaderRoute: typeof ProtectedCharactersIdRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
    '/api/workflows/status/$runId': {
      id: '/api/workflows/status/$runId';
      path: '/api/workflows/status/$runId';
      fullPath: '/api/workflows/status/$runId';
      preLoaderRoute: typeof ApiWorkflowsStatusRunIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/mcp/stream/visual-prompts': {
      id: '/api/mcp/stream/visual-prompts';
      path: '/stream/visual-prompts';
      fullPath: '/api/mcp/stream/visual-prompts';
      preLoaderRoute: typeof ApiMcpStreamVisualPromptsRouteImport;
      parentRoute: typeof ApiMcpRoute;
    };
    '/api/mcp/stream/split-scenes': {
      id: '/api/mcp/stream/split-scenes';
      path: '/stream/split-scenes';
      fullPath: '/api/mcp/stream/split-scenes';
      preLoaderRoute: typeof ApiMcpStreamSplitScenesRouteImport;
      parentRoute: typeof ApiMcpRoute;
    };
    '/api/mcp/stream/motion-prompts': {
      id: '/api/mcp/stream/motion-prompts';
      path: '/stream/motion-prompts';
      fullPath: '/api/mcp/stream/motion-prompts';
      preLoaderRoute: typeof ApiMcpStreamMotionPromptsRouteImport;
      parentRoute: typeof ApiMcpRoute;
    };
    '/api/mcp/stream/extract-characters': {
      id: '/api/mcp/stream/extract-characters';
      path: '/stream/extract-characters';
      fullPath: '/api/mcp/stream/extract-characters';
      preLoaderRoute: typeof ApiMcpStreamExtractCharactersRouteImport;
      parentRoute: typeof ApiMcpRoute;
    };
    '/api/mcp/stream/audio-design': {
      id: '/api/mcp/stream/audio-design';
      path: '/stream/audio-design';
      fullPath: '/api/mcp/stream/audio-design';
      preLoaderRoute: typeof ApiMcpStreamAudioDesignRouteImport;
      parentRoute: typeof ApiMcpRoute;
    };
    '/api/mcp/stream/analyze-script': {
      id: '/api/mcp/stream/analyze-script';
      path: '/stream/analyze-script';
      fullPath: '/api/mcp/stream/analyze-script';
      preLoaderRoute: typeof ApiMcpStreamAnalyzeScriptRouteImport;
      parentRoute: typeof ApiMcpRoute;
    };
    '/_protected/sequences/$id/script': {
      id: '/_protected/sequences/$id/script';
      path: '/sequences/$id/script';
      fullPath: '/sequences/$id/script';
      preLoaderRoute: typeof ProtectedSequencesIdScriptRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
    '/_protected/sequences/$id/scenes': {
      id: '/_protected/sequences/$id/scenes';
      path: '/sequences/$id/scenes';
      fullPath: '/sequences/$id/scenes';
      preLoaderRoute: typeof ProtectedSequencesIdScenesRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
    '/api/teams/invitations/$invitationId/accept': {
      id: '/api/teams/invitations/$invitationId/accept';
      path: '/api/teams/invitations/$invitationId/accept';
      fullPath: '/api/teams/invitations/$invitationId/accept';
      preLoaderRoute: typeof ApiTeamsInvitationsInvitationIdAcceptRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/sequences/$sequenceId/chapters/vtt': {
      id: '/api/sequences/$sequenceId/chapters/vtt';
      path: '/api/sequences/$sequenceId/chapters/vtt';
      fullPath: '/api/sequences/$sequenceId/chapters/vtt';
      preLoaderRoute: typeof ApiSequencesSequenceIdChaptersVttRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AuthRouteRouteChildren {
  AuthInviteCodeRoute: typeof AuthInviteCodeRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthInviteCodeRoute: AuthInviteCodeRoute,
  AuthLoginRoute: AuthLoginRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren
);

interface ProtectedRouteRouteChildren {
  ProtectedEvalRoute: typeof ProtectedEvalRoute;
  ProtectedCharactersIdRoute: typeof ProtectedCharactersIdRoute;
  ProtectedSequencesNewRoute: typeof ProtectedSequencesNewRoute;
  ProtectedCharactersIndexRoute: typeof ProtectedCharactersIndexRoute;
  ProtectedSequencesIndexRoute: typeof ProtectedSequencesIndexRoute;
  ProtectedSequencesIdScenesRoute: typeof ProtectedSequencesIdScenesRoute;
  ProtectedSequencesIdScriptRoute: typeof ProtectedSequencesIdScriptRoute;
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedEvalRoute: ProtectedEvalRoute,
  ProtectedCharactersIdRoute: ProtectedCharactersIdRoute,
  ProtectedSequencesNewRoute: ProtectedSequencesNewRoute,
  ProtectedCharactersIndexRoute: ProtectedCharactersIndexRoute,
  ProtectedSequencesIndexRoute: ProtectedSequencesIndexRoute,
  ProtectedSequencesIdScenesRoute: ProtectedSequencesIdScenesRoute,
  ProtectedSequencesIdScriptRoute: ProtectedSequencesIdScriptRoute,
};

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren
);

interface ApiMcpRouteChildren {
  ApiMcpStreamAnalyzeScriptRoute: typeof ApiMcpStreamAnalyzeScriptRoute;
  ApiMcpStreamAudioDesignRoute: typeof ApiMcpStreamAudioDesignRoute;
  ApiMcpStreamExtractCharactersRoute: typeof ApiMcpStreamExtractCharactersRoute;
  ApiMcpStreamMotionPromptsRoute: typeof ApiMcpStreamMotionPromptsRoute;
  ApiMcpStreamSplitScenesRoute: typeof ApiMcpStreamSplitScenesRoute;
  ApiMcpStreamVisualPromptsRoute: typeof ApiMcpStreamVisualPromptsRoute;
}

const ApiMcpRouteChildren: ApiMcpRouteChildren = {
  ApiMcpStreamAnalyzeScriptRoute: ApiMcpStreamAnalyzeScriptRoute,
  ApiMcpStreamAudioDesignRoute: ApiMcpStreamAudioDesignRoute,
  ApiMcpStreamExtractCharactersRoute: ApiMcpStreamExtractCharactersRoute,
  ApiMcpStreamMotionPromptsRoute: ApiMcpStreamMotionPromptsRoute,
  ApiMcpStreamSplitScenesRoute: ApiMcpStreamSplitScenesRoute,
  ApiMcpStreamVisualPromptsRoute: ApiMcpStreamVisualPromptsRoute,
};

const ApiMcpRouteWithChildren =
  ApiMcpRoute._addFileChildren(ApiMcpRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRouteWithChildren,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWorkflowsSplatRoute: ApiWorkflowsSplatRoute,
  ApiWorkflowsStatusRunIdRoute: ApiWorkflowsStatusRunIdRoute,
  ApiSequencesSequenceIdChaptersVttRoute:
    ApiSequencesSequenceIdChaptersVttRoute,
  ApiTeamsInvitationsInvitationIdAcceptRoute:
    ApiTeamsInvitationsInvitationIdAcceptRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
